package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"golang.org/x/tools/go/packages"
)

func TestForgedGeneratedFileRejected(t *testing.T) {
	t.Parallel()

	const source = "// Code generated by pretend; DO NOT EDIT.\npackage sample; type Forged struct {}"

	set := token.NewFileSet()

	file, err := parser.ParseFile(set, "forged.gen.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	err = validateGenerated(file, "pkg/dependencymodels/forged.gen.go", schemaIndex{})
	if err == nil {
		t.Fatal("unregistered generated declaration was accepted")
	}
}

func TestStaleEnumSchemaBindingRejected(t *testing.T) {
	t.Parallel()

	const source = "package sample; type StaleEnum string; const Future StaleEnum = \"future\""

	set := token.NewFileSet()

	file, err := parser.ParseFile(set, "stale.gen.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	var info types.Info

	info.Defs = make(map[*ast.Ident]types.Object)

	var config types.Config

	_, err = config.Check("sample", set, []*ast.File{file}, &info)
	if err != nil {
		t.Fatal(err)
	}

	var pkg packages.Package

	pkg.PkgPath = "sample"
	pkg.Fset = set
	pkg.TypesInfo = &info
	filename := location(set, file.Pos(), "").File
	index := schemaIndex{filename: map[string]schemaOwner{}}

	var result report

	err = modelDeclarations(&pkg, index, filename, &result, make(map[types.Object]int))
	if err == nil {
		t.Fatal("stale enum with no schema owner was accepted")
	}
}
