package main

import (
	"bytes"
	"testing"
)

func TestPublicPackageCommentNormalization(t *testing.T) {
	t.Parallel()

	marker := "// Code generated by pinned-generator; DO NOT EDIT.\npackage roborock\n"
	boilerplate := "// Package roborock provides primitives to interact with the openapi HTTP API.\n//\n"

	output := normalizePackageComment("roborock", []byte(boilerplate+marker))
	if !bytes.Equal(output, []byte(marker)) {
		t.Fatalf("public package boilerplate was not removed: %s", output)
	}

	dependency := []byte(boilerplate + marker)

	output = normalizePackageComment("dependencymodels", dependency)

	if !bytes.Equal(output, dependency) {
		t.Fatal("dependency package documentation changed")
	}
}
