// Command generate reproducibly generates schema models and protocol constants.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/getkin/kin-openapi/openapi3"
)

const (
	generator           = "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.5.1"
	privateFileMode     = 0o600
	outputDirectoryMode = 0o750
	cliPackage          = "main"
	publicPackage       = "roborock"
)

var (
	errGeneratedDrift  = errors.New("generated output drift")
	errEmptyIdentifier = errors.New("empty schema identifier")
)

func main() {
	check := flag.Bool("check", false, "compare generated output without writing")

	flag.Parse()

	err := run(context.Background(), *check)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context, check bool) error {
	err := generateProtobuf(ctx, check)
	if err != nil {
		return err
	}

	schemas, err := filepath.Glob("api/*.openapi.yaml")
	if err != nil {
		return fmt.Errorf("find schemas: %w", err)
	}

	asyncSchemas, err := filepath.Glob("api/*.asyncapi.yaml")
	if err != nil {
		return fmt.Errorf("find MQTT schemas: %w", err)
	}

	schemas = append(schemas, asyncSchemas...)

	constants := make(map[string]string)

	for _, schema := range schemas {
		err = generateInput(ctx, schema, constants, check)
		if err != nil {
			return err
		}
	}

	err = mapAliases(check)
	if err != nil {
		return err
	}

	return restConstants(constants, check)
}

func generateSchema(ctx context.Context, schema string, constants map[string]string, check bool) error {
	name := strings.TrimSuffix(strings.TrimSuffix(filepath.Base(schema), ".openapi.yaml"), ".asyncapi.yaml")
	pkg, output := modelTarget(name)

	err := model(ctx, schema, pkg, output, check)
	if err != nil {
		return err
	}

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true

	doc, loadErr := loader.LoadFromFile(schema)
	if loadErr != nil {
		return fmt.Errorf("load %s: %w", schema, loadErr)
	}

	if name == "auth" || name == "devices" {
		collect(doc, constants)
	}

	err = wireConstants(doc, name, check)
	if err != nil {
		return err
	}

	err = known(doc, output, pkg, check)
	if err != nil {
		return err
	}

	return nil
}

func restConstants(constants map[string]string, check bool) error {
	var body bytes.Buffer

	body.WriteString("// Code generated by tools/generate from api/*.openapi.yaml; DO NOT EDIT.\n")
	body.WriteString("package protocol\n\nconst (\n")

	names := make([]string, 0, len(constants))
	for name := range constants {
		names = append(names, name)
	}

	sort.Strings(names)

	for _, name := range names {
		fmt.Fprintf(&body, "%s = %q\n", name, constants[name])
	}

	body.WriteString(")\n")

	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return fmt.Errorf("format constants: %w", err)
	}

	return write("internal/protocol/rest.gen.go", formatted, check)
}

func wireConstants(doc *openapi3.T, name string, check bool) error {
	value, exists := doc.Extensions["x-wire-constants"]
	if !exists {
		return nil
	}

	data, err := json.Marshal(value)
	if err != nil {
		return fmt.Errorf("encode wire constants: %w", err)
	}

	var constants map[string]json.RawMessage

	err = json.Unmarshal(data, &constants)
	if err != nil {
		return fmt.Errorf("read wire constants: %w", err)
	}

	declarations := make([]string, 0, len(constants))
	for identifier, literal := range constants {
		declarations = append(declarations, fmt.Sprintf("%s = %s", identifier, literal))
	}

	sort.Strings(declarations)

	source := "// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.\n"
	source += "package protocol\n\nconst (\n" + strings.Join(declarations, "\n") + "\n)\n"

	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("format wire constants: %w", err)
	}

	return write("internal/protocol/"+name+".gen.go", formatted, check)
}

func known(doc *openapi3.T, output, pkg string, check bool) error {
	var declarations []string

	stem := strings.TrimSuffix(output, ".gen.go")
	stem = strings.TrimSuffix(stem, "_models")
	constantOutput := stem + "_constants.gen.go"

	for typeName, component := range doc.Components.Schemas {
		value, exists := component.Value.Extensions["x-known-values"]
		if !exists {
			continue
		}

		data, err := json.Marshal(value)
		if err != nil {
			return fmt.Errorf("encode known values: %w", err)
		}

		var values map[string]json.RawMessage

		err = json.Unmarshal(data, &values)
		if err != nil {
			return fmt.Errorf("read known values: %w", err)
		}

		for name, number := range values {
			declarations = append(declarations, fmt.Sprintf("%s %s = %s", name, typeName, number))
		}
	}

	if len(declarations) == 0 {
		return removeStale(constantOutput, check)
	}

	sort.Strings(declarations)

	source := "// Code generated by tools/generate from schema x-known-values; DO NOT EDIT.\n"
	source += "package " + pkg + "\n\nconst (\n" + strings.Join(declarations, "\n") + "\n)\n"

	data, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("format known values: %w", err)
	}

	return write(constantOutput, data, check)
}

func removeStale(name string, check bool) error {
	_, err := os.Stat(name)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}

	if err != nil {
		return fmt.Errorf("inspect stale output: %w", err)
	}

	if check {
		return fmt.Errorf("%w: obsolete generated output %s", errGeneratedDrift, name)
	}

	err = os.Remove(name)
	if err != nil {
		return fmt.Errorf("remove obsolete output: %w", err)
	}

	return nil
}

func model(ctx context.Context, schema, pkg, output string, check bool) error {
	directory, err := os.MkdirTemp("", "roborock-generate-")
	if err != nil {
		return fmt.Errorf("create temporary directory: %w", err)
	}

	defer func() {
		cleanupErr := os.RemoveAll(directory)
		if cleanupErr != nil {
			fmt.Fprintln(os.Stderr, "remove temporary generator directory:", cleanupErr)
		}
	}()

	target := filepath.Join(directory, "models.go")
	configTemplate := "package: %s\ngenerate:\n  models: true\noutput-options:\n  skip-prune: true\noutput: %s\n"

	config := fmt.Sprintf(configTemplate, pkg, filepath.ToSlash(target))
	if pkg == publicPackage {
		config += "import-mapping:\n"
		config += "  ./client-models.openapi.yaml: '-'\n"
	}

	if pkg == "main" {
		config += "import-mapping:\n"
		config += "  ./client-models.openapi.yaml: github.com/portpowered/go-roborock/pkg/roborock\n"
		config += "  ./operation-models.openapi.yaml: github.com/portpowered/go-roborock/pkg/roborock\n"
		config += "  ./a01-models.openapi.yaml: github.com/portpowered/go-roborock/pkg/roborock\n"
	}

	configPath := filepath.Join(directory, "config.yaml")

	err = os.WriteFile(configPath, []byte(config), privateFileMode)
	if err != nil {
		return fmt.Errorf("write generator config: %w", err)
	}

	// LIB-13: a pinned generator receives only local schema/config paths and no shell expansion.
	command := exec.CommandContext(ctx, "go", "run", generator, "-config", configPath, schema) //nolint:gosec // LIB-13.

	result, runErr := command.CombinedOutput()
	if runErr != nil {
		return fmt.Errorf("generate %s: %w: %s", schema, runErr, result)
	}

	data, err := os.ReadFile(target) //nolint:gosec // Read the generator-owned temporary output.
	if err != nil {
		return fmt.Errorf("read generated model: %w", err)
	}

	return write(output, normalizePackageComment(pkg, data), check)
}

func normalizePackageComment(pkg string, data []byte) []byte {
	if pkg != publicPackage && pkg != cliPackage {
		return data
	}

	boilerplate := "// Package " + pkg + " provides primitives to interact with the openapi HTTP API.\n//\n"
	data = bytes.TrimPrefix(data, []byte(boilerplate))
	// Keep the generator marker separate from the package documentation owned by doc.go.
	return bytes.Replace(data, []byte("DO NOT EDIT.\npackage "+pkg), []byte("DO NOT EDIT.\n\npackage "+pkg), 1)
}

func write(name string, data []byte, check bool) error {
	if check {
		current, err := os.ReadFile(name) //nolint:gosec // Read explicit repository generator output paths.
		if err != nil {
			return fmt.Errorf("missing generated output %s: %w", name, err)
		}

		if !bytes.Equal(current, data) {
			return fmt.Errorf("%w: %s", errGeneratedDrift, name)
		}

		return nil
	}

	err := os.MkdirAll(filepath.Dir(name), outputDirectoryMode)
	if err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	err = os.WriteFile(name, data, privateFileMode) //nolint:gosec // Write explicit repository generated output.
	if err != nil {
		return fmt.Errorf("write %s: %w", name, err)
	}

	return nil
}

func collect(doc *openapi3.T, values map[string]string) {
	for path, item := range doc.Paths.Map() {
		for method, operation := range item.Operations() {
			values["RESTPath"+operation.OperationID] = path

			values["RESTMethod"+operation.OperationID] = method

			for _, parameter := range append(item.Parameters, operation.Parameters...) {
				if parameter.Value != nil {
					values["REST"+identifier(parameter.Value.In)+identifier(parameter.Value.Name)] = parameter.Value.Name
				}
			}

			collectForm(operation, values)
		}
	}
}

func collectForm(operation *openapi3.Operation, values map[string]string) {
	if operation.RequestBody == nil || operation.RequestBody.Value == nil {
		return
	}

	for contentType, media := range operation.RequestBody.Value.Content {
		if contentType == "application/x-www-form-urlencoded" && media.Schema != nil && media.Schema.Value != nil {
			for property := range media.Schema.Value.Properties {
				values["RESTForm"+identifier(property)] = property
			}
		}
	}
}

func identifier(value string) string {
	var result strings.Builder

	upper := true

	for _, char := range value {
		if !unicode.IsLetter(char) && !unicode.IsDigit(char) {
			upper = true

			continue
		}

		if upper {
			char = unicode.ToUpper(char)
			upper = false
		}

		result.WriteRune(char)
	}

	if result.Len() == 0 {
		panic(errEmptyIdentifier)
	}

	return result.String()
}

func modelTarget(name string) (string, string) {
	pkg, output := "dependencymodels", "pkg/dependencymodels/"+name+".gen.go"

	if strings.HasSuffix(name, "-models") {
		pkg, output = publicPackage, "pkg/roborock/"+strings.ReplaceAll(name, "-", "_")+".gen.go"
	}

	if name == "maps-models" {
		pkg, output = "mapmodel", "internal/mapmodel/models.gen.go"
	}

	if name == "a01-wire" {
		output = "pkg/dependencymodels/a01_models.gen.go"
	}

	if name == "cli-models" {
		pkg, output = cliPackage, "cmd/go-roborock/input.gen.go"
	}

	return pkg, output
}
