package main

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"testing"
)

func TestPublicPackageCommentNormalization(t *testing.T) {
	t.Parallel()

	for _, pkg := range []string{"roborock", "main"} {
		t.Run(pkg, func(t *testing.T) {
			t.Parallel()

			marker := "// Code generated by pinned-generator; DO NOT EDIT.\npackage " + pkg + "\n"
			expected := "// Code generated by pinned-generator; DO NOT EDIT.\n\npackage " + pkg + "\n"
			boilerplate := "// Package " + pkg + " provides primitives to interact with the openapi HTTP API.\n//\n"

			output := normalizePackageComment(pkg, []byte(boilerplate+marker))
			if !bytes.Equal(output, []byte(expected)) {
				t.Fatalf("public package boilerplate was not removed: %s", output)
			}

			file, err := parser.ParseFile(token.NewFileSet(), "models.gen.go", output, parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}

			if file.Doc != nil || !ast.IsGenerated(file) {
				t.Fatalf("detached generated marker has package documentation or lost provenance: %v", file.Doc)
			}
		})
	}
}

func TestDependencyPackageCommentUnchanged(t *testing.T) {
	t.Parallel()

	dependency := []byte("// Package dependencymodels provides primitives to interact with the openapi HTTP API.\n//\n" +
		"// Code generated by pinned-generator; DO NOT EDIT.\npackage dependencymodels\n")
	if !bytes.Equal(normalizePackageComment("dependencymodels", dependency), dependency) {
		t.Fatal("dependency package documentation changed")
	}
}
