package main

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
)

func generateProtobuf(ctx context.Context, check bool) error {
	args := []string{"run", "./tools/protogen"}
	if check {
		args = append(args, "-check")
	}

	command := exec.CommandContext(ctx, "go", args...)

	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("generate protobuf: %w: %s", err, output)
	}

	return nil
}

func mapAliases(check bool) error {
	const (
		input  = "internal/mapmodel/models.gen.go"
		output = "pkg/roborock/maps_models.gen.go"
	)

	_, err := os.Stat(input)
	if os.IsNotExist(err) {
		return nil
	}

	if err != nil {
		return fmt.Errorf("inspect map models: %w", err)
	}

	var source bytes.Buffer

	source.WriteString("// Code generated by tools/generate from api/maps-models.openapi.yaml; DO NOT EDIT.\n\n")
	source.WriteString("package roborock\n\nimport \"github.com/portpowered/go-roborock/internal/mapmodel\"\n\n")

	for _, path := range []string{input, "internal/mapmodel/models_constants.gen.go"} {
		_, err = os.Stat(path)
		if os.IsNotExist(err) {
			continue
		}

		file, parseErr := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if parseErr != nil {
			return fmt.Errorf("read map definitions: %w", parseErr)
		}

		appendAliases(&source, file)
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format map aliases: %w", err)
	}

	return write(output, formatted, check)
}

func appendAliases(source *bytes.Buffer, file *ast.File) {
	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range group.Specs {
			switch item := spec.(type) {
			case *ast.TypeSpec:
				fmt.Fprintf(source, "// %s describes a decoded Roborock map value.\ntype %s = mapmodel.%s\n\n",
					item.Name, item.Name, item.Name)
			case *ast.ValueSpec:
				if group.Tok != token.CONST {
					continue
				}

				for _, name := range item.Names {
					fmt.Fprintf(source, "// %s is a map protocol value.\nconst %s = mapmodel.%s\n\n", name, name, name)
				}
			}
		}
	}
}
