// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// A01QueryDatapoints A01 ID_QUERY payload. The numeric-key value is a JSON string containing the ordered property ID array, matching pinned Python behavior.
type A01QueryDatapoints struct {
	// PropertyIDs JSON-encoded property ID array, for example "[201,209]". The value is a string, not an array.
	PropertyIDs string `json:"10000"`
}

// A01QueryRequest Encrypted MQTT request payload before frame padding.
type A01QueryRequest struct {
	// Dps A01 ID_QUERY payload. The numeric-key value is a JSON string containing the ordered property ID array, matching pinned Python behavior.
	Dps A01QueryDatapoints `json:"dps"`

	// T Unix timestamp, in seconds.
	T int64 `json:"t"`
}

// A01QueryResponse Appliance MQTT datapoint update. Replies may be split across multiple frames; the session merges selected datapoints until every requested ID arrives.
type A01QueryResponse struct {
	// Dps Known typed appliance datapoints. Additional future properties are tolerated; the public query projects only selected supported properties.
	Dps A01QueryResponse_Dps `json:"dps"`

	// T Optional appliance timestamp, in Unix seconds.
	T *int64 `json:"t,omitempty"`
}

// A01QueryResponse_Dps Known typed appliance datapoints. Additional future properties are tolerated; the public query projects only selected supported properties.
type A01QueryResponse_Dps struct {
	union json.RawMessage
}

// A01SetRequest Sparse MQTT setting publication or bundled washer start payload before encryption.
type A01SetRequest struct {
	// Dps Only supplied settings are published; a Zeo cycle start includes the start signal, mode, and program together.
	Dps A01SetRequest_Dps `json:"dps"`

	// T Unix timestamp, in seconds.
	T int64 `json:"t"`
}

// A01SetRequest_Dps Only supplied settings are published; a Zeo cycle start includes the start signal, mode, and program together.
type A01SetRequest_Dps struct {
	union json.RawMessage
}

// DyadStateWire Numeric-key A01 appliance datapoints.
type DyadStateWire struct {
	// Status Status appliance datapoint.
	Status *int `json:"201,omitempty"`

	// SelfCleanMode SelfCleanMode appliance datapoint.
	SelfCleanMode *int `json:"202,omitempty"`

	// SelfCleanLevel SelfCleanLevel appliance datapoint.
	SelfCleanLevel *int `json:"203,omitempty"`

	// WarmLevel WarmLevel appliance datapoint.
	WarmLevel *int `json:"204,omitempty"`

	// CleanMode CleanMode appliance datapoint.
	CleanMode *int `json:"205,omitempty"`

	// Suction Suction appliance datapoint.
	Suction *int `json:"206,omitempty"`

	// WaterLevel WaterLevel appliance datapoint.
	WaterLevel *int `json:"207,omitempty"`

	// BrushSpeed BrushSpeed appliance datapoint.
	BrushSpeed *int `json:"208,omitempty"`

	// Power Power appliance datapoint.
	Power *int `json:"209,omitempty"`

	// CountdownTime CountdownTime appliance datapoint.
	CountdownTime *int `json:"210,omitempty"`

	// AutoSelfCleanSet AutoSelfCleanSet appliance datapoint.
	AutoSelfCleanSet *int `json:"212,omitempty"`

	// AutoDry AutoDry appliance datapoint.
	AutoDry *int `json:"213,omitempty"`

	// MeshLeft MeshLeft appliance datapoint.
	MeshLeft *int `json:"214,omitempty"`

	// BrushLeft BrushLeft appliance datapoint.
	BrushLeft *int `json:"215,omitempty"`

	// Error Error appliance datapoint.
	Error *int `json:"216,omitempty"`

	// Volume Speaker volume percent, from 0 through 100.
	Volume *int `json:"221,omitempty"`

	// StandLockAutoRun StandLockAutoRun appliance datapoint.
	StandLockAutoRun *int `json:"222,omitempty"`

	// AutoSelfCleanSetMode AutoSelfCleanSetMode appliance datapoint.
	AutoSelfCleanSetMode *int `json:"223,omitempty"`

	// AutoDryMode AutoDryMode appliance datapoint.
	AutoDryMode *int `json:"224,omitempty"`

	// SilentDryDuration SilentDryDuration appliance datapoint.
	SilentDryDuration *int `json:"225,omitempty"`

	// SilentMode SilentMode appliance datapoint.
	SilentMode *int `json:"226,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439.
	SilentModeStartTime *int `json:"227,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439.
	SilentModeEndTime *int `json:"228,omitempty"`

	// RecentRunTime Comma-delimited daily cleaning durations, in minutes.
	RecentRunTime *string `json:"229,omitempty"`

	// TotalRunTime TotalRunTime appliance datapoint.
	TotalRunTime *int `json:"230,omitempty"`

	// DryCountdown DryCountdown appliance datapoint.
	DryCountdown *int `json:"237,omitempty"`
}

// SetDyadSettingsWire Sparse numeric-key A01 settings command.
type SetDyadSettingsWire struct {
	// SelfCleanMode SelfCleanMode appliance datapoint.
	SelfCleanMode *int `json:"202,omitempty"`

	// SelfCleanLevel SelfCleanLevel appliance datapoint.
	SelfCleanLevel *int `json:"203,omitempty"`

	// WarmLevel WarmLevel appliance datapoint.
	WarmLevel *int `json:"204,omitempty"`

	// CleanMode CleanMode appliance datapoint.
	CleanMode *int `json:"205,omitempty"`

	// Suction Suction appliance datapoint.
	Suction *int `json:"206,omitempty"`

	// WaterLevel WaterLevel appliance datapoint.
	WaterLevel *int `json:"207,omitempty"`

	// BrushSpeed BrushSpeed appliance datapoint.
	BrushSpeed *int `json:"208,omitempty"`

	// AutoSelfCleanSet AutoSelfCleanSet appliance datapoint.
	AutoSelfCleanSet *int `json:"212,omitempty"`

	// AutoDry AutoDry appliance datapoint.
	AutoDry *int `json:"213,omitempty"`

	// Volume Speaker volume percent, from 0 through 100.
	Volume *int `json:"221,omitempty"`

	// StandLockAutoRun StandLockAutoRun appliance datapoint.
	StandLockAutoRun *int `json:"222,omitempty"`

	// AutoSelfCleanSetMode AutoSelfCleanSetMode appliance datapoint.
	AutoSelfCleanSetMode *int `json:"223,omitempty"`

	// AutoDryMode AutoDryMode appliance datapoint.
	AutoDryMode *int `json:"224,omitempty"`

	// SilentDryDuration SilentDryDuration appliance datapoint.
	SilentDryDuration *int `json:"225,omitempty"`

	// SilentMode SilentMode appliance datapoint.
	SilentMode *int `json:"226,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439.
	SilentModeStartTime *int `json:"227,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439.
	SilentModeEndTime *int `json:"228,omitempty"`
}

// SetZeoSettingsWire Sparse numeric-key A01 settings command.
type SetZeoSettingsWire struct {
	// ChildLock Appliance boolean datapoint.
	ChildLock *bool `json:"206,omitempty"`

	// DetergentSet Appliance boolean datapoint.
	DetergentSet *bool `json:"211,omitempty"`

	// SoftenerSet Appliance boolean datapoint.
	SoftenerSet *bool `json:"212,omitempty"`

	// DetergentType DetergentType appliance datapoint.
	DetergentType *int `json:"213,omitempty"`

	// SoftenerType SoftenerType appliance datapoint.
	SoftenerType *int `json:"214,omitempty"`

	// Countdown Countdown appliance datapoint.
	Countdown *int `json:"217,omitempty"`

	// Sound Appliance boolean datapoint.
	Sound *bool `json:"223,omitempty"`

	// LightSetting Appliance boolean datapoint.
	LightSetting *bool `json:"229,omitempty"`

	// DetergentVolume DetergentVolume appliance datapoint.
	DetergentVolume *int `json:"230,omitempty"`

	// SoftenerVolume SoftenerVolume appliance datapoint.
	SoftenerVolume *int `json:"231,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439.
	SilentModeStartTime *int `json:"241,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439.
	SilentModeEndTime *int `json:"242,omitempty"`

	// SoftenerExpansionType SoftenerExpansionType appliance datapoint.
	SoftenerExpansionType *int `json:"245,omitempty"`

	// DetergentExpansionType DetergentExpansionType appliance datapoint.
	DetergentExpansionType *int `json:"248,omitempty"`
}

// StartZeoWire Bundled Zeo START command.
type StartZeoWire struct {
	// Start Appliance boolean datapoint.
	Start bool `json:"200"`

	// Mode Mode appliance datapoint.
	Mode int `json:"204"`

	// Program Program appliance datapoint.
	Program int `json:"205"`

	// Temperature Temperature appliance datapoint.
	Temperature *int `json:"207,omitempty"`

	// Rinse Rinse appliance datapoint.
	Rinse *int `json:"208,omitempty"`

	// Spin Spin appliance datapoint.
	Spin *int `json:"209,omitempty"`

	// DryingMode DryingMode appliance datapoint.
	DryingMode *int `json:"210,omitempty"`

	// Soak Soak appliance datapoint.
	Soak *int `json:"233,omitempty"`

	// DryCareMode DryCareMode appliance datapoint.
	DryCareMode *int `json:"244,omitempty"`

	// DryingMethod DryingMethod appliance datapoint.
	DryingMethod *int `json:"256,omitempty"`

	// SteamVolume SteamVolume appliance datapoint.
	SteamVolume *int `json:"257,omitempty"`
}

// ZeoStateWire Numeric-key A01 appliance datapoints.
type ZeoStateWire struct {
	// Start Appliance boolean datapoint.
	Start *bool `json:"200,omitempty"`

	// Pause Appliance boolean datapoint.
	Pause *bool `json:"201,omitempty"`

	// Shutdown Appliance boolean datapoint.
	Shutdown *bool `json:"202,omitempty"`

	// Status Status appliance datapoint.
	Status *int `json:"203,omitempty"`

	// Mode Mode appliance datapoint.
	Mode *int `json:"204,omitempty"`

	// Program Program appliance datapoint.
	Program *int `json:"205,omitempty"`

	// ChildLock Appliance boolean datapoint.
	ChildLock *bool `json:"206,omitempty"`

	// Temperature Temperature appliance datapoint.
	Temperature *int `json:"207,omitempty"`

	// Rinse Rinse appliance datapoint.
	Rinse *int `json:"208,omitempty"`

	// Spin Spin appliance datapoint.
	Spin *int `json:"209,omitempty"`

	// DryingMode DryingMode appliance datapoint.
	DryingMode *int `json:"210,omitempty"`

	// DetergentSet Appliance boolean datapoint.
	DetergentSet *bool `json:"211,omitempty"`

	// SoftenerSet Appliance boolean datapoint.
	SoftenerSet *bool `json:"212,omitempty"`

	// DetergentType DetergentType appliance datapoint.
	DetergentType *int `json:"213,omitempty"`

	// SoftenerType SoftenerType appliance datapoint.
	SoftenerType *int `json:"214,omitempty"`

	// DirtDetectionStatus DirtDetectionStatus appliance datapoint.
	DirtDetectionStatus *int `json:"216,omitempty"`

	// Countdown Countdown appliance datapoint.
	Countdown *int `json:"217,omitempty"`

	// WashingLeft WashingLeft appliance datapoint.
	WashingLeft *int `json:"218,omitempty"`

	// DoorLockState Appliance boolean datapoint.
	DoorLockState *bool `json:"219,omitempty"`

	// Error Error appliance datapoint.
	Error *int `json:"220,omitempty"`

	// CustomParamSave CustomParamSave appliance datapoint.
	CustomParamSave *int `json:"221,omitempty"`

	// CustomParamGet CustomParamGet appliance datapoint.
	CustomParamGet *int `json:"222,omitempty"`

	// Sound Appliance boolean datapoint.
	Sound *bool `json:"223,omitempty"`

	// TimesAfterClean TimesAfterClean appliance datapoint.
	TimesAfterClean *int `json:"224,omitempty"`

	// DefaultSetting Appliance boolean datapoint.
	DefaultSetting *bool `json:"225,omitempty"`

	// DetergentEmpty Appliance boolean datapoint.
	DetergentEmpty *bool `json:"226,omitempty"`

	// SoftenerEmpty Appliance boolean datapoint.
	SoftenerEmpty *bool `json:"227,omitempty"`

	// LightSetting Appliance boolean datapoint.
	LightSetting *bool `json:"229,omitempty"`

	// DetergentVolume DetergentVolume appliance datapoint.
	DetergentVolume *int `json:"230,omitempty"`

	// SoftenerVolume SoftenerVolume appliance datapoint.
	SoftenerVolume *int `json:"231,omitempty"`

	// AppAuthorization AppAuthorization appliance datapoint.
	AppAuthorization *int `json:"232,omitempty"`

	// Soak Soak appliance datapoint.
	Soak *int `json:"233,omitempty"`

	// TotalTime TotalTime appliance datapoint.
	TotalTime *int `json:"234,omitempty"`

	// FeatureBits FeatureBits appliance datapoint.
	FeatureBits *int `json:"237,omitempty"`

	// CustomProgramCleaningTime CustomProgramCleaningTime appliance datapoint.
	CustomProgramCleaningTime *int `json:"239,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439.
	SilentModeStartTime *int `json:"241,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439.
	SilentModeEndTime *int `json:"242,omitempty"`

	// DryCareMode DryCareMode appliance datapoint.
	DryCareMode *int `json:"244,omitempty"`

	// SoftenerExpansionType SoftenerExpansionType appliance datapoint.
	SoftenerExpansionType *int `json:"245,omitempty"`

	// DetergentExpansionType DetergentExpansionType appliance datapoint.
	DetergentExpansionType *int `json:"248,omitempty"`

	// DryingMethod DryingMethod appliance datapoint.
	DryingMethod *int `json:"256,omitempty"`

	// SteamVolume SteamVolume appliance datapoint.
	SteamVolume *int `json:"257,omitempty"`

	// SteamCareTime SteamCareTime appliance datapoint.
	SteamCareTime *int `json:"261,omitempty"`

	// StartDryerError StartDryerError appliance datapoint.
	StartDryerError *int `json:"265,omitempty"`
}

// QueryA01ValuesJSONRequestBody defines body for QueryA01Values for application/json ContentType.
type QueryA01ValuesJSONRequestBody = A01QueryRequest

// SetA01ValuesJSONRequestBody defines body for SetA01Values for application/json ContentType.
type SetA01ValuesJSONRequestBody = A01SetRequest

// AsDyadStateWire returns the union data inside the A01QueryResponse_Dps as a DyadStateWire
func (t A01QueryResponse_Dps) AsDyadStateWire() (DyadStateWire, error) {
	var body DyadStateWire
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDyadStateWire overwrites any union data inside the A01QueryResponse_Dps as the provided DyadStateWire
func (t *A01QueryResponse_Dps) FromDyadStateWire(v DyadStateWire) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDyadStateWire performs a merge with any union data inside the A01QueryResponse_Dps, using the provided DyadStateWire
func (t *A01QueryResponse_Dps) MergeDyadStateWire(v DyadStateWire) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsZeoStateWire returns the union data inside the A01QueryResponse_Dps as a ZeoStateWire
func (t A01QueryResponse_Dps) AsZeoStateWire() (ZeoStateWire, error) {
	var body ZeoStateWire
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromZeoStateWire overwrites any union data inside the A01QueryResponse_Dps as the provided ZeoStateWire
func (t *A01QueryResponse_Dps) FromZeoStateWire(v ZeoStateWire) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeZeoStateWire performs a merge with any union data inside the A01QueryResponse_Dps, using the provided ZeoStateWire
func (t *A01QueryResponse_Dps) MergeZeoStateWire(v ZeoStateWire) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t A01QueryResponse_Dps) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *A01QueryResponse_Dps) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSetDyadSettingsWire returns the union data inside the A01SetRequest_Dps as a SetDyadSettingsWire
func (t A01SetRequest_Dps) AsSetDyadSettingsWire() (SetDyadSettingsWire, error) {
	var body SetDyadSettingsWire
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetDyadSettingsWire overwrites any union data inside the A01SetRequest_Dps as the provided SetDyadSettingsWire
func (t *A01SetRequest_Dps) FromSetDyadSettingsWire(v SetDyadSettingsWire) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetDyadSettingsWire performs a merge with any union data inside the A01SetRequest_Dps, using the provided SetDyadSettingsWire
func (t *A01SetRequest_Dps) MergeSetDyadSettingsWire(v SetDyadSettingsWire) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetZeoSettingsWire returns the union data inside the A01SetRequest_Dps as a SetZeoSettingsWire
func (t A01SetRequest_Dps) AsSetZeoSettingsWire() (SetZeoSettingsWire, error) {
	var body SetZeoSettingsWire
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetZeoSettingsWire overwrites any union data inside the A01SetRequest_Dps as the provided SetZeoSettingsWire
func (t *A01SetRequest_Dps) FromSetZeoSettingsWire(v SetZeoSettingsWire) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetZeoSettingsWire performs a merge with any union data inside the A01SetRequest_Dps, using the provided SetZeoSettingsWire
func (t *A01SetRequest_Dps) MergeSetZeoSettingsWire(v SetZeoSettingsWire) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStartZeoWire returns the union data inside the A01SetRequest_Dps as a StartZeoWire
func (t A01SetRequest_Dps) AsStartZeoWire() (StartZeoWire, error) {
	var body StartZeoWire
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartZeoWire overwrites any union data inside the A01SetRequest_Dps as the provided StartZeoWire
func (t *A01SetRequest_Dps) FromStartZeoWire(v StartZeoWire) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartZeoWire performs a merge with any union data inside the A01SetRequest_Dps, using the provided StartZeoWire
func (t *A01SetRequest_Dps) MergeStartZeoWire(v StartZeoWire) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t A01SetRequest_Dps) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *A01SetRequest_Dps) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
