// Code generated by tools/generate from schema x-known-values; DO NOT EDIT.
package dependencymodels

const (
	VendorCodeAccountMissing     VendorCode = 2008
	VendorCodeAgreementRequired  VendorCode = 3009
	VendorCodeDeletedAccount     VendorCode = 3030
	VendorCodeInvalidAgreement   VendorCode = 3006
	VendorCodeInvalidCode        VendorCode = 2018
	VendorCodeInvalidCredentials VendorCode = 2010
	VendorCodeInvalidEmail       VendorCode = 2003
	VendorCodeMissingParameters  VendorCode = 1001
	VendorCodeSuccess            VendorCode = 200
	VendorCodeTooFrequent        VendorCode = 9002
	VendorCodeWrongRegion        VendorCode = 3039
)
