// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
)

// Defines values for B01Method.
const (
	ServiceGetMapList    B01Method = "service.get_map_list"
	ServiceSetRoomClean  B01Method = "service.set_room_clean"
	ServiceUploadByMapid B01Method = "service.upload_by_mapid"
)

// Defines values for Q10CleanCommandCmd.
const (
	N2 Q10CleanCommandCmd = 2
	N3 Q10CleanCommandCmd = 3
)

// B01Envelope defines model for B01Envelope.
type B01Envelope struct {
	Dps map[string]json.RawMessage `json:"dps"`
}

// B01Method defines model for B01Method.
type B01Method string

// B01RPCRequest defines model for B01RPCRequest.
type B01RPCRequest struct {
	Method B01Method       `json:"method"`
	MsgId  string          `json:"msgId"`
	Params json.RawMessage `json:"params"`
}

// B01RPCResponse defines model for B01RPCResponse.
type B01RPCResponse struct {
	Code  *int             `json:"code,omitempty"`
	Data  *json.RawMessage `json:"data,omitempty"`
	MsgId string           `json:"msgId"`
}

// Q10CleanCommand defines model for Q10CleanCommand.
type Q10CleanCommand struct {
	CleanParamters json.RawMessage    `json:"clean_paramters"`
	Cmd            Q10CleanCommandCmd `json:"cmd"`
}

// Q10CleanCommandCmd defines model for Q10CleanCommand.Cmd.
type Q10CleanCommandCmd int

// Q7RoomCleanRequest defines model for Q7RoomCleanRequest.
type Q7RoomCleanRequest struct {
	CleanType int   `json:"clean_type"`
	CtrlValue int   `json:"ctrl_value"`
	RoomIds   []int `json:"room_ids"`
}
