// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
)

// Defines values for B01Method.
const (
	ServiceGetMapList    B01Method = "service.get_map_list"
	ServiceSetRoomClean  B01Method = "service.set_room_clean"
	ServiceUploadByMapid B01Method = "service.upload_by_mapid"
)

// Defines values for B01Q10RoomCleanCommandCmd.
const (
	B01Q10RoomCleanCommandPropertiesCmd0Value B01Q10RoomCleanCommandCmd = 2
)

// Defines values for B01Q10ZoneCleanCommandCmd.
const (
	B01Q10ZoneCleanCommandPropertiesCmd0Value B01Q10ZoneCleanCommandCmd = 3
)

// Defines values for B01Q7RoomCleanRPCMethod.
const (
	B01Q7RoomCleanRPCPropertiesMethod0Value B01Q7RoomCleanRPCMethod = "service.set_room_clean"
)

// Defines values for Q10CleanCommandCmd.
const (
	N2 Q10CleanCommandCmd = 2
	N3 Q10CleanCommandCmd = 3
)

// Defines values for Q7RoomCleanRequestCleanType.
const (
	Q7RoomCleanRequestPropertiesCleanType0Value Q7RoomCleanRequestCleanType = 1
)

// Defines values for Q7RoomCleanRequestCtrlValue.
const (
	Q7RoomCleanRequestPropertiesCtrlValue0Value Q7RoomCleanRequestCtrlValue = 1
)

// B01Envelope Open carrier for future datapoints; use the named operations for verified payload variants.
type B01Envelope struct {
	Dps map[string]json.RawMessage `json:"dps"`
}

// B01KnownEmptyObject defines model for B01KnownEmptyObject.
type B01KnownEmptyObject = map[string]interface{}

// B01Method defines model for B01Method.
type B01Method string

// B01Q10RoomCleanCommand defines model for B01Q10RoomCleanCommand.
type B01Q10RoomCleanCommand struct {
	// CleanParamters Room IDs from the selected Q10 map, represented as unsigned 16-bit integers; individual firmware acceptance is not established.
	CleanParamters B01Q10RoomIDs             `json:"clean_paramters"`
	Cmd            B01Q10RoomCleanCommandCmd `json:"cmd"`
}

// B01Q10RoomCleanCommandCmd defines model for B01Q10RoomCleanCommand.Cmd.
type B01Q10RoomCleanCommandCmd int

// B01Q10RoomCleanEnvelope defines model for B01Q10RoomCleanEnvelope.
type B01Q10RoomCleanEnvelope struct {
	Dps B01Q10RoomCleanEnvelopeDatapoints `json:"dps"`
}

// B01Q10RoomCleanEnvelopeDatapoints defines model for B01Q10RoomCleanEnvelopeDatapoints.
type B01Q10RoomCleanEnvelopeDatapoints struct {
	N201 B01Q10RoomCleanCommand `json:"201"`
}

// B01Q10RoomIDs Room IDs from the selected Q10 map, represented as unsigned 16-bit integers; individual firmware acceptance is not established.
type B01Q10RoomIDs = []int64

// B01Q10ZoneCleanCommand defines model for B01Q10ZoneCleanCommand.
type B01Q10ZoneCleanCommand struct {
	// CleanParamters Base64 of the 40-byte zone vector: version 1, repeat 1 through 3, one four-vertex polygon, eight signed big-endian 16-bit coordinates in 5 mm units relative to (25500,25500), zero name length, and 19 zero bytes.
	CleanParamters B01Q10ZonePayload         `json:"clean_paramters"`
	Cmd            B01Q10ZoneCleanCommandCmd `json:"cmd"`
}

// B01Q10ZoneCleanCommandCmd defines model for B01Q10ZoneCleanCommand.Cmd.
type B01Q10ZoneCleanCommandCmd int

// B01Q10ZoneCleanEnvelope defines model for B01Q10ZoneCleanEnvelope.
type B01Q10ZoneCleanEnvelope struct {
	Dps B01Q10ZoneCleanEnvelopeDatapoints `json:"dps"`
}

// B01Q10ZoneCleanEnvelopeDatapoints defines model for B01Q10ZoneCleanEnvelopeDatapoints.
type B01Q10ZoneCleanEnvelopeDatapoints struct {
	N201 B01Q10ZoneCleanCommand `json:"201"`
}

// B01Q10ZonePayload Base64 of the 40-byte zone vector: version 1, repeat 1 through 3, one four-vertex polygon, eight signed big-endian 16-bit coordinates in 5 mm units relative to (25500,25500), zero name length, and 19 zero bytes.
type B01Q10ZonePayload = []byte

// B01Q7CommandReply defines model for B01Q7CommandReply.
type B01Q7CommandReply struct {
	Code *int `json:"code,omitempty"`

	// Data Device acknowledgement data has no verified stable shape.
	Data  *json.RawMessage `json:"data,omitempty"`
	MsgId string           `json:"msgId"`
}

// B01Q7RoomCleanEnvelope defines model for B01Q7RoomCleanEnvelope.
type B01Q7RoomCleanEnvelope struct {
	Dps B01Q7RoomCleanEnvelopeDatapoints `json:"dps"`
}

// B01Q7RoomCleanEnvelopeDatapoints defines model for B01Q7RoomCleanEnvelopeDatapoints.
type B01Q7RoomCleanEnvelopeDatapoints struct {
	N10000 B01Q7RoomCleanRPC `json:"10000"`
}

// B01Q7RoomCleanRPC defines model for B01Q7RoomCleanRPC.
type B01Q7RoomCleanRPC struct {
	Method B01Q7RoomCleanRPCMethod `json:"method"`
	MsgId  string                  `json:"msgId"`
	Params Q7RoomCleanRequest      `json:"params"`
}

// B01Q7RoomCleanRPCMethod defines model for B01Q7RoomCleanRPC.Method.
type B01Q7RoomCleanRPCMethod string

// B01RPCRequest Open parameter carrier used by the transport; known method messages constrain parameters.
type B01RPCRequest struct {
	Method B01Method       `json:"method"`
	MsgId  string          `json:"msgId"`
	Params json.RawMessage `json:"params"`
}

// B01RPCResponse defines model for B01RPCResponse.
type B01RPCResponse struct {
	Code  *int             `json:"code,omitempty"`
	Data  *json.RawMessage `json:"data,omitempty"`
	MsgId string           `json:"msgId"`
}

// Q10CleanCommand Transport carrier; room and zone messages constrain the command-specific parameter shape.
type Q10CleanCommand struct {
	CleanParamters json.RawMessage    `json:"clean_paramters"`
	Cmd            Q10CleanCommandCmd `json:"cmd"`
}

// Q10CleanCommandCmd defines model for Q10CleanCommand.Cmd.
type Q10CleanCommandCmd int

// Q7RoomCleanRequest defines model for Q7RoomCleanRequest.
type Q7RoomCleanRequest struct {
	CleanType Q7RoomCleanRequestCleanType `json:"clean_type"`
	CtrlValue Q7RoomCleanRequestCtrlValue `json:"ctrl_value"`

	// RoomIds Room IDs from the selected Q7 map, represented as unsigned 32-bit integers; individual firmware acceptance is not established.
	RoomIds []int64 `json:"room_ids"`
}

// Q7RoomCleanRequestCleanType defines model for Q7RoomCleanRequest.CleanType.
type Q7RoomCleanRequestCleanType int

// Q7RoomCleanRequestCtrlValue defines model for Q7RoomCleanRequest.CtrlValue.
type Q7RoomCleanRequestCtrlValue int
