// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

// Defines values for CameraRPCMethod.
const (
	RPCCameraCheckPassword CameraRPCMethod = "check_homesec_password"
	RPCCameraGetICE        CameraRPCMethod = "get_device_ice"
	RPCCameraGetSDP        CameraRPCMethod = "get_device_sdp"
	RPCCameraGetTURN       CameraRPCMethod = "get_turn_server"
	RPCCameraSendICE       CameraRPCMethod = "send_ice_to_robot"
	RPCCameraSendSDP       CameraRPCMethod = "send_sdp_to_robot"
	RPCCameraStartPreview  CameraRPCMethod = "start_camera_preview"
	RPCCameraStopPreview   CameraRPCMethod = "stop_camera_preview"
)

// Defines values for CameraSDPRetry.
const (
	CameraSDPRetryPending CameraSDPRetry = "retry"
)

// Defines values for CameraSDPType.
const (
	CameraSDPTypeAnswer CameraSDPType = "answer"
	CameraSDPTypeOffer  CameraSDPType = "offer"
)

// CameraAcknowledgement defines model for CameraAcknowledgement.
type CameraAcknowledgement = []string

// CameraCheckPasswordRPCJSONRequestBody defines model for CameraCheckPasswordRPCJSONRequestBody.
type CameraCheckPasswordRPCJSONRequestBody = CameraPasswordParameters

// CameraDeviceICE defines model for CameraDeviceICE.
type CameraDeviceICE struct {
	DevIce *string `json:"dev_ice,omitempty"`
	Ice    *string `json:"ice,omitempty"`
}

// CameraDeviceSDP defines model for CameraDeviceSDP.
type CameraDeviceSDP struct {
	// DevSdp Base64 encoded answer envelope, or the retry token.
	DevSdp *string `json:"dev_sdp,omitempty"`
	Sdp    *string `json:"sdp,omitempty"`
}

// CameraEmptyParameters defines model for CameraEmptyParameters.
type CameraEmptyParameters = struct{}

// CameraGetICERPCJSONRequestBody defines model for CameraGetICERPCJSONRequestBody.
type CameraGetICERPCJSONRequestBody = CameraEmptyParameters

// CameraGetSDPRPCJSONRequestBody defines model for CameraGetSDPRPCJSONRequestBody.
type CameraGetSDPRPCJSONRequestBody = CameraEmptyParameters

// CameraGetTURNRPCJSONRequestBody defines model for CameraGetTURNRPCJSONRequestBody.
type CameraGetTURNRPCJSONRequestBody = CameraEmptyParameters

// CameraICEParameters defines model for CameraICEParameters.
type CameraICEParameters struct {
	Ice string `json:"ice"`
}

// CameraPasswordParameters defines model for CameraPasswordParameters.
type CameraPasswordParameters struct {
	Password string `json:"password"`
}

// CameraPreviewParameters defines model for CameraPreviewParameters.
type CameraPreviewParameters struct {
	Password string `json:"password"`
	Quality  string `json:"quality"`
}

// CameraRPCMethod defines model for CameraRPCMethod.
type CameraRPCMethod string

// CameraSDPEnvelope defines model for CameraSDPEnvelope.
type CameraSDPEnvelope struct {
	Sdp string `json:"sdp"`

	// Type SDP negotiation direction.
	Type CameraSDPType `json:"type"`
}

// CameraSDPParameters defines model for CameraSDPParameters.
type CameraSDPParameters struct {
	AppSdp string `json:"app_sdp"`
}

// CameraSDPRetry Device requests bounded polling while answer is not ready.
type CameraSDPRetry string

// CameraSDPType SDP negotiation direction.
type CameraSDPType string

// CameraSendICERPCJSONRequestBody defines model for CameraSendICERPCJSONRequestBody.
type CameraSendICERPCJSONRequestBody = CameraICEParameters

// CameraSendSDPRPCJSONRequestBody defines model for CameraSendSDPRPCJSONRequestBody.
type CameraSendSDPRPCJSONRequestBody = CameraSDPParameters

// CameraStartPreviewRPCJSONRequestBody defines model for CameraStartPreviewRPCJSONRequestBody.
type CameraStartPreviewRPCJSONRequestBody = CameraPreviewParameters

// CameraStopPreviewRPCJSONRequestBody defines model for CameraStopPreviewRPCJSONRequestBody.
type CameraStopPreviewRPCJSONRequestBody = CameraEmptyParameters

// CameraTURN defines model for CameraTURN.
type CameraTURN struct {
	Credential *string `json:"credential,omitempty"`
	Pwd        *string `json:"pwd,omitempty"`
	Url        *string `json:"url,omitempty"`
	User       *string `json:"user,omitempty"`
	Username   *string `json:"username,omitempty"`
}
