// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
)

// HomeData defines model for HomeData.
type HomeData struct {
	Devices              *[]HomeDevice              `json:"devices"`
	GeoName              *json.RawMessage           `json:"geoName"`
	Id                   int64                      `json:"id"`
	Lat                  *json.RawMessage           `json:"lat"`
	Lon                  *json.RawMessage           `json:"lon"`
	Name                 string                     `json:"name"`
	Products             *[]HomeProduct             `json:"products"`
	ReceivedDevices      *[]HomeDevice              `json:"receivedDevices"`
	Rooms                *[]HomeRoom                `json:"rooms"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// HomeDataResponse defines model for HomeDataResponse.
type HomeDataResponse struct {
	Code                 *int                       `json:"code"`
	Msg                  *string                    `json:"msg"`
	Result               *HomeData                  `json:"result"`
	Success              bool                       `json:"success"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// HomeDevice defines model for HomeDevice.
type HomeDevice struct {
	ActiveTime           *int64                     `json:"activeTime"`
	Attribute            *json.RawMessage           `json:"attribute"`
	Cid                  *string                    `json:"cid"`
	CreateTime           *int64                     `json:"createTime"`
	DeviceStatus         *json.RawMessage           `json:"deviceStatus"`
	Duid                 string                     `json:"duid"`
	Extra                *json.RawMessage           `json:"extra"`
	F                    *bool                      `json:"f"`
	FeatureSet           *string                    `json:"featureSet"`
	Fv                   *string                    `json:"fv"`
	IconUrl              *string                    `json:"iconUrl"`
	Lat                  *json.RawMessage           `json:"lat"`
	LocalKey             string                     `json:"localKey"`
	Lon                  *json.RawMessage           `json:"lon"`
	Name                 string                     `json:"name"`
	NewFeatureSet        *string                    `json:"newFeatureSet"`
	Online               *bool                      `json:"online"`
	ProductId            string                     `json:"productId"`
	Pv                   *string                    `json:"pv"`
	RoomId               *json.RawMessage           `json:"roomId"`
	RuntimeEnv           *json.RawMessage           `json:"runtimeEnv"`
	Setting              *json.RawMessage           `json:"setting"`
	Share                *json.RawMessage           `json:"share"`
	ShareExpiredTime     *int64                     `json:"shareExpiredTime"`
	ShareTime            *json.RawMessage           `json:"shareTime"`
	ShareType            *json.RawMessage           `json:"shareType"`
	SilentOtaSwitch      *bool                      `json:"silentOtaSwitch"`
	Sn                   *string                    `json:"sn"`
	TimeZoneId           *string                    `json:"timeZoneId"`
	TuyaMigrated         *bool                      `json:"tuyaMigrated"`
	TuyaUuid             *json.RawMessage           `json:"tuyaUuid"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// HomeProduct defines model for HomeProduct.
type HomeProduct struct {
	Attribute  *json.RawMessage `json:"attribute"`
	Capability *int64           `json:"capability"`

	// Category Open device category. Known values are robot.vacuum.cleaner, roborock.wetdryvac, roborock.wm, roborock.mower and UNKNOWN; future strings remain valid.
	Category             ProductCategory            `json:"category"`
	Code                 *string                    `json:"code"`
	IconUrl              *string                    `json:"iconUrl"`
	Id                   string                     `json:"id"`
	Model                string                     `json:"model"`
	Name                 string                     `json:"name"`
	Schema               *[]ProductProperty         `json:"schema"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// HomeRoom defines model for HomeRoom.
type HomeRoom struct {
	Id                   int64                      `json:"id"`
	Name                 string                     `json:"name"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ProductCategory Open device category. Known values are robot.vacuum.cleaner, roborock.wetdryvac, roborock.wm, roborock.mower and UNKNOWN; future strings remain valid.
type ProductCategory = string

// ProductProperty defines model for ProductProperty.
type ProductProperty struct {
	Code                 *json.RawMessage           `json:"code"`
	Desc                 *json.RawMessage           `json:"desc"`
	Id                   *json.RawMessage           `json:"id"`
	Mode                 *json.RawMessage           `json:"mode"`
	Name                 *json.RawMessage           `json:"name"`
	ProductProperty      *json.RawMessage           `json:"productProperty"`
	Property             *json.RawMessage           `json:"property"`
	Type                 *json.RawMessage           `json:"type"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// GetHomeDatav1Params defines parameters for GetHomeDatav1.
type GetHomeDatav1Params struct {
	Authorization string `json:"Authorization"`
}

// GetHomeDatav2Params defines parameters for GetHomeDatav2.
type GetHomeDatav2Params struct {
	Authorization string `json:"Authorization"`
}

// GetHomeDatav3Params defines parameters for GetHomeDatav3.
type GetHomeDatav3Params struct {
	Authorization string `json:"Authorization"`
}

// Getter for additional properties for HomeData. Returns the specified
// element and whether it was found
func (a HomeData) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeData
func (a *HomeData) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeData to handle AdditionalProperties
func (a *HomeData) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devices"]; found {
		err = json.Unmarshal(raw, &a.Devices)
		if err != nil {
			return fmt.Errorf("error reading 'devices': %w", err)
		}
		delete(object, "devices")
	}

	if raw, found := object["geoName"]; found {
		err = json.Unmarshal(raw, &a.GeoName)
		if err != nil {
			return fmt.Errorf("error reading 'geoName': %w", err)
		}
		delete(object, "geoName")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["lat"]; found {
		err = json.Unmarshal(raw, &a.Lat)
		if err != nil {
			return fmt.Errorf("error reading 'lat': %w", err)
		}
		delete(object, "lat")
	}

	if raw, found := object["lon"]; found {
		err = json.Unmarshal(raw, &a.Lon)
		if err != nil {
			return fmt.Errorf("error reading 'lon': %w", err)
		}
		delete(object, "lon")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["products"]; found {
		err = json.Unmarshal(raw, &a.Products)
		if err != nil {
			return fmt.Errorf("error reading 'products': %w", err)
		}
		delete(object, "products")
	}

	if raw, found := object["receivedDevices"]; found {
		err = json.Unmarshal(raw, &a.ReceivedDevices)
		if err != nil {
			return fmt.Errorf("error reading 'receivedDevices': %w", err)
		}
		delete(object, "receivedDevices")
	}

	if raw, found := object["rooms"]; found {
		err = json.Unmarshal(raw, &a.Rooms)
		if err != nil {
			return fmt.Errorf("error reading 'rooms': %w", err)
		}
		delete(object, "rooms")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeData to handle AdditionalProperties
func (a HomeData) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Devices != nil {
		object["devices"], err = json.Marshal(a.Devices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devices': %w", err)
		}
	}

	if a.GeoName != nil {
		object["geoName"], err = json.Marshal(a.GeoName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'geoName': %w", err)
		}
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.Lat != nil {
		object["lat"], err = json.Marshal(a.Lat)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lat': %w", err)
		}
	}

	if a.Lon != nil {
		object["lon"], err = json.Marshal(a.Lon)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lon': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Products != nil {
		object["products"], err = json.Marshal(a.Products)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'products': %w", err)
		}
	}

	if a.ReceivedDevices != nil {
		object["receivedDevices"], err = json.Marshal(a.ReceivedDevices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'receivedDevices': %w", err)
		}
	}

	if a.Rooms != nil {
		object["rooms"], err = json.Marshal(a.Rooms)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rooms': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HomeDataResponse. Returns the specified
// element and whether it was found
func (a HomeDataResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeDataResponse
func (a *HomeDataResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeDataResponse to handle AdditionalProperties
func (a *HomeDataResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["success"]; found {
		err = json.Unmarshal(raw, &a.Success)
		if err != nil {
			return fmt.Errorf("error reading 'success': %w", err)
		}
		delete(object, "success")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeDataResponse to handle AdditionalProperties
func (a HomeDataResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Msg != nil {
		object["msg"], err = json.Marshal(a.Msg)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg': %w", err)
		}
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	object["success"], err = json.Marshal(a.Success)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'success': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HomeDevice. Returns the specified
// element and whether it was found
func (a HomeDevice) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeDevice
func (a *HomeDevice) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeDevice to handle AdditionalProperties
func (a *HomeDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["activeTime"]; found {
		err = json.Unmarshal(raw, &a.ActiveTime)
		if err != nil {
			return fmt.Errorf("error reading 'activeTime': %w", err)
		}
		delete(object, "activeTime")
	}

	if raw, found := object["attribute"]; found {
		err = json.Unmarshal(raw, &a.Attribute)
		if err != nil {
			return fmt.Errorf("error reading 'attribute': %w", err)
		}
		delete(object, "attribute")
	}

	if raw, found := object["cid"]; found {
		err = json.Unmarshal(raw, &a.Cid)
		if err != nil {
			return fmt.Errorf("error reading 'cid': %w", err)
		}
		delete(object, "cid")
	}

	if raw, found := object["createTime"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'createTime': %w", err)
		}
		delete(object, "createTime")
	}

	if raw, found := object["deviceStatus"]; found {
		err = json.Unmarshal(raw, &a.DeviceStatus)
		if err != nil {
			return fmt.Errorf("error reading 'deviceStatus': %w", err)
		}
		delete(object, "deviceStatus")
	}

	if raw, found := object["duid"]; found {
		err = json.Unmarshal(raw, &a.Duid)
		if err != nil {
			return fmt.Errorf("error reading 'duid': %w", err)
		}
		delete(object, "duid")
	}

	if raw, found := object["extra"]; found {
		err = json.Unmarshal(raw, &a.Extra)
		if err != nil {
			return fmt.Errorf("error reading 'extra': %w", err)
		}
		delete(object, "extra")
	}

	if raw, found := object["f"]; found {
		err = json.Unmarshal(raw, &a.F)
		if err != nil {
			return fmt.Errorf("error reading 'f': %w", err)
		}
		delete(object, "f")
	}

	if raw, found := object["featureSet"]; found {
		err = json.Unmarshal(raw, &a.FeatureSet)
		if err != nil {
			return fmt.Errorf("error reading 'featureSet': %w", err)
		}
		delete(object, "featureSet")
	}

	if raw, found := object["fv"]; found {
		err = json.Unmarshal(raw, &a.Fv)
		if err != nil {
			return fmt.Errorf("error reading 'fv': %w", err)
		}
		delete(object, "fv")
	}

	if raw, found := object["iconUrl"]; found {
		err = json.Unmarshal(raw, &a.IconUrl)
		if err != nil {
			return fmt.Errorf("error reading 'iconUrl': %w", err)
		}
		delete(object, "iconUrl")
	}

	if raw, found := object["lat"]; found {
		err = json.Unmarshal(raw, &a.Lat)
		if err != nil {
			return fmt.Errorf("error reading 'lat': %w", err)
		}
		delete(object, "lat")
	}

	if raw, found := object["localKey"]; found {
		err = json.Unmarshal(raw, &a.LocalKey)
		if err != nil {
			return fmt.Errorf("error reading 'localKey': %w", err)
		}
		delete(object, "localKey")
	}

	if raw, found := object["lon"]; found {
		err = json.Unmarshal(raw, &a.Lon)
		if err != nil {
			return fmt.Errorf("error reading 'lon': %w", err)
		}
		delete(object, "lon")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["newFeatureSet"]; found {
		err = json.Unmarshal(raw, &a.NewFeatureSet)
		if err != nil {
			return fmt.Errorf("error reading 'newFeatureSet': %w", err)
		}
		delete(object, "newFeatureSet")
	}

	if raw, found := object["online"]; found {
		err = json.Unmarshal(raw, &a.Online)
		if err != nil {
			return fmt.Errorf("error reading 'online': %w", err)
		}
		delete(object, "online")
	}

	if raw, found := object["productId"]; found {
		err = json.Unmarshal(raw, &a.ProductId)
		if err != nil {
			return fmt.Errorf("error reading 'productId': %w", err)
		}
		delete(object, "productId")
	}

	if raw, found := object["pv"]; found {
		err = json.Unmarshal(raw, &a.Pv)
		if err != nil {
			return fmt.Errorf("error reading 'pv': %w", err)
		}
		delete(object, "pv")
	}

	if raw, found := object["roomId"]; found {
		err = json.Unmarshal(raw, &a.RoomId)
		if err != nil {
			return fmt.Errorf("error reading 'roomId': %w", err)
		}
		delete(object, "roomId")
	}

	if raw, found := object["runtimeEnv"]; found {
		err = json.Unmarshal(raw, &a.RuntimeEnv)
		if err != nil {
			return fmt.Errorf("error reading 'runtimeEnv': %w", err)
		}
		delete(object, "runtimeEnv")
	}

	if raw, found := object["setting"]; found {
		err = json.Unmarshal(raw, &a.Setting)
		if err != nil {
			return fmt.Errorf("error reading 'setting': %w", err)
		}
		delete(object, "setting")
	}

	if raw, found := object["share"]; found {
		err = json.Unmarshal(raw, &a.Share)
		if err != nil {
			return fmt.Errorf("error reading 'share': %w", err)
		}
		delete(object, "share")
	}

	if raw, found := object["shareExpiredTime"]; found {
		err = json.Unmarshal(raw, &a.ShareExpiredTime)
		if err != nil {
			return fmt.Errorf("error reading 'shareExpiredTime': %w", err)
		}
		delete(object, "shareExpiredTime")
	}

	if raw, found := object["shareTime"]; found {
		err = json.Unmarshal(raw, &a.ShareTime)
		if err != nil {
			return fmt.Errorf("error reading 'shareTime': %w", err)
		}
		delete(object, "shareTime")
	}

	if raw, found := object["shareType"]; found {
		err = json.Unmarshal(raw, &a.ShareType)
		if err != nil {
			return fmt.Errorf("error reading 'shareType': %w", err)
		}
		delete(object, "shareType")
	}

	if raw, found := object["silentOtaSwitch"]; found {
		err = json.Unmarshal(raw, &a.SilentOtaSwitch)
		if err != nil {
			return fmt.Errorf("error reading 'silentOtaSwitch': %w", err)
		}
		delete(object, "silentOtaSwitch")
	}

	if raw, found := object["sn"]; found {
		err = json.Unmarshal(raw, &a.Sn)
		if err != nil {
			return fmt.Errorf("error reading 'sn': %w", err)
		}
		delete(object, "sn")
	}

	if raw, found := object["timeZoneId"]; found {
		err = json.Unmarshal(raw, &a.TimeZoneId)
		if err != nil {
			return fmt.Errorf("error reading 'timeZoneId': %w", err)
		}
		delete(object, "timeZoneId")
	}

	if raw, found := object["tuyaMigrated"]; found {
		err = json.Unmarshal(raw, &a.TuyaMigrated)
		if err != nil {
			return fmt.Errorf("error reading 'tuyaMigrated': %w", err)
		}
		delete(object, "tuyaMigrated")
	}

	if raw, found := object["tuyaUuid"]; found {
		err = json.Unmarshal(raw, &a.TuyaUuid)
		if err != nil {
			return fmt.Errorf("error reading 'tuyaUuid': %w", err)
		}
		delete(object, "tuyaUuid")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeDevice to handle AdditionalProperties
func (a HomeDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ActiveTime != nil {
		object["activeTime"], err = json.Marshal(a.ActiveTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'activeTime': %w", err)
		}
	}

	if a.Attribute != nil {
		object["attribute"], err = json.Marshal(a.Attribute)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attribute': %w", err)
		}
	}

	if a.Cid != nil {
		object["cid"], err = json.Marshal(a.Cid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cid': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["createTime"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'createTime': %w", err)
		}
	}

	if a.DeviceStatus != nil {
		object["deviceStatus"], err = json.Marshal(a.DeviceStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceStatus': %w", err)
		}
	}

	object["duid"], err = json.Marshal(a.Duid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'duid': %w", err)
	}

	if a.Extra != nil {
		object["extra"], err = json.Marshal(a.Extra)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'extra': %w", err)
		}
	}

	if a.F != nil {
		object["f"], err = json.Marshal(a.F)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'f': %w", err)
		}
	}

	if a.FeatureSet != nil {
		object["featureSet"], err = json.Marshal(a.FeatureSet)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'featureSet': %w", err)
		}
	}

	if a.Fv != nil {
		object["fv"], err = json.Marshal(a.Fv)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fv': %w", err)
		}
	}

	if a.IconUrl != nil {
		object["iconUrl"], err = json.Marshal(a.IconUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'iconUrl': %w", err)
		}
	}

	if a.Lat != nil {
		object["lat"], err = json.Marshal(a.Lat)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lat': %w", err)
		}
	}

	object["localKey"], err = json.Marshal(a.LocalKey)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'localKey': %w", err)
	}

	if a.Lon != nil {
		object["lon"], err = json.Marshal(a.Lon)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lon': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.NewFeatureSet != nil {
		object["newFeatureSet"], err = json.Marshal(a.NewFeatureSet)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'newFeatureSet': %w", err)
		}
	}

	if a.Online != nil {
		object["online"], err = json.Marshal(a.Online)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'online': %w", err)
		}
	}

	object["productId"], err = json.Marshal(a.ProductId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'productId': %w", err)
	}

	if a.Pv != nil {
		object["pv"], err = json.Marshal(a.Pv)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pv': %w", err)
		}
	}

	if a.RoomId != nil {
		object["roomId"], err = json.Marshal(a.RoomId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'roomId': %w", err)
		}
	}

	if a.RuntimeEnv != nil {
		object["runtimeEnv"], err = json.Marshal(a.RuntimeEnv)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'runtimeEnv': %w", err)
		}
	}

	if a.Setting != nil {
		object["setting"], err = json.Marshal(a.Setting)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'setting': %w", err)
		}
	}

	if a.Share != nil {
		object["share"], err = json.Marshal(a.Share)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'share': %w", err)
		}
	}

	if a.ShareExpiredTime != nil {
		object["shareExpiredTime"], err = json.Marshal(a.ShareExpiredTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shareExpiredTime': %w", err)
		}
	}

	if a.ShareTime != nil {
		object["shareTime"], err = json.Marshal(a.ShareTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shareTime': %w", err)
		}
	}

	if a.ShareType != nil {
		object["shareType"], err = json.Marshal(a.ShareType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shareType': %w", err)
		}
	}

	if a.SilentOtaSwitch != nil {
		object["silentOtaSwitch"], err = json.Marshal(a.SilentOtaSwitch)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'silentOtaSwitch': %w", err)
		}
	}

	if a.Sn != nil {
		object["sn"], err = json.Marshal(a.Sn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sn': %w", err)
		}
	}

	if a.TimeZoneId != nil {
		object["timeZoneId"], err = json.Marshal(a.TimeZoneId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timeZoneId': %w", err)
		}
	}

	if a.TuyaMigrated != nil {
		object["tuyaMigrated"], err = json.Marshal(a.TuyaMigrated)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tuyaMigrated': %w", err)
		}
	}

	if a.TuyaUuid != nil {
		object["tuyaUuid"], err = json.Marshal(a.TuyaUuid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tuyaUuid': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HomeProduct. Returns the specified
// element and whether it was found
func (a HomeProduct) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeProduct
func (a *HomeProduct) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeProduct to handle AdditionalProperties
func (a *HomeProduct) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attribute"]; found {
		err = json.Unmarshal(raw, &a.Attribute)
		if err != nil {
			return fmt.Errorf("error reading 'attribute': %w", err)
		}
		delete(object, "attribute")
	}

	if raw, found := object["capability"]; found {
		err = json.Unmarshal(raw, &a.Capability)
		if err != nil {
			return fmt.Errorf("error reading 'capability': %w", err)
		}
		delete(object, "capability")
	}

	if raw, found := object["category"]; found {
		err = json.Unmarshal(raw, &a.Category)
		if err != nil {
			return fmt.Errorf("error reading 'category': %w", err)
		}
		delete(object, "category")
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["iconUrl"]; found {
		err = json.Unmarshal(raw, &a.IconUrl)
		if err != nil {
			return fmt.Errorf("error reading 'iconUrl': %w", err)
		}
		delete(object, "iconUrl")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["schema"]; found {
		err = json.Unmarshal(raw, &a.Schema)
		if err != nil {
			return fmt.Errorf("error reading 'schema': %w", err)
		}
		delete(object, "schema")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeProduct to handle AdditionalProperties
func (a HomeProduct) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Attribute != nil {
		object["attribute"], err = json.Marshal(a.Attribute)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attribute': %w", err)
		}
	}

	if a.Capability != nil {
		object["capability"], err = json.Marshal(a.Capability)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'capability': %w", err)
		}
	}

	object["category"], err = json.Marshal(a.Category)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'category': %w", err)
	}

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.IconUrl != nil {
		object["iconUrl"], err = json.Marshal(a.IconUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'iconUrl': %w", err)
		}
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["model"], err = json.Marshal(a.Model)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'model': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Schema != nil {
		object["schema"], err = json.Marshal(a.Schema)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'schema': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HomeRoom. Returns the specified
// element and whether it was found
func (a HomeRoom) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HomeRoom
func (a *HomeRoom) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HomeRoom to handle AdditionalProperties
func (a *HomeRoom) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HomeRoom to handle AdditionalProperties
func (a HomeRoom) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ProductProperty. Returns the specified
// element and whether it was found
func (a ProductProperty) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProductProperty
func (a *ProductProperty) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProductProperty to handle AdditionalProperties
func (a *ProductProperty) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["desc"]; found {
		err = json.Unmarshal(raw, &a.Desc)
		if err != nil {
			return fmt.Errorf("error reading 'desc': %w", err)
		}
		delete(object, "desc")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &a.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
		delete(object, "mode")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["productProperty"]; found {
		err = json.Unmarshal(raw, &a.ProductProperty)
		if err != nil {
			return fmt.Errorf("error reading 'productProperty': %w", err)
		}
		delete(object, "productProperty")
	}

	if raw, found := object["property"]; found {
		err = json.Unmarshal(raw, &a.Property)
		if err != nil {
			return fmt.Errorf("error reading 'property': %w", err)
		}
		delete(object, "property")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProductProperty to handle AdditionalProperties
func (a ProductProperty) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Desc != nil {
		object["desc"], err = json.Marshal(a.Desc)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'desc': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Mode != nil {
		object["mode"], err = json.Marshal(a.Mode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mode': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.ProductProperty != nil {
		object["productProperty"], err = json.Marshal(a.ProductProperty)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'productProperty': %w", err)
		}
	}

	if a.Property != nil {
		object["property"], err = json.Marshal(a.Property)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'property': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
