// Code generated by tools/generate from schema x-known-values; DO NOT EDIT.
package dependencymodels

const (
	HomeDeviceShareTypeUnlimitedTime HomeDeviceShareType = "UNLIMITED_TIME"
	ProductCategoryMower             ProductCategory     = "roborock.mower"
	ProductCategoryUnknown           ProductCategory     = "UNKNOWN"
	ProductCategoryVacuum            ProductCategory     = "robot.vacuum.cleaner"
	ProductCategoryWashingMachine    ProductCategory     = "roborock.wm"
	ProductCategoryWetDryVacuum      ProductCategory     = "roborock.wetdryvac"
	ProductPropertyModeReadOnly      ProductPropertyMode = "ro"
	ProductPropertyModeReadWrite     ProductPropertyMode = "rw"
	ProductPropertyTypeBoolean       ProductPropertyType = "BOOL"
	ProductPropertyTypeEnum          ProductPropertyType = "ENUM"
	ProductPropertyTypeRaw           ProductPropertyType = "RAW"
	ProductPropertyTypeString        ProductPropertyType = "STRING"
	ProductPropertyTypeValue         ProductPropertyType = "VALUE"
)
