// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// MapBinaryPayload Inflated V1 RRMap, inflated Q7 RobotMap protobuf, or Q10 custom LZ4 map/trace packet.
type MapBinaryPayload = openapi_types.File
