// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for MapsQ10ListRequestOp.
const (
	List MapsQ10ListRequestOp = "list"
)

// Defines values for MapsQ10ListSuccessOp.
const (
	MapsQ10ListSuccessOpList MapsQ10ListSuccessOp = "list"
)

// Defines values for MapsQ10ListSuccessResult.
const (
	MapsQ10ListSuccessResultAccepted MapsQ10ListSuccessResult = 1
)

// Defines values for MapsQ7ListRPCMethod.
const (
	MapsQ7ListRPCPropertiesMethod0Value MapsQ7ListRPCMethod = "service.get_map_list"
)

// Defines values for MapsQ7UploadRPCMethod.
const (
	MapsQ7UploadRPCPropertiesMethod0Value MapsQ7UploadRPCMethod = "service.upload_by_mapid"
)

// MapsBinaryPayload Decoded protocol-301 payload, before family-specific map decoding.
type MapsBinaryPayload = []byte

// MapsKnownEmptyObject defines model for MapsKnownEmptyObject.
type MapsKnownEmptyObject = map[string]interface{}

// MapsQ10ListCommonReply defines model for MapsQ10ListCommonReply.
type MapsQ10ListCommonReply struct {
	N61 MapsQ10ListSuccess `json:"61"`
}

// MapsQ10ListCommonRequest defines model for MapsQ10ListCommonRequest.
type MapsQ10ListCommonRequest struct {
	N61 MapsQ10ListRequest `json:"61"`
}

// MapsQ10ListEntry defines model for MapsQ10ListEntry.
type MapsQ10ListEntry struct {
	Id        string  `json:"id"`
	Name      *string `json:"name,omitempty"`
	Timestamp *int64  `json:"timestamp,omitempty"`
}

// MapsQ10ListEnvelope defines model for MapsQ10ListEnvelope.
type MapsQ10ListEnvelope struct {
	Dps MapsQ10ListEnvelopeDatapoints `json:"dps"`
}

// MapsQ10ListEnvelopeDatapoints defines model for MapsQ10ListEnvelopeDatapoints.
type MapsQ10ListEnvelopeDatapoints struct {
	N101 MapsQ10ListCommonRequest `json:"101"`
}

// MapsQ10ListReply Successful map-list update nested inside DP101 or carried directly in DP61; it has no request identifier.
type MapsQ10ListReply = json.RawMessage

// MapsQ10ListReplyEnvelope defines model for MapsQ10ListReplyEnvelope.
type MapsQ10ListReplyEnvelope struct {
	Dps MapsQ10ListReplyEnvelopeDatapoints `json:"dps"`
}

// MapsQ10ListReplyEnvelopeDatapoints defines model for MapsQ10ListReplyEnvelopeDatapoints.
type MapsQ10ListReplyEnvelopeDatapoints struct {
	N61 MapsQ10ListSuccess `json:"61"`
}

// MapsQ10ListRequest defines model for MapsQ10ListRequest.
type MapsQ10ListRequest struct {
	Op MapsQ10ListRequestOp `json:"op"`
}

// MapsQ10ListRequestOp defines model for MapsQ10ListRequest.Op.
type MapsQ10ListRequestOp string

// MapsQ10ListResult defines model for MapsQ10ListResult.
type MapsQ10ListResult struct {
	Data   *[]MapsQ10ListEntry `json:"data,omitempty"`
	Op     *string             `json:"op,omitempty"`
	Result *int                `json:"result,omitempty"`
}

// MapsQ10ListSuccess defines model for MapsQ10ListSuccess.
type MapsQ10ListSuccess struct {
	Data   *[]MapsQ10ListEntry      `json:"data,omitempty"`
	Op     MapsQ10ListSuccessOp     `json:"op"`
	Result MapsQ10ListSuccessResult `json:"result"`
}

// MapsQ10ListSuccessOp defines model for MapsQ10ListSuccess.Op.
type MapsQ10ListSuccessOp string

// MapsQ10ListSuccessResult defines model for MapsQ10ListSuccess.Result.
type MapsQ10ListSuccessResult int

// MapsQ10NestedListReplyEnvelope defines model for MapsQ10NestedListReplyEnvelope.
type MapsQ10NestedListReplyEnvelope struct {
	Dps MapsQ10NestedListReplyEnvelopeDatapoints `json:"dps"`
}

// MapsQ10NestedListReplyEnvelopeDatapoints defines model for MapsQ10NestedListReplyEnvelopeDatapoints.
type MapsQ10NestedListReplyEnvelopeDatapoints struct {
	N101 MapsQ10ListCommonReply `json:"101"`
}

// MapsQ10ReadEnvelope defines model for MapsQ10ReadEnvelope.
type MapsQ10ReadEnvelope struct {
	Dps MapsQ10ReadEnvelopeDatapoints `json:"dps"`
}

// MapsQ10ReadEnvelopeDatapoints defines model for MapsQ10ReadEnvelopeDatapoints.
type MapsQ10ReadEnvelopeDatapoints struct {
	N102 MapsKnownEmptyObject `json:"102"`
}

// MapsQ7ListEntry defines model for MapsQ7ListEntry.
type MapsQ7ListEntry struct {
	Cur *bool  `json:"cur,omitempty"`
	Id  *int64 `json:"id,omitempty"`
}

// MapsQ7ListEnvelope defines model for MapsQ7ListEnvelope.
type MapsQ7ListEnvelope struct {
	Dps MapsQ7ListEnvelopeDatapoints `json:"dps"`
}

// MapsQ7ListEnvelopeDatapoints defines model for MapsQ7ListEnvelopeDatapoints.
type MapsQ7ListEnvelopeDatapoints struct {
	N10000 MapsQ7ListRPC `json:"10000"`
}

// MapsQ7ListRPC defines model for MapsQ7ListRPC.
type MapsQ7ListRPC struct {
	Method MapsQ7ListRPCMethod `json:"method"`
	MsgId  string              `json:"msgId"`
	Params MapsQ7ListRequest   `json:"params"`
}

// MapsQ7ListRPCMethod defines model for MapsQ7ListRPC.Method.
type MapsQ7ListRPCMethod string

// MapsQ7ListReply defines model for MapsQ7ListReply.
type MapsQ7ListReply struct {
	Code  *int              `json:"code,omitempty"`
	Data  *MapsQ7ListResult `json:"data,omitempty"`
	MsgId string            `json:"msgId"`
}

// MapsQ7ListRequest defines model for MapsQ7ListRequest.
type MapsQ7ListRequest = map[string]interface{}

// MapsQ7ListResult defines model for MapsQ7ListResult.
type MapsQ7ListResult struct {
	MapList *[]MapsQ7ListEntry `json:"map_list,omitempty"`
}

// MapsQ7UploadEnvelope defines model for MapsQ7UploadEnvelope.
type MapsQ7UploadEnvelope struct {
	Dps MapsQ7UploadEnvelopeDatapoints `json:"dps"`
}

// MapsQ7UploadEnvelopeDatapoints defines model for MapsQ7UploadEnvelopeDatapoints.
type MapsQ7UploadEnvelopeDatapoints struct {
	N10000 MapsQ7UploadRPC `json:"10000"`
}

// MapsQ7UploadRPC defines model for MapsQ7UploadRPC.
type MapsQ7UploadRPC struct {
	Method MapsQ7UploadRPCMethod `json:"method"`
	MsgId  string                `json:"msgId"`
	Params MapsQ7UploadRequest   `json:"params"`
}

// MapsQ7UploadRPCMethod defines model for MapsQ7UploadRPC.Method.
type MapsQ7UploadRPCMethod string

// MapsQ7UploadRequest defines model for MapsQ7UploadRequest.
type MapsQ7UploadRequest struct {
	MapId int64 `json:"map_id"`
}

// MapsV1Backup defines model for MapsV1Backup.
type MapsV1Backup struct {
	AddTime *json.RawMessage `json:"add_time,omitempty"`
	MapFlag *json.RawMessage `json:"mapFlag,omitempty"`
}

// MapsV1Entry defines model for MapsV1Entry.
type MapsV1Entry struct {
	AddTime *json.RawMessage `json:"add_time,omitempty"`
	BakMaps *[]MapsV1Backup  `json:"bak_maps,omitempty"`
	Length  *json.RawMessage `json:"length,omitempty"`
	MapFlag int64            `json:"mapFlag"`
	Name    string           `json:"name"`
	Rooms   *[]MapsV1Room    `json:"rooms,omitempty"`
}

// MapsV1List defines model for MapsV1List.
type MapsV1List struct {
	MapInfo       *[]MapsV1Entry `json:"map_info,omitempty"`
	MaxBakMap     *int           `json:"max_bak_map,omitempty"`
	MaxMultiMap   *int           `json:"max_multi_map,omitempty"`
	MultiMapCount *int           `json:"multi_map_count,omitempty"`
}

// MapsV1ListResult defines model for MapsV1ListResult.
type MapsV1ListResult = []MapsV1List

// MapsV1LoadRequest defines model for MapsV1LoadRequest.
type MapsV1LoadRequest = []int64

// MapsV1Room defines model for MapsV1Room.
type MapsV1Room struct {
	Id        *int    `json:"id,omitempty"`
	IotName   *string `json:"iot_name,omitempty"`
	IotNameId *string `json:"iot_name_id,omitempty"`
	Tag       *int    `json:"tag,omitempty"`
}

// MapsV1RoomMappingPair Segment ID, then cloud room ID. Newer firmware appends a room type; extra values are ignored.
type MapsV1RoomMappingPair = []MapsV1RoomMappingValue

// MapsV1RoomMappingValue defines model for MapsV1RoomMappingValue.
type MapsV1RoomMappingValue = json.RawMessage

// MapsV1RoomMappings defines model for MapsV1RoomMappings.
type MapsV1RoomMappings = []MapsV1RoomMappingPair

// MapsV1RoomsResult A list of pairs or a single pair. A null result means the map has no rooms.
type MapsV1RoomsResult struct {
	union json.RawMessage
}

// AsMapsV1RoomMappingPair returns the union data inside the MapsV1RoomsResult as a MapsV1RoomMappingPair
func (t MapsV1RoomsResult) AsMapsV1RoomMappingPair() (MapsV1RoomMappingPair, error) {
	var body MapsV1RoomMappingPair
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMapsV1RoomMappingPair overwrites any union data inside the MapsV1RoomsResult as the provided MapsV1RoomMappingPair
func (t *MapsV1RoomsResult) FromMapsV1RoomMappingPair(v MapsV1RoomMappingPair) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMapsV1RoomMappingPair performs a merge with any union data inside the MapsV1RoomsResult, using the provided MapsV1RoomMappingPair
func (t *MapsV1RoomsResult) MergeMapsV1RoomMappingPair(v MapsV1RoomMappingPair) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMapsV1RoomMappings returns the union data inside the MapsV1RoomsResult as a MapsV1RoomMappings
func (t MapsV1RoomsResult) AsMapsV1RoomMappings() (MapsV1RoomMappings, error) {
	var body MapsV1RoomMappings
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMapsV1RoomMappings overwrites any union data inside the MapsV1RoomsResult as the provided MapsV1RoomMappings
func (t *MapsV1RoomsResult) FromMapsV1RoomMappings(v MapsV1RoomMappings) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMapsV1RoomMappings performs a merge with any union data inside the MapsV1RoomsResult, using the provided MapsV1RoomMappings
func (t *MapsV1RoomsResult) MergeMapsV1RoomMappings(v MapsV1RoomMappings) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MapsV1RoomsResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MapsV1RoomsResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
