// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for MapsQ10ListRequestOp.
const (
	List MapsQ10ListRequestOp = "list"
)

// MapsBinaryPayload Decoded protocol-301 payload, before family-specific map decoding.
type MapsBinaryPayload = []byte

// MapsQ10ListEntry defines model for MapsQ10ListEntry.
type MapsQ10ListEntry struct {
	Id        string  `json:"id"`
	Name      *string `json:"name,omitempty"`
	Timestamp *int64  `json:"timestamp,omitempty"`
}

// MapsQ10ListRequest defines model for MapsQ10ListRequest.
type MapsQ10ListRequest struct {
	Op MapsQ10ListRequestOp `json:"op"`
}

// MapsQ10ListRequestOp defines model for MapsQ10ListRequest.Op.
type MapsQ10ListRequestOp string

// MapsQ10ListResult defines model for MapsQ10ListResult.
type MapsQ10ListResult struct {
	Data   *[]MapsQ10ListEntry `json:"data,omitempty"`
	Op     *string             `json:"op,omitempty"`
	Result *int                `json:"result,omitempty"`
}

// MapsQ7ListEntry defines model for MapsQ7ListEntry.
type MapsQ7ListEntry struct {
	Cur *bool  `json:"cur,omitempty"`
	Id  *int64 `json:"id,omitempty"`
}

// MapsQ7ListRequest defines model for MapsQ7ListRequest.
type MapsQ7ListRequest = map[string]interface{}

// MapsQ7ListResult defines model for MapsQ7ListResult.
type MapsQ7ListResult struct {
	MapList *[]MapsQ7ListEntry `json:"map_list,omitempty"`
}

// MapsQ7UploadRequest defines model for MapsQ7UploadRequest.
type MapsQ7UploadRequest struct {
	MapId int64 `json:"map_id"`
}

// MapsV1Backup defines model for MapsV1Backup.
type MapsV1Backup struct {
	AddTime *json.RawMessage `json:"add_time,omitempty"`
	Mapflag *json.RawMessage `json:"mapflag,omitempty"`
}

// MapsV1Entry defines model for MapsV1Entry.
type MapsV1Entry struct {
	AddTime *json.RawMessage `json:"add_time,omitempty"`
	BakMaps *[]MapsV1Backup  `json:"bak_maps,omitempty"`
	Length  *json.RawMessage `json:"length,omitempty"`
	MapFlag int64            `json:"map_flag"`
	Name    string           `json:"name"`
	Rooms   *[]MapsV1Room    `json:"rooms,omitempty"`
}

// MapsV1List defines model for MapsV1List.
type MapsV1List struct {
	MapInfo       *[]MapsV1Entry `json:"map_info,omitempty"`
	MaxBakMap     *int           `json:"max_bak_map,omitempty"`
	MaxMultiMap   *int           `json:"max_multi_map,omitempty"`
	MultiMapCount *int           `json:"multi_map_count,omitempty"`
}

// MapsV1ListResult defines model for MapsV1ListResult.
type MapsV1ListResult = []MapsV1List

// MapsV1LoadRequest defines model for MapsV1LoadRequest.
type MapsV1LoadRequest = []int64

// MapsV1Room defines model for MapsV1Room.
type MapsV1Room struct {
	Id        *int    `json:"id,omitempty"`
	IotName   *string `json:"iot_name,omitempty"`
	IotNameId *string `json:"iot_name_id,omitempty"`
	Tag       *int    `json:"tag,omitempty"`
}

// MapsV1RoomMappingPair defines model for MapsV1RoomMappingPair.
type MapsV1RoomMappingPair = []MapsV1RoomMappingValue

// MapsV1RoomMappingValue defines model for MapsV1RoomMappingValue.
type MapsV1RoomMappingValue = json.RawMessage

// MapsV1RoomMappings defines model for MapsV1RoomMappings.
type MapsV1RoomMappings = []MapsV1RoomMappingPair

// MapsV1RoomsResult defines model for MapsV1RoomsResult.
type MapsV1RoomsResult struct {
	union json.RawMessage
}

// AsMapsV1RoomMappingPair returns the union data inside the MapsV1RoomsResult as a MapsV1RoomMappingPair
func (t MapsV1RoomsResult) AsMapsV1RoomMappingPair() (MapsV1RoomMappingPair, error) {
	var body MapsV1RoomMappingPair
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMapsV1RoomMappingPair overwrites any union data inside the MapsV1RoomsResult as the provided MapsV1RoomMappingPair
func (t *MapsV1RoomsResult) FromMapsV1RoomMappingPair(v MapsV1RoomMappingPair) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMapsV1RoomMappingPair performs a merge with any union data inside the MapsV1RoomsResult, using the provided MapsV1RoomMappingPair
func (t *MapsV1RoomsResult) MergeMapsV1RoomMappingPair(v MapsV1RoomMappingPair) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMapsV1RoomMappings returns the union data inside the MapsV1RoomsResult as a MapsV1RoomMappings
func (t MapsV1RoomsResult) AsMapsV1RoomMappings() (MapsV1RoomMappings, error) {
	var body MapsV1RoomMappings
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMapsV1RoomMappings overwrites any union data inside the MapsV1RoomsResult as the provided MapsV1RoomMappings
func (t *MapsV1RoomsResult) FromMapsV1RoomMappings(v MapsV1RoomMappings) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMapsV1RoomMappings performs a merge with any union data inside the MapsV1RoomsResult, using the provided MapsV1RoomMappings
func (t *MapsV1RoomsResult) MergeMapsV1RoomMappings(v MapsV1RoomMappings) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MapsV1RoomsResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MapsV1RoomsResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
