// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
)

// MQTTEnvelope defines model for MQTTEnvelope.
type MQTTEnvelope struct {
	Dps map[string]json.RawMessage `json:"dps"`

	// T Unix timestamp in seconds.
	T int64 `json:"t"`
}

// MQTTRPCError defines model for MQTTRPCError.
type MQTTRPCError struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// MQTTRPCRequest defines model for MQTTRPCRequest.
type MQTTRPCRequest struct {
	Id       int64           `json:"id"`
	Method   string          `json:"method"`
	Params   json.RawMessage `json:"params"`
	Security MQTTRPCSecurity `json:"security"`
}

// MQTTRPCResponse defines model for MQTTRPCResponse.
type MQTTRPCResponse struct {
	Error  *MQTTRPCError    `json:"error,omitempty"`
	Id     int64            `json:"id"`
	Result *json.RawMessage `json:"result,omitempty"`
}

// MQTTRPCSecurity defines model for MQTTRPCSecurity.
type MQTTRPCSecurity struct {
	// Endpoint Base64 encoding of bytes 8 through 13 of the account-key MD5.
	Endpoint string `json:"endpoint"`

	// Nonce Fresh session AES key for secured device blob responses, encoded as lowercase hex.
	Nonce string `json:"nonce"`
}
