// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ChargeStatus.
const (
	ChargeStatusChargeWaiting ChargeStatus = 0
	ChargeStatusCharging      ChargeStatus = 1
	ChargeStatusUnknown       ChargeStatus = -1
)

// Defines values for CleanFinishReason.
const (
	CleanFinishReasonAreaUnreachable      CleanFinishReason = 61
	CleanFinishReasonAreaUnreachable2     CleanFinishReason = 62
	CleanFinishReasonBackToWashFailure    CleanFinishReason = 68
	CleanFinishReasonBreakpoint           CleanFinishReason = 32
	CleanFinishReasonBreakpoint2          CleanFinishReason = 33
	CleanFinishReasonBreakpoint4          CleanFinishReason = 102
	CleanFinishReasonCleanupInterrupted   CleanFinishReason = 24
	CleanFinishReasonCleanupInterrupted10 CleanFinishReason = 109
	CleanFinishReasonCleanupInterrupted11 CleanFinishReason = 110
	CleanFinishReasonCleanupInterrupted2  CleanFinishReason = 34
	CleanFinishReasonCleanupInterrupted3  CleanFinishReason = 64
	CleanFinishReasonCleanupInterrupted4  CleanFinishReason = 51
	CleanFinishReasonCleanupInterrupted5  CleanFinishReason = 101
	CleanFinishReasonCleanupInterrupted6  CleanFinishReason = 104
	CleanFinishReasonCleanupInterrupted7  CleanFinishReason = 105
	CleanFinishReasonCleanupInterrupted8  CleanFinishReason = 106
	CleanFinishReasonCleanupInterrupted9  CleanFinishReason = 107
	CleanFinishReasonFinishedCleaning     CleanFinishReason = 52
	CleanFinishReasonFinishedCleaning2    CleanFinishReason = 54
	CleanFinishReasonFinishedCleaning3    CleanFinishReason = 55
	CleanFinishReasonFinishedCleaning4    CleanFinishReason = 56
	CleanFinishReasonFinishedClenaing5    CleanFinishReason = 57
	CleanFinishReasonLocateFail           CleanFinishReason = 45
	CleanFinishReasonLocateFail2          CleanFinishReason = 65
	CleanFinishReasonManualInterrupt      CleanFinishReason = 21
	CleanFinishReasonManualInterrupt10    CleanFinishReason = 60
	CleanFinishReasonManualInterrupt11    CleanFinishReason = 103
	CleanFinishReasonManualInterrupt12    CleanFinishReason = 29
	CleanFinishReasonManualInterrupt3     CleanFinishReason = 35
	CleanFinishReasonManualInterrupt4     CleanFinishReason = 36
	CleanFinishReasonManualInterrupt5     CleanFinishReason = 37
	CleanFinishReasonManualInterrupt6     CleanFinishReason = 43
	CleanFinishReasonManualInterrupt7     CleanFinishReason = 48
	CleanFinishReasonManualInterrupt8     CleanFinishReason = 49
	CleanFinishReasonManualInterrupt9     CleanFinishReason = 50
	CleanFinishReasonPatrolFail           CleanFinishReason = 115
	CleanFinishReasonPatrolSuccess        CleanFinishReason = 114
	CleanFinishReasonPetPatrolFail        CleanFinishReason = 117
	CleanFinishReasonPetPatrolSuccess     CleanFinishReason = 116
	CleanFinishReasonWashingError         CleanFinishReason = 67
)

// Defines values for CleanStartType.
const (
	CleanStartTypeAlexa        CleanStartType = 801
	CleanStartTypeAlipay       CleanStartType = 902
	CleanStartTypeApp          CleanStartType = 2
	CleanStartTypeAqara        CleanStartType = 903
	CleanStartTypeButton       CleanStartType = 1
	CleanStartTypeClova        CleanStartType = 811
	CleanStartTypeDingdong     CleanStartType = 809
	CleanStartTypeDuer         CleanStartType = 808
	CleanStartTypeGoogle       CleanStartType = 802
	CleanStartTypeHisense      CleanStartType = 904
	CleanStartTypeHomekit      CleanStartType = 805
	CleanStartTypeHuawei       CleanStartType = 905
	CleanStartTypeIfttt        CleanStartType = 803
	CleanStartTypeMiHome       CleanStartType = 4
	CleanStartTypeQuickStart   CleanStartType = 5
	CleanStartTypeRoutines     CleanStartType = 101
	CleanStartTypeSchedule     CleanStartType = 3
	CleanStartTypeSiri         CleanStartType = 810
	CleanStartTypeSmartWatch   CleanStartType = 821
	CleanStartTypeTmallGenie   CleanStartType = 807
	CleanStartTypeVoiceControl CleanStartType = 13
	CleanStartTypeWechat       CleanStartType = 901
	CleanStartTypeWidgetLaunch CleanStartType = 820
	CleanStartTypeXiaoai       CleanStartType = 806
	CleanStartTypeYandex       CleanStartType = 804
)

// Defines values for CleanType.
const (
	CleanTypeAllZone     CleanType = 1
	CleanTypeDrawZone    CleanType = 2
	CleanTypePetPatrol   CleanType = 6
	CleanTypeQuickBuild  CleanType = 4
	CleanTypeSelectZone  CleanType = 3
	CleanTypeVideoPatrol CleanType = 5
)

// Defines values for CleaningState.
const (
	CleaningStateComplete                CleaningState = 0
	CleaningStateGlobalCleanNotComplete  CleaningState = 1
	CleaningStateSegmentCleanNotComplete CleaningState = 3
	CleaningStateZoneCleanNotComplete    CleaningState = 2
)

// Defines values for CommandAcceptance.
const (
	CommandAcceptanceOK CommandAcceptance = "ok"
)

// Defines values for DeviceErrorCode.
const (
	DeviceErrorCodeAudioError             DeviceErrorCode = 56
	DeviceErrorCodeBatteryError           DeviceErrorCode = 14
	DeviceErrorCodeBumperStuck            DeviceErrorCode = 2
	DeviceErrorCodeCannotCrossCarpet      DeviceErrorCode = 31
	DeviceErrorCodeChargingError          DeviceErrorCode = 13
	DeviceErrorCodeCheckCleanCarouse      DeviceErrorCode = 55
	DeviceErrorCodeCleanCarouselException DeviceErrorCode = 52
	DeviceErrorCodeCleanCarouselWaterFull DeviceErrorCode = 53
	DeviceErrorCodeClearBrushException    DeviceErrorCode = 42
	DeviceErrorCodeClearBrushException2   DeviceErrorCode = 43
	DeviceErrorCodeClearWaterBoxException DeviceErrorCode = 41
	DeviceErrorCodeClearWaterBoxHoare     DeviceErrorCode = 38
	DeviceErrorCodeCliffSensorError       DeviceErrorCode = 4
	DeviceErrorCodeCollectDustError3      DeviceErrorCode = 34
	DeviceErrorCodeCollectDustError4      DeviceErrorCode = 35
	DeviceErrorCodeCompassError           DeviceErrorCode = 11
	DeviceErrorCodeDirtyWaterBoxHoare     DeviceErrorCode = 39
	DeviceErrorCodeDock                   DeviceErrorCode = 19
	DeviceErrorCodeDockLocatorError       DeviceErrorCode = 22
	DeviceErrorCodeDrainWaterException    DeviceErrorCode = 49
	DeviceErrorCodeFanError               DeviceErrorCode = 18
	DeviceErrorCodeFilterBlocked          DeviceErrorCode = 29
	DeviceErrorCodeFilterScreenException  DeviceErrorCode = 44
	DeviceErrorCodeInternalError          DeviceErrorCode = 32
	DeviceErrorCodeInvisibleWallDetected  DeviceErrorCode = 30
	DeviceErrorCodeLidarBlocked           DeviceErrorCode = 1
	DeviceErrorCodeLightTouch             DeviceErrorCode = 26
	DeviceErrorCodeLowBattery             DeviceErrorCode = 12
	DeviceErrorCodeMainBrushJammed        DeviceErrorCode = 5
	DeviceErrorCodeMoppingRoller1         DeviceErrorCode = 36
	DeviceErrorCodeMoppingRoller2         DeviceErrorCode = 45
	DeviceErrorCodeMoppingRollerError2    DeviceErrorCode = 37
	DeviceErrorCodeNoDustbin              DeviceErrorCode = 9
	DeviceErrorCodeNogoZoneDetected       DeviceErrorCode = 24
	DeviceErrorCodeNone                   DeviceErrorCode = 0
	DeviceErrorCodeOpticalFlowSensorDirt  DeviceErrorCode = 20
	DeviceErrorCodeReturnToDockFail       DeviceErrorCode = 23
	DeviceErrorCodeRobotOnCarpet          DeviceErrorCode = 28
	DeviceErrorCodeRobotTilted            DeviceErrorCode = 16
	DeviceErrorCodeRobotTrapped           DeviceErrorCode = 8
	DeviceErrorCodeSideBrushError         DeviceErrorCode = 17
	DeviceErrorCodeSideBrushJammed        DeviceErrorCode = 6
	DeviceErrorCodeSinkStrainerHoare      DeviceErrorCode = 40
	DeviceErrorCodeStrainerError          DeviceErrorCode = 10
	DeviceErrorCodeTemperatureProtection  DeviceErrorCode = 51
	DeviceErrorCodeUpWaterException       DeviceErrorCode = 48
	DeviceErrorCodeVerticalBumperPressed  DeviceErrorCode = 21
	DeviceErrorCodeVibrariseJammed        DeviceErrorCode = 27
	DeviceErrorCodeVisualSensor           DeviceErrorCode = 25
	DeviceErrorCodeWallSensorDirty        DeviceErrorCode = 15
	DeviceErrorCodeWaterCarriageDrop      DeviceErrorCode = 54
	DeviceErrorCodeWheelsJammed           DeviceErrorCode = 7
	DeviceErrorCodeWheelsSuspended        DeviceErrorCode = 3
)

// Defines values for DeviceState.
const (
	DeviceStateAirDryingStopping       DeviceState = 202
	DeviceStateAttachingTheMop         DeviceState = 33
	DeviceStateBackToDockWashingDuster DeviceState = 6310
	DeviceStateChargerDisconnected     DeviceState = 2
	DeviceStateCharging                DeviceState = 8
	DeviceStateChargingComplete        DeviceState = 100
	DeviceStateChargingProblem         DeviceState = 9
	DeviceStateCleanMopCleaning        DeviceState = 6302
	DeviceStateCleanMopMopping         DeviceState = 6303
	DeviceStateCleaning                DeviceState = 5
	DeviceStateDetachingTheMop         DeviceState = 34
	DeviceStateDeviceOffline           DeviceState = 101
	DeviceStateDocking                 DeviceState = 15
	DeviceStateEggAttack               DeviceState = 30
	DeviceStateEmptyingTheBin          DeviceState = 22
	DeviceStateError                   DeviceState = 12
	DeviceStateGoingToTarget           DeviceState = 16
	DeviceStateGoingToWashTheMop       DeviceState = 26
	DeviceStateIdle                    DeviceState = 3
	DeviceStateInCall                  DeviceState = 28
	DeviceStateLocked                  DeviceState = 103
	DeviceStateManualMode              DeviceState = 7
	DeviceStateMapping                 DeviceState = 29
	DeviceStatePatrol                  DeviceState = 32
	DeviceStatePaused                  DeviceState = 10
	DeviceStateRemoteControlActive     DeviceState = 4
	DeviceStateReturningHome           DeviceState = 6
	DeviceStateRobotStatusMopping      DeviceState = 6301
	DeviceStateSegmentCleanMopCleaning DeviceState = 6305
	DeviceStateSegmentCleanMopMopping  DeviceState = 6306
	DeviceStateSegmentCleaning         DeviceState = 18
	DeviceStateSegmentMopping          DeviceState = 6304
	DeviceStateShuttingDown            DeviceState = 13
	DeviceStateSpotCleaning            DeviceState = 11
	DeviceStateStarting                DeviceState = 1
	DeviceStateUnknown                 DeviceState = 0
	DeviceStateUpdating                DeviceState = 14
	DeviceStateWashingTheMop           DeviceState = 23
	DeviceStateWashingTheMop2          DeviceState = 25
	DeviceStateZonedCleanMopCleaning   DeviceState = 6308
	DeviceStateZonedCleanMopMopping    DeviceState = 6309
	DeviceStateZonedCleaning           DeviceState = 17
	DeviceStateZonedMopping            DeviceState = 6307
)

// Defines values for DockErrorCode.
const (
	DockErrorCodeAutoEmptyDockFanError     DockErrorCode = 33
	DockErrorCodeAutoEmptyDockVoltageError DockErrorCode = 35
	DockErrorCodeCleaningTankFullOrBlocked DockErrorCode = 53
	DockErrorCodeDirtyTankLatchOpen        DockErrorCode = 44
	DockErrorCodeDuctBlockage              DockErrorCode = 34
	DockErrorCodeMaintenanceBrushJammed    DockErrorCode = 42
	DockErrorCodeNoDustbin                 DockErrorCode = 46
	DockErrorCodeNoDustbinOrFilter         DockErrorCode = 32
	DockErrorCodeOk                        DockErrorCode = 0
	DockErrorCodeWasteWaterTankFull        DockErrorCode = 39
	DockErrorCodeWaterEmpty                DockErrorCode = 38
)

// Defines values for DockType.
const (
	DockTypeCoupleDock      DockType = 13
	DockTypeF1CDock         DockType = 46
	DockTypeF1Dock          DockType = 41
	DockTypeF1RDock         DockType = 42
	DockTypeF1SDock         DockType = 44
	DockTypeF2RDock         DockType = 43
	DockTypeHeraDock        DockType = 24
	DockTypeK1CDock         DockType = 19
	DockTypeK1CLiteDock     DockType = 28
	DockTypeK1DDock         DockType = 37
	DockTypeK1Dock          DockType = 17
	DockTypeK1RDock         DockType = 29
	DockTypeK1SDock         DockType = 20
	DockTypeK1SProDock      DockType = 26
	DockTypeO0Dock          DockType = 0
	DockTypeO1Dock          DockType = 1
	DockTypeO2Dock          DockType = 2
	DockTypeO3Dock          DockType = 3
	DockTypeO3PlusDock      DockType = 6
	DockTypeO4Dock          DockType = 7
	DockTypeO5Dock          DockType = 10
	DockTypeO6Dock          DockType = 18
	DockTypeO7Dock          DockType = 35
	DockTypeO7HDock         DockType = 45
	DockTypeOcDock          DockType = 5
	DockTypePearlDock       DockType = 8
	DockTypePearlPlusDock   DockType = 9
	DockTypeShell2CDock     DockType = 15
	DockTypeShell2EDock     DockType = 22
	DockTypeShell2EHeatDock DockType = 40
	DockTypeShell2ELiteDock DockType = 30
	DockTypeShell2SDock     DockType = 11
	DockTypeShell3CDock     DockType = 23
	DockTypeShell3Dock      DockType = 14
	DockTypeShell3PDock     DockType = 38
	DockTypeShell3SDock     DockType = 16
	DockTypeShell4DDock     DockType = 39
	DockTypeShell4PDock     DockType = 33
	DockTypeShell4RDock     DockType = 32
	DockTypeShell4RcDock    DockType = 31
	DockTypeShell4SDock     DockType = 34
	DockTypeShellEDock      DockType = 21
	DockTypeType27Dock      DockType = 27
	DockTypeUnknown         DockType = -9999
)

// Defines values for FanSpeed.
const (
	FanSpeedBalanced FanSpeed = 102
	FanSpeedMax      FanSpeed = 104
	FanSpeedMaxPlus  FanSpeed = 108
	FanSpeedOff      FanSpeed = 105
	FanSpeedQuiet    FanSpeed = 101
	FanSpeedTurbo    FanSpeed = 103
)

// Defines values for MopMode.
const (
	MopModeCustom   MopMode = 302
	MopModeDeep     MopMode = 301
	MopModeDeepPlus MopMode = 303
	MopModeStandard MopMode = 300
)

// Defines values for RPCMethod.
const (
	RPCCleanSegments       RPCMethod = "app_segment_clean"
	RPCCleanZones          RPCMethod = "app_zoned_clean"
	RPCDisableDND          RPCMethod = "close_dnd_timer"
	RPCGetCleanRecord      RPCMethod = "get_clean_record"
	RPCGetCleaningSummary  RPCMethod = "get_clean_summary"
	RPCGetConsumables      RPCMethod = "get_consumable"
	RPCGetDND              RPCMethod = "get_dnd_timer"
	RPCGetStatus           RPCMethod = "get_status"
	RPCPauseCleaning       RPCMethod = "app_pause"
	RPCRCEnd               RPCMethod = "app_rc_end"
	RPCRCMove              RPCMethod = "app_rc_move"
	RPCRCStart             RPCMethod = "app_rc_start"
	RPCRCStop              RPCMethod = "app_rc_stop"
	RPCReturnToDock        RPCMethod = "app_charge"
	RPCSetDND              RPCMethod = "set_dnd_timer"
	RPCSetFanSpeed         RPCMethod = "set_custom_mode"
	RPCSetMopMode          RPCMethod = "set_mop_mode"
	RPCSetWaterMode        RPCMethod = "set_water_box_custom_mode"
	RPCSpotClean           RPCMethod = "app_spot"
	RPCStartCleaning       RPCMethod = "app_start"
	RPCStartDustCollection RPCMethod = "app_start_collect_dust"
	RPCStartMopWashing     RPCMethod = "app_start_wash"
	RPCStopCleaning        RPCMethod = "app_stop"
	RPCStopDustCollection  RPCMethod = "app_stop_collect_dust"
	RPCStopMopWashing      RPCMethod = "app_stop_wash"
)

// Defines values for WaterMode.
const (
	WaterModeHigh   WaterMode = 203
	WaterModeLow    WaterMode = 201
	WaterModeMedium WaterMode = 202
	WaterModeOff    WaterMode = 200
)

// Acknowledgement Expected command acceptance is ["ok"].
type Acknowledgement = []CommandAcceptance

// ChargeStatus Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type ChargeStatus int64

// CleanFinishReason Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type CleanFinishReason int64

// CleanRecord Presence-aware CleanRecord inventory from pinned Python V1 containers; absent fields stay absent. Cleaning area is square millimeters and durations are seconds.
type CleanRecord struct {
	Area       *int64 `json:"area,omitempty"`
	AvoidCount *int64 `json:"avoid_count,omitempty"`
	Begin      *int64 `json:"begin,omitempty"`

	// CleanType Open CleanType value; future firmware values are accepted.
	CleanType            *CleanType `json:"clean_type,omitempty"`
	Complete             *int64     `json:"complete,omitempty"`
	Duration             *int64     `json:"duration,omitempty"`
	DustCollectionStatus *int64     `json:"dust_collection_status,omitempty"`
	End                  *int64     `json:"end,omitempty"`
	Error                *int64     `json:"error,omitempty"`

	// FinishReason Open CleanFinishReason value; future firmware values are accepted.
	FinishReason *CleanFinishReason `json:"finish_reason,omitempty"`
	MapFlag      *int64             `json:"map_flag,omitempty"`

	// StartType Open CleanStartType value; future firmware values are accepted.
	StartType            *CleanStartType            `json:"start_type,omitempty"`
	WashCount            *int64                     `json:"wash_count,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CleanRecordLegacy Legacy numeric record tuple: begin Unix time, end Unix time, duration seconds, area square millimeters. Additional numeric columns have unknown meaning and are not projected.
type CleanRecordLegacy = []int64

// CleanRecordParts Ordered multipart record response. Each part is an object or a legacy numeric tuple; deeper arbitrary array recursion is unsupported.
type CleanRecordParts = []CleanRecordParts_Item

// CleanRecordParts_Item defines model for CleanRecordParts.Item.
type CleanRecordParts_Item struct {
	union json.RawMessage
}

// CleanRecordRPCResult One record object, a legacy numeric tuple, or ordered multipart record objects and nested legacy tuples.
type CleanRecordRPCResult struct {
	union json.RawMessage
}

// CleanSegmentsRPCJSONRequestBody defines model for CleanSegmentsRPCJSONRequestBody.
type CleanSegmentsRPCJSONRequestBody = SegmentParameters

// CleanStartType Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type CleanStartType int64

// CleanType Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type CleanType int64

// CleanZonesRPCJSONRequestBody defines model for CleanZonesRPCJSONRequestBody.
type CleanZonesRPCJSONRequestBody = ZoneParameters

// CleaningState Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type CleaningState int64

// CleaningSummary Presence-aware CleaningSummary inventory from pinned Python V1 containers; absent fields stay absent. Cleaning area is square millimeters and durations are seconds.
type CleaningSummary struct {
	CleanArea            *int64                     `json:"clean_area,omitempty"`
	CleanCount           *int64                     `json:"clean_count,omitempty"`
	CleanTime            *int64                     `json:"clean_time,omitempty"`
	DustCollectionCount  *int64                     `json:"dust_collection_count,omitempty"`
	LastCleanT           *int64                     `json:"last_clean_t,omitempty"`
	Records              *[]int64                   `json:"records,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CleaningSummaryCounter Legacy tuple counter; null means unavailable.
type CleaningSummaryCounter = int64

// CleaningSummaryDuration Total cleaning time in seconds when the device returns only a scalar duration.
type CleaningSummaryDuration = int64

// CleaningSummaryLegacy Ordered clean_time, clean_area, clean_count, records; fourth entry is an array of record IDs. OpenAPI 3.0 represents the heterogeneous array elements; the SDK additionally enforces numeric counters in the first three positions and record IDs in the fourth.
type CleaningSummaryLegacy = []json.RawMessage

// CleaningSummaryRPCResult Object, single duration, ordered legacy tuple, or singleton object array as supported by the pinned Python V1 converter.
type CleaningSummaryRPCResult struct {
	union json.RawMessage
}

// CleaningSummaryRecordIDs Legacy tuple fourth position contains cleaning record IDs.
type CleaningSummaryRecordIDs = []int64

// CleaningSummarySingletonResult defines model for CleaningSummarySingletonResult.
type CleaningSummarySingletonResult = []CleaningSummary

// CommandAcceptance Device command acceptance token. Unknown tokens are rejected by the public operation.
type CommandAcceptance string

// Consumables Presence-aware Consumables inventory from pinned Python V1 containers; absent fields stay absent. Cleaning area is square millimeters and durations are seconds.
type Consumables struct {
	CleaningBrushWorkTimes  *int64                     `json:"cleaning_brush_work_times,omitempty"`
	DustCollectionWorkTimes *int64                     `json:"dust_collection_work_times,omitempty"`
	FilterElementWorkTime   *int64                     `json:"filter_element_work_time,omitempty"`
	FilterWorkTime          *int64                     `json:"filter_work_time,omitempty"`
	MainBrushWorkTime       *int64                     `json:"main_brush_work_time,omitempty"`
	MoprollerWorkTime       *int64                     `json:"moproller_work_time,omitempty"`
	SensorDirtyTime         *int64                     `json:"sensor_dirty_time,omitempty"`
	SideBrushWorkTime       *int64                     `json:"side_brush_work_time,omitempty"`
	StrainerWorkTimes       *int64                     `json:"strainer_work_times,omitempty"`
	AdditionalProperties    map[string]json.RawMessage `json:"-"`
}

// ConsumablesRPCResult Device returns an object or an array containing exactly one object. Unknown firmware fields remain available as raw JSON properties.
type ConsumablesRPCResult struct {
	union json.RawMessage
}

// ConsumablesSingletonResult defines model for ConsumablesSingletonResult.
type ConsumablesSingletonResult = []Consumables

// DND defines model for DND.
type DND struct {
	Enabled              *int64                     `json:"enabled,omitempty"`
	EndHour              *int64                     `json:"end_hour,omitempty"`
	EndMinute            *int64                     `json:"end_minute,omitempty"`
	StartHour            *int64                     `json:"start_hour,omitempty"`
	StartMinute          *int64                     `json:"start_minute,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// DNDRPCResult Device returns an object or an array containing exactly one object. Unknown firmware fields remain available as raw JSON properties.
type DNDRPCResult struct {
	union json.RawMessage
}

// DNDSingletonResult defines model for DNDSingletonResult.
type DNDSingletonResult = []DND

// DeviceErrorCode Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type DeviceErrorCode int64

// DeviceState Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type DeviceState int64

// DisableDNDRPCJSONRequestBody defines model for DisableDNDRPCJSONRequestBody.
type DisableDNDRPCJSONRequestBody = NoParameters

// DockErrorCode Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type DockErrorCode int64

// DockType Open numeric enum from pinned Python V1 mappings; unknown firmware values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type DockType int64

// FanSpeed Open device-dependent numeric enum; future values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type FanSpeed int

// GetCleanRecordRPCJSONRequestBody defines model for GetCleanRecordRPCJSONRequestBody.
type GetCleanRecordRPCJSONRequestBody = IntegerParameters

// GetCleaningSummaryRPCJSONRequestBody defines model for GetCleaningSummaryRPCJSONRequestBody.
type GetCleaningSummaryRPCJSONRequestBody = NoParameters

// GetConsumablesRPCJSONRequestBody defines model for GetConsumablesRPCJSONRequestBody.
type GetConsumablesRPCJSONRequestBody = NoParameters

// GetDNDRPCJSONRequestBody defines model for GetDNDRPCJSONRequestBody.
type GetDNDRPCJSONRequestBody = NoParameters

// GetStatusRPCJSONRequestBody defines model for GetStatusRPCJSONRequestBody.
type GetStatusRPCJSONRequestBody = NoParameters

// IntegerParameters defines model for IntegerParameters.
type IntegerParameters = []int64

// MopMode Open device-dependent numeric enum; future values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type MopMode int

// NoParameters defines model for NoParameters.
type NoParameters = []int64

// PauseCleaningRPCJSONRequestBody defines model for PauseCleaningRPCJSONRequestBody.
type PauseCleaningRPCJSONRequestBody = NoParameters

// RCCommand defines model for RCCommand.
type RCCommand struct {
	// Duration Movement duration in milliseconds, from 1 through 5000.
	Duration int `json:"duration"`

	// Omega Angular velocity in radians per second, from -0.8 through 0.8.
	Omega  float32 `json:"omega"`
	Seqnum int64   `json:"seqnum"`

	// Velocity Linear velocity in meters per second, from -0.3 through 0.3.
	Velocity float32 `json:"velocity"`
}

// RCEndRPCJSONRequestBody defines model for RCEndRPCJSONRequestBody.
type RCEndRPCJSONRequestBody = NoParameters

// RCMoveRPCJSONRequestBody defines model for RCMoveRPCJSONRequestBody.
type RCMoveRPCJSONRequestBody = RCParameters

// RCParameters defines model for RCParameters.
type RCParameters = []RCCommand

// RCStartRPCJSONRequestBody defines model for RCStartRPCJSONRequestBody.
type RCStartRPCJSONRequestBody = NoParameters

// RCStopRPCJSONRequestBody defines model for RCStopRPCJSONRequestBody.
type RCStopRPCJSONRequestBody = NoParameters

// RPCMethod defines model for RPCMethod.
type RPCMethod string

// ReturnToDockRPCJSONRequestBody defines model for ReturnToDockRPCJSONRequestBody.
type ReturnToDockRPCJSONRequestBody = NoParameters

// SegmentCommand defines model for SegmentCommand.
type SegmentCommand struct {
	Repeat   int64   `json:"repeat"`
	Segments []int64 `json:"segments"`
}

// SegmentParameters defines model for SegmentParameters.
type SegmentParameters = []SegmentCommand

// SetDNDRPCJSONRequestBody defines model for SetDNDRPCJSONRequestBody.
type SetDNDRPCJSONRequestBody = IntegerParameters

// SetFanSpeedRPCJSONRequestBody defines model for SetFanSpeedRPCJSONRequestBody.
type SetFanSpeedRPCJSONRequestBody = IntegerParameters

// SetMopModeRPCJSONRequestBody defines model for SetMopModeRPCJSONRequestBody.
type SetMopModeRPCJSONRequestBody = IntegerParameters

// SetWaterModeRPCJSONRequestBody defines model for SetWaterModeRPCJSONRequestBody.
type SetWaterModeRPCJSONRequestBody = IntegerParameters

// SpotCleanRPCJSONRequestBody defines model for SpotCleanRPCJSONRequestBody.
type SpotCleanRPCJSONRequestBody = NoParameters

// StartCleaningRPCJSONRequestBody defines model for StartCleaningRPCJSONRequestBody.
type StartCleaningRPCJSONRequestBody = NoParameters

// StartDustCollectionRPCJSONRequestBody defines model for StartDustCollectionRPCJSONRequestBody.
type StartDustCollectionRPCJSONRequestBody = NoParameters

// StartMopWashingRPCJSONRequestBody defines model for StartMopWashingRPCJSONRequestBody.
type StartMopWashingRPCJSONRequestBody = NoParameters

// Status Presence-aware Status inventory from pinned Python V1 containers; absent fields stay absent. Cleaning area is square millimeters and durations are seconds.
type Status struct {
	AdbumperStatus     *[]int64 `json:"adbumper_status,omitempty"`
	AutoDustCollection *int64   `json:"auto_dust_collection,omitempty"`
	AvoidCount         *int64   `json:"avoid_count,omitempty"`
	BackType           *int64   `json:"back_type,omitempty"`
	Battery            *int64   `json:"battery,omitempty"`
	CameraStatus       *int64   `json:"camera_status,omitempty"`

	// ChargeStatus Open ChargeStatus value; future firmware values are accepted.
	ChargeStatus         *ChargeStatus `json:"charge_status,omitempty"`
	CleanArea            *int64        `json:"clean_area,omitempty"`
	CleanPercent         *int64        `json:"clean_percent,omitempty"`
	CleanTime            *int64        `json:"clean_time,omitempty"`
	CollisionAvoidStatus *int64        `json:"collision_avoid_status,omitempty"`
	CommonStatus         *int64        `json:"common_status,omitempty"`
	CornerCleanMode      *int64        `json:"corner_clean_mode,omitempty"`
	DebugMode            *int64        `json:"debug_mode,omitempty"`
	DistanceOff          *int64        `json:"distance_off,omitempty"`
	DndEnabled           *int64        `json:"dnd_enabled,omitempty"`

	// DockErrorStatus Open DockErrorCode value; future firmware values are accepted.
	DockErrorStatus *DockErrorCode `json:"dock_error_status,omitempty"`

	// DockType Open DockType value; future firmware values are accepted.
	DockType             *DockType `json:"dock_type,omitempty"`
	DryStatus            *int64    `json:"dry_status,omitempty"`
	Dss                  *int64    `json:"dss,omitempty"`
	DustCollectionStatus *int64    `json:"dust_collection_status,omitempty"`

	// ErrorCode Open DeviceErrorCode value; future firmware values are accepted.
	ErrorCode *DeviceErrorCode `json:"error_code,omitempty"`

	// FanPower Open FanSpeed value; future firmware values are accepted.
	FanPower              *FanSpeed `json:"fan_power,omitempty"`
	HomeSecEnablePassword *int64    `json:"home_sec_enable_password,omitempty"`
	HomeSecStatus         *int64    `json:"home_sec_status,omitempty"`

	// InCleaning Open CleaningState value; future firmware values are accepted.
	InCleaning         *CleaningState `json:"in_cleaning,omitempty"`
	InFreshState       *int64         `json:"in_fresh_state,omitempty"`
	InReturning        *int64         `json:"in_returning,omitempty"`
	InWarmup           *int64         `json:"in_warmup,omitempty"`
	IsExploring        *int64         `json:"is_exploring,omitempty"`
	IsLocating         *int64         `json:"is_locating,omitempty"`
	Kct                *int64         `json:"kct,omitempty"`
	LabStatus          *int64         `json:"lab_status,omitempty"`
	LastCleanT         *int64         `json:"last_clean_t,omitempty"`
	LockStatus         *int64         `json:"lock_status,omitempty"`
	MapPresent         *int64         `json:"map_present,omitempty"`
	MapStatus          *int64         `json:"map_status,omitempty"`
	MopForbiddenEnable *int64         `json:"mop_forbidden_enable,omitempty"`

	// MopMode Open MopMode value; future firmware values are accepted.
	MopMode       *MopMode `json:"mop_mode,omitempty"`
	MsgSeq        *int64   `json:"msg_seq,omitempty"`
	MsgVer        *int64   `json:"msg_ver,omitempty"`
	Rdt           *int64   `json:"rdt,omitempty"`
	Repeat        *int64   `json:"repeat,omitempty"`
	ReplenishMode *int64   `json:"replenish_mode,omitempty"`
	Rss           *int64   `json:"rss,omitempty"`

	// State Open DeviceState value; future firmware values are accepted.
	State                  *DeviceState `json:"state,omitempty"`
	SubdivisionSets        *int64       `json:"subdivision_sets,omitempty"`
	SwitchMapMode          *int64       `json:"switch_map_mode,omitempty"`
	UnsaveMapFlag          *int64       `json:"unsave_map_flag,omitempty"`
	UnsaveMapReason        *int64       `json:"unsave_map_reason,omitempty"`
	WashPhase              *int64       `json:"wash_phase,omitempty"`
	WashReady              *int64       `json:"wash_ready,omitempty"`
	WashStatus             *int64       `json:"wash_status,omitempty"`
	WaterBoxCarriageStatus *int64       `json:"water_box_carriage_status,omitempty"`

	// WaterBoxMode Open WaterMode value; future firmware values are accepted.
	WaterBoxMode         *WaterMode                 `json:"water_box_mode,omitempty"`
	WaterBoxStatus       *int64                     `json:"water_box_status,omitempty"`
	WaterShortageStatus  *int64                     `json:"water_shortage_status,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// StatusRPCResult Device returns an object or an array containing exactly one object. Unknown firmware fields remain available as raw JSON properties.
type StatusRPCResult struct {
	union json.RawMessage
}

// StatusSingletonResult defines model for StatusSingletonResult.
type StatusSingletonResult = []Status

// StopCleaningRPCJSONRequestBody defines model for StopCleaningRPCJSONRequestBody.
type StopCleaningRPCJSONRequestBody = NoParameters

// StopDustCollectionRPCJSONRequestBody defines model for StopDustCollectionRPCJSONRequestBody.
type StopDustCollectionRPCJSONRequestBody = NoParameters

// StopMopWashingRPCJSONRequestBody defines model for StopMopWashingRPCJSONRequestBody.
type StopMopWashingRPCJSONRequestBody = NoParameters

// WaterMode Open device-dependent numeric enum; future values are preserved. This named inventory lists known constants; field contracts explicitly accept future values.
type WaterMode int

// ZoneParameters defines model for ZoneParameters.
type ZoneParameters = [][]int64

// Getter for additional properties for CleanRecord. Returns the specified
// element and whether it was found
func (a CleanRecord) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CleanRecord
func (a *CleanRecord) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CleanRecord to handle AdditionalProperties
func (a *CleanRecord) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["area"]; found {
		err = json.Unmarshal(raw, &a.Area)
		if err != nil {
			return fmt.Errorf("error reading 'area': %w", err)
		}
		delete(object, "area")
	}

	if raw, found := object["avoid_count"]; found {
		err = json.Unmarshal(raw, &a.AvoidCount)
		if err != nil {
			return fmt.Errorf("error reading 'avoid_count': %w", err)
		}
		delete(object, "avoid_count")
	}

	if raw, found := object["begin"]; found {
		err = json.Unmarshal(raw, &a.Begin)
		if err != nil {
			return fmt.Errorf("error reading 'begin': %w", err)
		}
		delete(object, "begin")
	}

	if raw, found := object["clean_type"]; found {
		err = json.Unmarshal(raw, &a.CleanType)
		if err != nil {
			return fmt.Errorf("error reading 'clean_type': %w", err)
		}
		delete(object, "clean_type")
	}

	if raw, found := object["complete"]; found {
		err = json.Unmarshal(raw, &a.Complete)
		if err != nil {
			return fmt.Errorf("error reading 'complete': %w", err)
		}
		delete(object, "complete")
	}

	if raw, found := object["duration"]; found {
		err = json.Unmarshal(raw, &a.Duration)
		if err != nil {
			return fmt.Errorf("error reading 'duration': %w", err)
		}
		delete(object, "duration")
	}

	if raw, found := object["dust_collection_status"]; found {
		err = json.Unmarshal(raw, &a.DustCollectionStatus)
		if err != nil {
			return fmt.Errorf("error reading 'dust_collection_status': %w", err)
		}
		delete(object, "dust_collection_status")
	}

	if raw, found := object["end"]; found {
		err = json.Unmarshal(raw, &a.End)
		if err != nil {
			return fmt.Errorf("error reading 'end': %w", err)
		}
		delete(object, "end")
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["finish_reason"]; found {
		err = json.Unmarshal(raw, &a.FinishReason)
		if err != nil {
			return fmt.Errorf("error reading 'finish_reason': %w", err)
		}
		delete(object, "finish_reason")
	}

	if raw, found := object["map_flag"]; found {
		err = json.Unmarshal(raw, &a.MapFlag)
		if err != nil {
			return fmt.Errorf("error reading 'map_flag': %w", err)
		}
		delete(object, "map_flag")
	}

	if raw, found := object["start_type"]; found {
		err = json.Unmarshal(raw, &a.StartType)
		if err != nil {
			return fmt.Errorf("error reading 'start_type': %w", err)
		}
		delete(object, "start_type")
	}

	if raw, found := object["wash_count"]; found {
		err = json.Unmarshal(raw, &a.WashCount)
		if err != nil {
			return fmt.Errorf("error reading 'wash_count': %w", err)
		}
		delete(object, "wash_count")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CleanRecord to handle AdditionalProperties
func (a CleanRecord) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Area != nil {
		object["area"], err = json.Marshal(a.Area)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'area': %w", err)
		}
	}

	if a.AvoidCount != nil {
		object["avoid_count"], err = json.Marshal(a.AvoidCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'avoid_count': %w", err)
		}
	}

	if a.Begin != nil {
		object["begin"], err = json.Marshal(a.Begin)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'begin': %w", err)
		}
	}

	if a.CleanType != nil {
		object["clean_type"], err = json.Marshal(a.CleanType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_type': %w", err)
		}
	}

	if a.Complete != nil {
		object["complete"], err = json.Marshal(a.Complete)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'complete': %w", err)
		}
	}

	if a.Duration != nil {
		object["duration"], err = json.Marshal(a.Duration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duration': %w", err)
		}
	}

	if a.DustCollectionStatus != nil {
		object["dust_collection_status"], err = json.Marshal(a.DustCollectionStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dust_collection_status': %w", err)
		}
	}

	if a.End != nil {
		object["end"], err = json.Marshal(a.End)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'end': %w", err)
		}
	}

	if a.Error != nil {
		object["error"], err = json.Marshal(a.Error)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'error': %w", err)
		}
	}

	if a.FinishReason != nil {
		object["finish_reason"], err = json.Marshal(a.FinishReason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'finish_reason': %w", err)
		}
	}

	if a.MapFlag != nil {
		object["map_flag"], err = json.Marshal(a.MapFlag)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'map_flag': %w", err)
		}
	}

	if a.StartType != nil {
		object["start_type"], err = json.Marshal(a.StartType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'start_type': %w", err)
		}
	}

	if a.WashCount != nil {
		object["wash_count"], err = json.Marshal(a.WashCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wash_count': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CleaningSummary. Returns the specified
// element and whether it was found
func (a CleaningSummary) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CleaningSummary
func (a *CleaningSummary) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CleaningSummary to handle AdditionalProperties
func (a *CleaningSummary) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["clean_area"]; found {
		err = json.Unmarshal(raw, &a.CleanArea)
		if err != nil {
			return fmt.Errorf("error reading 'clean_area': %w", err)
		}
		delete(object, "clean_area")
	}

	if raw, found := object["clean_count"]; found {
		err = json.Unmarshal(raw, &a.CleanCount)
		if err != nil {
			return fmt.Errorf("error reading 'clean_count': %w", err)
		}
		delete(object, "clean_count")
	}

	if raw, found := object["clean_time"]; found {
		err = json.Unmarshal(raw, &a.CleanTime)
		if err != nil {
			return fmt.Errorf("error reading 'clean_time': %w", err)
		}
		delete(object, "clean_time")
	}

	if raw, found := object["dust_collection_count"]; found {
		err = json.Unmarshal(raw, &a.DustCollectionCount)
		if err != nil {
			return fmt.Errorf("error reading 'dust_collection_count': %w", err)
		}
		delete(object, "dust_collection_count")
	}

	if raw, found := object["last_clean_t"]; found {
		err = json.Unmarshal(raw, &a.LastCleanT)
		if err != nil {
			return fmt.Errorf("error reading 'last_clean_t': %w", err)
		}
		delete(object, "last_clean_t")
	}

	if raw, found := object["records"]; found {
		err = json.Unmarshal(raw, &a.Records)
		if err != nil {
			return fmt.Errorf("error reading 'records': %w", err)
		}
		delete(object, "records")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CleaningSummary to handle AdditionalProperties
func (a CleaningSummary) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CleanArea != nil {
		object["clean_area"], err = json.Marshal(a.CleanArea)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_area': %w", err)
		}
	}

	if a.CleanCount != nil {
		object["clean_count"], err = json.Marshal(a.CleanCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_count': %w", err)
		}
	}

	if a.CleanTime != nil {
		object["clean_time"], err = json.Marshal(a.CleanTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_time': %w", err)
		}
	}

	if a.DustCollectionCount != nil {
		object["dust_collection_count"], err = json.Marshal(a.DustCollectionCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dust_collection_count': %w", err)
		}
	}

	if a.LastCleanT != nil {
		object["last_clean_t"], err = json.Marshal(a.LastCleanT)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_clean_t': %w", err)
		}
	}

	if a.Records != nil {
		object["records"], err = json.Marshal(a.Records)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'records': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Consumables. Returns the specified
// element and whether it was found
func (a Consumables) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Consumables
func (a *Consumables) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Consumables to handle AdditionalProperties
func (a *Consumables) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cleaning_brush_work_times"]; found {
		err = json.Unmarshal(raw, &a.CleaningBrushWorkTimes)
		if err != nil {
			return fmt.Errorf("error reading 'cleaning_brush_work_times': %w", err)
		}
		delete(object, "cleaning_brush_work_times")
	}

	if raw, found := object["dust_collection_work_times"]; found {
		err = json.Unmarshal(raw, &a.DustCollectionWorkTimes)
		if err != nil {
			return fmt.Errorf("error reading 'dust_collection_work_times': %w", err)
		}
		delete(object, "dust_collection_work_times")
	}

	if raw, found := object["filter_element_work_time"]; found {
		err = json.Unmarshal(raw, &a.FilterElementWorkTime)
		if err != nil {
			return fmt.Errorf("error reading 'filter_element_work_time': %w", err)
		}
		delete(object, "filter_element_work_time")
	}

	if raw, found := object["filter_work_time"]; found {
		err = json.Unmarshal(raw, &a.FilterWorkTime)
		if err != nil {
			return fmt.Errorf("error reading 'filter_work_time': %w", err)
		}
		delete(object, "filter_work_time")
	}

	if raw, found := object["main_brush_work_time"]; found {
		err = json.Unmarshal(raw, &a.MainBrushWorkTime)
		if err != nil {
			return fmt.Errorf("error reading 'main_brush_work_time': %w", err)
		}
		delete(object, "main_brush_work_time")
	}

	if raw, found := object["moproller_work_time"]; found {
		err = json.Unmarshal(raw, &a.MoprollerWorkTime)
		if err != nil {
			return fmt.Errorf("error reading 'moproller_work_time': %w", err)
		}
		delete(object, "moproller_work_time")
	}

	if raw, found := object["sensor_dirty_time"]; found {
		err = json.Unmarshal(raw, &a.SensorDirtyTime)
		if err != nil {
			return fmt.Errorf("error reading 'sensor_dirty_time': %w", err)
		}
		delete(object, "sensor_dirty_time")
	}

	if raw, found := object["side_brush_work_time"]; found {
		err = json.Unmarshal(raw, &a.SideBrushWorkTime)
		if err != nil {
			return fmt.Errorf("error reading 'side_brush_work_time': %w", err)
		}
		delete(object, "side_brush_work_time")
	}

	if raw, found := object["strainer_work_times"]; found {
		err = json.Unmarshal(raw, &a.StrainerWorkTimes)
		if err != nil {
			return fmt.Errorf("error reading 'strainer_work_times': %w", err)
		}
		delete(object, "strainer_work_times")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Consumables to handle AdditionalProperties
func (a Consumables) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CleaningBrushWorkTimes != nil {
		object["cleaning_brush_work_times"], err = json.Marshal(a.CleaningBrushWorkTimes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'cleaning_brush_work_times': %w", err)
		}
	}

	if a.DustCollectionWorkTimes != nil {
		object["dust_collection_work_times"], err = json.Marshal(a.DustCollectionWorkTimes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dust_collection_work_times': %w", err)
		}
	}

	if a.FilterElementWorkTime != nil {
		object["filter_element_work_time"], err = json.Marshal(a.FilterElementWorkTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'filter_element_work_time': %w", err)
		}
	}

	if a.FilterWorkTime != nil {
		object["filter_work_time"], err = json.Marshal(a.FilterWorkTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'filter_work_time': %w", err)
		}
	}

	if a.MainBrushWorkTime != nil {
		object["main_brush_work_time"], err = json.Marshal(a.MainBrushWorkTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'main_brush_work_time': %w", err)
		}
	}

	if a.MoprollerWorkTime != nil {
		object["moproller_work_time"], err = json.Marshal(a.MoprollerWorkTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'moproller_work_time': %w", err)
		}
	}

	if a.SensorDirtyTime != nil {
		object["sensor_dirty_time"], err = json.Marshal(a.SensorDirtyTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sensor_dirty_time': %w", err)
		}
	}

	if a.SideBrushWorkTime != nil {
		object["side_brush_work_time"], err = json.Marshal(a.SideBrushWorkTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'side_brush_work_time': %w", err)
		}
	}

	if a.StrainerWorkTimes != nil {
		object["strainer_work_times"], err = json.Marshal(a.StrainerWorkTimes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'strainer_work_times': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DND. Returns the specified
// element and whether it was found
func (a DND) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DND
func (a *DND) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DND to handle AdditionalProperties
func (a *DND) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["enabled"]; found {
		err = json.Unmarshal(raw, &a.Enabled)
		if err != nil {
			return fmt.Errorf("error reading 'enabled': %w", err)
		}
		delete(object, "enabled")
	}

	if raw, found := object["end_hour"]; found {
		err = json.Unmarshal(raw, &a.EndHour)
		if err != nil {
			return fmt.Errorf("error reading 'end_hour': %w", err)
		}
		delete(object, "end_hour")
	}

	if raw, found := object["end_minute"]; found {
		err = json.Unmarshal(raw, &a.EndMinute)
		if err != nil {
			return fmt.Errorf("error reading 'end_minute': %w", err)
		}
		delete(object, "end_minute")
	}

	if raw, found := object["start_hour"]; found {
		err = json.Unmarshal(raw, &a.StartHour)
		if err != nil {
			return fmt.Errorf("error reading 'start_hour': %w", err)
		}
		delete(object, "start_hour")
	}

	if raw, found := object["start_minute"]; found {
		err = json.Unmarshal(raw, &a.StartMinute)
		if err != nil {
			return fmt.Errorf("error reading 'start_minute': %w", err)
		}
		delete(object, "start_minute")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DND to handle AdditionalProperties
func (a DND) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Enabled != nil {
		object["enabled"], err = json.Marshal(a.Enabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enabled': %w", err)
		}
	}

	if a.EndHour != nil {
		object["end_hour"], err = json.Marshal(a.EndHour)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'end_hour': %w", err)
		}
	}

	if a.EndMinute != nil {
		object["end_minute"], err = json.Marshal(a.EndMinute)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'end_minute': %w", err)
		}
	}

	if a.StartHour != nil {
		object["start_hour"], err = json.Marshal(a.StartHour)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'start_hour': %w", err)
		}
	}

	if a.StartMinute != nil {
		object["start_minute"], err = json.Marshal(a.StartMinute)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'start_minute': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Status. Returns the specified
// element and whether it was found
func (a Status) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Status
func (a *Status) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Status to handle AdditionalProperties
func (a *Status) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["adbumper_status"]; found {
		err = json.Unmarshal(raw, &a.AdbumperStatus)
		if err != nil {
			return fmt.Errorf("error reading 'adbumper_status': %w", err)
		}
		delete(object, "adbumper_status")
	}

	if raw, found := object["auto_dust_collection"]; found {
		err = json.Unmarshal(raw, &a.AutoDustCollection)
		if err != nil {
			return fmt.Errorf("error reading 'auto_dust_collection': %w", err)
		}
		delete(object, "auto_dust_collection")
	}

	if raw, found := object["avoid_count"]; found {
		err = json.Unmarshal(raw, &a.AvoidCount)
		if err != nil {
			return fmt.Errorf("error reading 'avoid_count': %w", err)
		}
		delete(object, "avoid_count")
	}

	if raw, found := object["back_type"]; found {
		err = json.Unmarshal(raw, &a.BackType)
		if err != nil {
			return fmt.Errorf("error reading 'back_type': %w", err)
		}
		delete(object, "back_type")
	}

	if raw, found := object["battery"]; found {
		err = json.Unmarshal(raw, &a.Battery)
		if err != nil {
			return fmt.Errorf("error reading 'battery': %w", err)
		}
		delete(object, "battery")
	}

	if raw, found := object["camera_status"]; found {
		err = json.Unmarshal(raw, &a.CameraStatus)
		if err != nil {
			return fmt.Errorf("error reading 'camera_status': %w", err)
		}
		delete(object, "camera_status")
	}

	if raw, found := object["charge_status"]; found {
		err = json.Unmarshal(raw, &a.ChargeStatus)
		if err != nil {
			return fmt.Errorf("error reading 'charge_status': %w", err)
		}
		delete(object, "charge_status")
	}

	if raw, found := object["clean_area"]; found {
		err = json.Unmarshal(raw, &a.CleanArea)
		if err != nil {
			return fmt.Errorf("error reading 'clean_area': %w", err)
		}
		delete(object, "clean_area")
	}

	if raw, found := object["clean_percent"]; found {
		err = json.Unmarshal(raw, &a.CleanPercent)
		if err != nil {
			return fmt.Errorf("error reading 'clean_percent': %w", err)
		}
		delete(object, "clean_percent")
	}

	if raw, found := object["clean_time"]; found {
		err = json.Unmarshal(raw, &a.CleanTime)
		if err != nil {
			return fmt.Errorf("error reading 'clean_time': %w", err)
		}
		delete(object, "clean_time")
	}

	if raw, found := object["collision_avoid_status"]; found {
		err = json.Unmarshal(raw, &a.CollisionAvoidStatus)
		if err != nil {
			return fmt.Errorf("error reading 'collision_avoid_status': %w", err)
		}
		delete(object, "collision_avoid_status")
	}

	if raw, found := object["common_status"]; found {
		err = json.Unmarshal(raw, &a.CommonStatus)
		if err != nil {
			return fmt.Errorf("error reading 'common_status': %w", err)
		}
		delete(object, "common_status")
	}

	if raw, found := object["corner_clean_mode"]; found {
		err = json.Unmarshal(raw, &a.CornerCleanMode)
		if err != nil {
			return fmt.Errorf("error reading 'corner_clean_mode': %w", err)
		}
		delete(object, "corner_clean_mode")
	}

	if raw, found := object["debug_mode"]; found {
		err = json.Unmarshal(raw, &a.DebugMode)
		if err != nil {
			return fmt.Errorf("error reading 'debug_mode': %w", err)
		}
		delete(object, "debug_mode")
	}

	if raw, found := object["distance_off"]; found {
		err = json.Unmarshal(raw, &a.DistanceOff)
		if err != nil {
			return fmt.Errorf("error reading 'distance_off': %w", err)
		}
		delete(object, "distance_off")
	}

	if raw, found := object["dnd_enabled"]; found {
		err = json.Unmarshal(raw, &a.DndEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'dnd_enabled': %w", err)
		}
		delete(object, "dnd_enabled")
	}

	if raw, found := object["dock_error_status"]; found {
		err = json.Unmarshal(raw, &a.DockErrorStatus)
		if err != nil {
			return fmt.Errorf("error reading 'dock_error_status': %w", err)
		}
		delete(object, "dock_error_status")
	}

	if raw, found := object["dock_type"]; found {
		err = json.Unmarshal(raw, &a.DockType)
		if err != nil {
			return fmt.Errorf("error reading 'dock_type': %w", err)
		}
		delete(object, "dock_type")
	}

	if raw, found := object["dry_status"]; found {
		err = json.Unmarshal(raw, &a.DryStatus)
		if err != nil {
			return fmt.Errorf("error reading 'dry_status': %w", err)
		}
		delete(object, "dry_status")
	}

	if raw, found := object["dss"]; found {
		err = json.Unmarshal(raw, &a.Dss)
		if err != nil {
			return fmt.Errorf("error reading 'dss': %w", err)
		}
		delete(object, "dss")
	}

	if raw, found := object["dust_collection_status"]; found {
		err = json.Unmarshal(raw, &a.DustCollectionStatus)
		if err != nil {
			return fmt.Errorf("error reading 'dust_collection_status': %w", err)
		}
		delete(object, "dust_collection_status")
	}

	if raw, found := object["error_code"]; found {
		err = json.Unmarshal(raw, &a.ErrorCode)
		if err != nil {
			return fmt.Errorf("error reading 'error_code': %w", err)
		}
		delete(object, "error_code")
	}

	if raw, found := object["fan_power"]; found {
		err = json.Unmarshal(raw, &a.FanPower)
		if err != nil {
			return fmt.Errorf("error reading 'fan_power': %w", err)
		}
		delete(object, "fan_power")
	}

	if raw, found := object["home_sec_enable_password"]; found {
		err = json.Unmarshal(raw, &a.HomeSecEnablePassword)
		if err != nil {
			return fmt.Errorf("error reading 'home_sec_enable_password': %w", err)
		}
		delete(object, "home_sec_enable_password")
	}

	if raw, found := object["home_sec_status"]; found {
		err = json.Unmarshal(raw, &a.HomeSecStatus)
		if err != nil {
			return fmt.Errorf("error reading 'home_sec_status': %w", err)
		}
		delete(object, "home_sec_status")
	}

	if raw, found := object["in_cleaning"]; found {
		err = json.Unmarshal(raw, &a.InCleaning)
		if err != nil {
			return fmt.Errorf("error reading 'in_cleaning': %w", err)
		}
		delete(object, "in_cleaning")
	}

	if raw, found := object["in_fresh_state"]; found {
		err = json.Unmarshal(raw, &a.InFreshState)
		if err != nil {
			return fmt.Errorf("error reading 'in_fresh_state': %w", err)
		}
		delete(object, "in_fresh_state")
	}

	if raw, found := object["in_returning"]; found {
		err = json.Unmarshal(raw, &a.InReturning)
		if err != nil {
			return fmt.Errorf("error reading 'in_returning': %w", err)
		}
		delete(object, "in_returning")
	}

	if raw, found := object["in_warmup"]; found {
		err = json.Unmarshal(raw, &a.InWarmup)
		if err != nil {
			return fmt.Errorf("error reading 'in_warmup': %w", err)
		}
		delete(object, "in_warmup")
	}

	if raw, found := object["is_exploring"]; found {
		err = json.Unmarshal(raw, &a.IsExploring)
		if err != nil {
			return fmt.Errorf("error reading 'is_exploring': %w", err)
		}
		delete(object, "is_exploring")
	}

	if raw, found := object["is_locating"]; found {
		err = json.Unmarshal(raw, &a.IsLocating)
		if err != nil {
			return fmt.Errorf("error reading 'is_locating': %w", err)
		}
		delete(object, "is_locating")
	}

	if raw, found := object["kct"]; found {
		err = json.Unmarshal(raw, &a.Kct)
		if err != nil {
			return fmt.Errorf("error reading 'kct': %w", err)
		}
		delete(object, "kct")
	}

	if raw, found := object["lab_status"]; found {
		err = json.Unmarshal(raw, &a.LabStatus)
		if err != nil {
			return fmt.Errorf("error reading 'lab_status': %w", err)
		}
		delete(object, "lab_status")
	}

	if raw, found := object["last_clean_t"]; found {
		err = json.Unmarshal(raw, &a.LastCleanT)
		if err != nil {
			return fmt.Errorf("error reading 'last_clean_t': %w", err)
		}
		delete(object, "last_clean_t")
	}

	if raw, found := object["lock_status"]; found {
		err = json.Unmarshal(raw, &a.LockStatus)
		if err != nil {
			return fmt.Errorf("error reading 'lock_status': %w", err)
		}
		delete(object, "lock_status")
	}

	if raw, found := object["map_present"]; found {
		err = json.Unmarshal(raw, &a.MapPresent)
		if err != nil {
			return fmt.Errorf("error reading 'map_present': %w", err)
		}
		delete(object, "map_present")
	}

	if raw, found := object["map_status"]; found {
		err = json.Unmarshal(raw, &a.MapStatus)
		if err != nil {
			return fmt.Errorf("error reading 'map_status': %w", err)
		}
		delete(object, "map_status")
	}

	if raw, found := object["mop_forbidden_enable"]; found {
		err = json.Unmarshal(raw, &a.MopForbiddenEnable)
		if err != nil {
			return fmt.Errorf("error reading 'mop_forbidden_enable': %w", err)
		}
		delete(object, "mop_forbidden_enable")
	}

	if raw, found := object["mop_mode"]; found {
		err = json.Unmarshal(raw, &a.MopMode)
		if err != nil {
			return fmt.Errorf("error reading 'mop_mode': %w", err)
		}
		delete(object, "mop_mode")
	}

	if raw, found := object["msg_seq"]; found {
		err = json.Unmarshal(raw, &a.MsgSeq)
		if err != nil {
			return fmt.Errorf("error reading 'msg_seq': %w", err)
		}
		delete(object, "msg_seq")
	}

	if raw, found := object["msg_ver"]; found {
		err = json.Unmarshal(raw, &a.MsgVer)
		if err != nil {
			return fmt.Errorf("error reading 'msg_ver': %w", err)
		}
		delete(object, "msg_ver")
	}

	if raw, found := object["rdt"]; found {
		err = json.Unmarshal(raw, &a.Rdt)
		if err != nil {
			return fmt.Errorf("error reading 'rdt': %w", err)
		}
		delete(object, "rdt")
	}

	if raw, found := object["repeat"]; found {
		err = json.Unmarshal(raw, &a.Repeat)
		if err != nil {
			return fmt.Errorf("error reading 'repeat': %w", err)
		}
		delete(object, "repeat")
	}

	if raw, found := object["replenish_mode"]; found {
		err = json.Unmarshal(raw, &a.ReplenishMode)
		if err != nil {
			return fmt.Errorf("error reading 'replenish_mode': %w", err)
		}
		delete(object, "replenish_mode")
	}

	if raw, found := object["rss"]; found {
		err = json.Unmarshal(raw, &a.Rss)
		if err != nil {
			return fmt.Errorf("error reading 'rss': %w", err)
		}
		delete(object, "rss")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["subdivision_sets"]; found {
		err = json.Unmarshal(raw, &a.SubdivisionSets)
		if err != nil {
			return fmt.Errorf("error reading 'subdivision_sets': %w", err)
		}
		delete(object, "subdivision_sets")
	}

	if raw, found := object["switch_map_mode"]; found {
		err = json.Unmarshal(raw, &a.SwitchMapMode)
		if err != nil {
			return fmt.Errorf("error reading 'switch_map_mode': %w", err)
		}
		delete(object, "switch_map_mode")
	}

	if raw, found := object["unsave_map_flag"]; found {
		err = json.Unmarshal(raw, &a.UnsaveMapFlag)
		if err != nil {
			return fmt.Errorf("error reading 'unsave_map_flag': %w", err)
		}
		delete(object, "unsave_map_flag")
	}

	if raw, found := object["unsave_map_reason"]; found {
		err = json.Unmarshal(raw, &a.UnsaveMapReason)
		if err != nil {
			return fmt.Errorf("error reading 'unsave_map_reason': %w", err)
		}
		delete(object, "unsave_map_reason")
	}

	if raw, found := object["wash_phase"]; found {
		err = json.Unmarshal(raw, &a.WashPhase)
		if err != nil {
			return fmt.Errorf("error reading 'wash_phase': %w", err)
		}
		delete(object, "wash_phase")
	}

	if raw, found := object["wash_ready"]; found {
		err = json.Unmarshal(raw, &a.WashReady)
		if err != nil {
			return fmt.Errorf("error reading 'wash_ready': %w", err)
		}
		delete(object, "wash_ready")
	}

	if raw, found := object["wash_status"]; found {
		err = json.Unmarshal(raw, &a.WashStatus)
		if err != nil {
			return fmt.Errorf("error reading 'wash_status': %w", err)
		}
		delete(object, "wash_status")
	}

	if raw, found := object["water_box_carriage_status"]; found {
		err = json.Unmarshal(raw, &a.WaterBoxCarriageStatus)
		if err != nil {
			return fmt.Errorf("error reading 'water_box_carriage_status': %w", err)
		}
		delete(object, "water_box_carriage_status")
	}

	if raw, found := object["water_box_mode"]; found {
		err = json.Unmarshal(raw, &a.WaterBoxMode)
		if err != nil {
			return fmt.Errorf("error reading 'water_box_mode': %w", err)
		}
		delete(object, "water_box_mode")
	}

	if raw, found := object["water_box_status"]; found {
		err = json.Unmarshal(raw, &a.WaterBoxStatus)
		if err != nil {
			return fmt.Errorf("error reading 'water_box_status': %w", err)
		}
		delete(object, "water_box_status")
	}

	if raw, found := object["water_shortage_status"]; found {
		err = json.Unmarshal(raw, &a.WaterShortageStatus)
		if err != nil {
			return fmt.Errorf("error reading 'water_shortage_status': %w", err)
		}
		delete(object, "water_shortage_status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Status to handle AdditionalProperties
func (a Status) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AdbumperStatus != nil {
		object["adbumper_status"], err = json.Marshal(a.AdbumperStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'adbumper_status': %w", err)
		}
	}

	if a.AutoDustCollection != nil {
		object["auto_dust_collection"], err = json.Marshal(a.AutoDustCollection)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'auto_dust_collection': %w", err)
		}
	}

	if a.AvoidCount != nil {
		object["avoid_count"], err = json.Marshal(a.AvoidCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'avoid_count': %w", err)
		}
	}

	if a.BackType != nil {
		object["back_type"], err = json.Marshal(a.BackType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'back_type': %w", err)
		}
	}

	if a.Battery != nil {
		object["battery"], err = json.Marshal(a.Battery)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'battery': %w", err)
		}
	}

	if a.CameraStatus != nil {
		object["camera_status"], err = json.Marshal(a.CameraStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'camera_status': %w", err)
		}
	}

	if a.ChargeStatus != nil {
		object["charge_status"], err = json.Marshal(a.ChargeStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'charge_status': %w", err)
		}
	}

	if a.CleanArea != nil {
		object["clean_area"], err = json.Marshal(a.CleanArea)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_area': %w", err)
		}
	}

	if a.CleanPercent != nil {
		object["clean_percent"], err = json.Marshal(a.CleanPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_percent': %w", err)
		}
	}

	if a.CleanTime != nil {
		object["clean_time"], err = json.Marshal(a.CleanTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clean_time': %w", err)
		}
	}

	if a.CollisionAvoidStatus != nil {
		object["collision_avoid_status"], err = json.Marshal(a.CollisionAvoidStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'collision_avoid_status': %w", err)
		}
	}

	if a.CommonStatus != nil {
		object["common_status"], err = json.Marshal(a.CommonStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'common_status': %w", err)
		}
	}

	if a.CornerCleanMode != nil {
		object["corner_clean_mode"], err = json.Marshal(a.CornerCleanMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'corner_clean_mode': %w", err)
		}
	}

	if a.DebugMode != nil {
		object["debug_mode"], err = json.Marshal(a.DebugMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'debug_mode': %w", err)
		}
	}

	if a.DistanceOff != nil {
		object["distance_off"], err = json.Marshal(a.DistanceOff)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'distance_off': %w", err)
		}
	}

	if a.DndEnabled != nil {
		object["dnd_enabled"], err = json.Marshal(a.DndEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dnd_enabled': %w", err)
		}
	}

	if a.DockErrorStatus != nil {
		object["dock_error_status"], err = json.Marshal(a.DockErrorStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dock_error_status': %w", err)
		}
	}

	if a.DockType != nil {
		object["dock_type"], err = json.Marshal(a.DockType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dock_type': %w", err)
		}
	}

	if a.DryStatus != nil {
		object["dry_status"], err = json.Marshal(a.DryStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dry_status': %w", err)
		}
	}

	if a.Dss != nil {
		object["dss"], err = json.Marshal(a.Dss)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dss': %w", err)
		}
	}

	if a.DustCollectionStatus != nil {
		object["dust_collection_status"], err = json.Marshal(a.DustCollectionStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dust_collection_status': %w", err)
		}
	}

	if a.ErrorCode != nil {
		object["error_code"], err = json.Marshal(a.ErrorCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'error_code': %w", err)
		}
	}

	if a.FanPower != nil {
		object["fan_power"], err = json.Marshal(a.FanPower)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fan_power': %w", err)
		}
	}

	if a.HomeSecEnablePassword != nil {
		object["home_sec_enable_password"], err = json.Marshal(a.HomeSecEnablePassword)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'home_sec_enable_password': %w", err)
		}
	}

	if a.HomeSecStatus != nil {
		object["home_sec_status"], err = json.Marshal(a.HomeSecStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'home_sec_status': %w", err)
		}
	}

	if a.InCleaning != nil {
		object["in_cleaning"], err = json.Marshal(a.InCleaning)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'in_cleaning': %w", err)
		}
	}

	if a.InFreshState != nil {
		object["in_fresh_state"], err = json.Marshal(a.InFreshState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'in_fresh_state': %w", err)
		}
	}

	if a.InReturning != nil {
		object["in_returning"], err = json.Marshal(a.InReturning)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'in_returning': %w", err)
		}
	}

	if a.InWarmup != nil {
		object["in_warmup"], err = json.Marshal(a.InWarmup)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'in_warmup': %w", err)
		}
	}

	if a.IsExploring != nil {
		object["is_exploring"], err = json.Marshal(a.IsExploring)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_exploring': %w", err)
		}
	}

	if a.IsLocating != nil {
		object["is_locating"], err = json.Marshal(a.IsLocating)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_locating': %w", err)
		}
	}

	if a.Kct != nil {
		object["kct"], err = json.Marshal(a.Kct)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'kct': %w", err)
		}
	}

	if a.LabStatus != nil {
		object["lab_status"], err = json.Marshal(a.LabStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lab_status': %w", err)
		}
	}

	if a.LastCleanT != nil {
		object["last_clean_t"], err = json.Marshal(a.LastCleanT)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_clean_t': %w", err)
		}
	}

	if a.LockStatus != nil {
		object["lock_status"], err = json.Marshal(a.LockStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lock_status': %w", err)
		}
	}

	if a.MapPresent != nil {
		object["map_present"], err = json.Marshal(a.MapPresent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'map_present': %w", err)
		}
	}

	if a.MapStatus != nil {
		object["map_status"], err = json.Marshal(a.MapStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'map_status': %w", err)
		}
	}

	if a.MopForbiddenEnable != nil {
		object["mop_forbidden_enable"], err = json.Marshal(a.MopForbiddenEnable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mop_forbidden_enable': %w", err)
		}
	}

	if a.MopMode != nil {
		object["mop_mode"], err = json.Marshal(a.MopMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mop_mode': %w", err)
		}
	}

	if a.MsgSeq != nil {
		object["msg_seq"], err = json.Marshal(a.MsgSeq)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg_seq': %w", err)
		}
	}

	if a.MsgVer != nil {
		object["msg_ver"], err = json.Marshal(a.MsgVer)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'msg_ver': %w", err)
		}
	}

	if a.Rdt != nil {
		object["rdt"], err = json.Marshal(a.Rdt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rdt': %w", err)
		}
	}

	if a.Repeat != nil {
		object["repeat"], err = json.Marshal(a.Repeat)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'repeat': %w", err)
		}
	}

	if a.ReplenishMode != nil {
		object["replenish_mode"], err = json.Marshal(a.ReplenishMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'replenish_mode': %w", err)
		}
	}

	if a.Rss != nil {
		object["rss"], err = json.Marshal(a.Rss)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rss': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.SubdivisionSets != nil {
		object["subdivision_sets"], err = json.Marshal(a.SubdivisionSets)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subdivision_sets': %w", err)
		}
	}

	if a.SwitchMapMode != nil {
		object["switch_map_mode"], err = json.Marshal(a.SwitchMapMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'switch_map_mode': %w", err)
		}
	}

	if a.UnsaveMapFlag != nil {
		object["unsave_map_flag"], err = json.Marshal(a.UnsaveMapFlag)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'unsave_map_flag': %w", err)
		}
	}

	if a.UnsaveMapReason != nil {
		object["unsave_map_reason"], err = json.Marshal(a.UnsaveMapReason)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'unsave_map_reason': %w", err)
		}
	}

	if a.WashPhase != nil {
		object["wash_phase"], err = json.Marshal(a.WashPhase)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wash_phase': %w", err)
		}
	}

	if a.WashReady != nil {
		object["wash_ready"], err = json.Marshal(a.WashReady)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wash_ready': %w", err)
		}
	}

	if a.WashStatus != nil {
		object["wash_status"], err = json.Marshal(a.WashStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wash_status': %w", err)
		}
	}

	if a.WaterBoxCarriageStatus != nil {
		object["water_box_carriage_status"], err = json.Marshal(a.WaterBoxCarriageStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'water_box_carriage_status': %w", err)
		}
	}

	if a.WaterBoxMode != nil {
		object["water_box_mode"], err = json.Marshal(a.WaterBoxMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'water_box_mode': %w", err)
		}
	}

	if a.WaterBoxStatus != nil {
		object["water_box_status"], err = json.Marshal(a.WaterBoxStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'water_box_status': %w", err)
		}
	}

	if a.WaterShortageStatus != nil {
		object["water_shortage_status"], err = json.Marshal(a.WaterShortageStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'water_shortage_status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsCleanRecord returns the union data inside the CleanRecordParts_Item as a CleanRecord
func (t CleanRecordParts_Item) AsCleanRecord() (CleanRecord, error) {
	var body CleanRecord
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanRecord overwrites any union data inside the CleanRecordParts_Item as the provided CleanRecord
func (t *CleanRecordParts_Item) FromCleanRecord(v CleanRecord) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanRecord performs a merge with any union data inside the CleanRecordParts_Item, using the provided CleanRecord
func (t *CleanRecordParts_Item) MergeCleanRecord(v CleanRecord) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleanRecordLegacy returns the union data inside the CleanRecordParts_Item as a CleanRecordLegacy
func (t CleanRecordParts_Item) AsCleanRecordLegacy() (CleanRecordLegacy, error) {
	var body CleanRecordLegacy
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanRecordLegacy overwrites any union data inside the CleanRecordParts_Item as the provided CleanRecordLegacy
func (t *CleanRecordParts_Item) FromCleanRecordLegacy(v CleanRecordLegacy) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanRecordLegacy performs a merge with any union data inside the CleanRecordParts_Item, using the provided CleanRecordLegacy
func (t *CleanRecordParts_Item) MergeCleanRecordLegacy(v CleanRecordLegacy) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CleanRecordParts_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CleanRecordParts_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCleanRecord returns the union data inside the CleanRecordRPCResult as a CleanRecord
func (t CleanRecordRPCResult) AsCleanRecord() (CleanRecord, error) {
	var body CleanRecord
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanRecord overwrites any union data inside the CleanRecordRPCResult as the provided CleanRecord
func (t *CleanRecordRPCResult) FromCleanRecord(v CleanRecord) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanRecord performs a merge with any union data inside the CleanRecordRPCResult, using the provided CleanRecord
func (t *CleanRecordRPCResult) MergeCleanRecord(v CleanRecord) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleanRecordLegacy returns the union data inside the CleanRecordRPCResult as a CleanRecordLegacy
func (t CleanRecordRPCResult) AsCleanRecordLegacy() (CleanRecordLegacy, error) {
	var body CleanRecordLegacy
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanRecordLegacy overwrites any union data inside the CleanRecordRPCResult as the provided CleanRecordLegacy
func (t *CleanRecordRPCResult) FromCleanRecordLegacy(v CleanRecordLegacy) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanRecordLegacy performs a merge with any union data inside the CleanRecordRPCResult, using the provided CleanRecordLegacy
func (t *CleanRecordRPCResult) MergeCleanRecordLegacy(v CleanRecordLegacy) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleanRecordParts returns the union data inside the CleanRecordRPCResult as a CleanRecordParts
func (t CleanRecordRPCResult) AsCleanRecordParts() (CleanRecordParts, error) {
	var body CleanRecordParts
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleanRecordParts overwrites any union data inside the CleanRecordRPCResult as the provided CleanRecordParts
func (t *CleanRecordRPCResult) FromCleanRecordParts(v CleanRecordParts) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleanRecordParts performs a merge with any union data inside the CleanRecordRPCResult, using the provided CleanRecordParts
func (t *CleanRecordRPCResult) MergeCleanRecordParts(v CleanRecordParts) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CleanRecordRPCResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CleanRecordRPCResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCleaningSummary returns the union data inside the CleaningSummaryRPCResult as a CleaningSummary
func (t CleaningSummaryRPCResult) AsCleaningSummary() (CleaningSummary, error) {
	var body CleaningSummary
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleaningSummary overwrites any union data inside the CleaningSummaryRPCResult as the provided CleaningSummary
func (t *CleaningSummaryRPCResult) FromCleaningSummary(v CleaningSummary) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleaningSummary performs a merge with any union data inside the CleaningSummaryRPCResult, using the provided CleaningSummary
func (t *CleaningSummaryRPCResult) MergeCleaningSummary(v CleaningSummary) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleaningSummaryDuration returns the union data inside the CleaningSummaryRPCResult as a CleaningSummaryDuration
func (t CleaningSummaryRPCResult) AsCleaningSummaryDuration() (CleaningSummaryDuration, error) {
	var body CleaningSummaryDuration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleaningSummaryDuration overwrites any union data inside the CleaningSummaryRPCResult as the provided CleaningSummaryDuration
func (t *CleaningSummaryRPCResult) FromCleaningSummaryDuration(v CleaningSummaryDuration) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleaningSummaryDuration performs a merge with any union data inside the CleaningSummaryRPCResult, using the provided CleaningSummaryDuration
func (t *CleaningSummaryRPCResult) MergeCleaningSummaryDuration(v CleaningSummaryDuration) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleaningSummaryLegacy returns the union data inside the CleaningSummaryRPCResult as a CleaningSummaryLegacy
func (t CleaningSummaryRPCResult) AsCleaningSummaryLegacy() (CleaningSummaryLegacy, error) {
	var body CleaningSummaryLegacy
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleaningSummaryLegacy overwrites any union data inside the CleaningSummaryRPCResult as the provided CleaningSummaryLegacy
func (t *CleaningSummaryRPCResult) FromCleaningSummaryLegacy(v CleaningSummaryLegacy) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleaningSummaryLegacy performs a merge with any union data inside the CleaningSummaryRPCResult, using the provided CleaningSummaryLegacy
func (t *CleaningSummaryRPCResult) MergeCleaningSummaryLegacy(v CleaningSummaryLegacy) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCleaningSummarySingletonResult returns the union data inside the CleaningSummaryRPCResult as a CleaningSummarySingletonResult
func (t CleaningSummaryRPCResult) AsCleaningSummarySingletonResult() (CleaningSummarySingletonResult, error) {
	var body CleaningSummarySingletonResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCleaningSummarySingletonResult overwrites any union data inside the CleaningSummaryRPCResult as the provided CleaningSummarySingletonResult
func (t *CleaningSummaryRPCResult) FromCleaningSummarySingletonResult(v CleaningSummarySingletonResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCleaningSummarySingletonResult performs a merge with any union data inside the CleaningSummaryRPCResult, using the provided CleaningSummarySingletonResult
func (t *CleaningSummaryRPCResult) MergeCleaningSummarySingletonResult(v CleaningSummarySingletonResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CleaningSummaryRPCResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CleaningSummaryRPCResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsConsumables returns the union data inside the ConsumablesRPCResult as a Consumables
func (t ConsumablesRPCResult) AsConsumables() (Consumables, error) {
	var body Consumables
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConsumables overwrites any union data inside the ConsumablesRPCResult as the provided Consumables
func (t *ConsumablesRPCResult) FromConsumables(v Consumables) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConsumables performs a merge with any union data inside the ConsumablesRPCResult, using the provided Consumables
func (t *ConsumablesRPCResult) MergeConsumables(v Consumables) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConsumablesSingletonResult returns the union data inside the ConsumablesRPCResult as a ConsumablesSingletonResult
func (t ConsumablesRPCResult) AsConsumablesSingletonResult() (ConsumablesSingletonResult, error) {
	var body ConsumablesSingletonResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConsumablesSingletonResult overwrites any union data inside the ConsumablesRPCResult as the provided ConsumablesSingletonResult
func (t *ConsumablesRPCResult) FromConsumablesSingletonResult(v ConsumablesSingletonResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConsumablesSingletonResult performs a merge with any union data inside the ConsumablesRPCResult, using the provided ConsumablesSingletonResult
func (t *ConsumablesRPCResult) MergeConsumablesSingletonResult(v ConsumablesSingletonResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ConsumablesRPCResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ConsumablesRPCResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsDND returns the union data inside the DNDRPCResult as a DND
func (t DNDRPCResult) AsDND() (DND, error) {
	var body DND
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDND overwrites any union data inside the DNDRPCResult as the provided DND
func (t *DNDRPCResult) FromDND(v DND) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDND performs a merge with any union data inside the DNDRPCResult, using the provided DND
func (t *DNDRPCResult) MergeDND(v DND) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDNDSingletonResult returns the union data inside the DNDRPCResult as a DNDSingletonResult
func (t DNDRPCResult) AsDNDSingletonResult() (DNDSingletonResult, error) {
	var body DNDSingletonResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDNDSingletonResult overwrites any union data inside the DNDRPCResult as the provided DNDSingletonResult
func (t *DNDRPCResult) FromDNDSingletonResult(v DNDSingletonResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDNDSingletonResult performs a merge with any union data inside the DNDRPCResult, using the provided DNDSingletonResult
func (t *DNDRPCResult) MergeDNDSingletonResult(v DNDSingletonResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DNDRPCResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DNDRPCResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStatus returns the union data inside the StatusRPCResult as a Status
func (t StatusRPCResult) AsStatus() (Status, error) {
	var body Status
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatus overwrites any union data inside the StatusRPCResult as the provided Status
func (t *StatusRPCResult) FromStatus(v Status) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatus performs a merge with any union data inside the StatusRPCResult, using the provided Status
func (t *StatusRPCResult) MergeStatus(v Status) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStatusSingletonResult returns the union data inside the StatusRPCResult as a StatusSingletonResult
func (t StatusRPCResult) AsStatusSingletonResult() (StatusSingletonResult, error) {
	var body StatusSingletonResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusSingletonResult overwrites any union data inside the StatusRPCResult as the provided StatusSingletonResult
func (t *StatusRPCResult) FromStatusSingletonResult(v StatusSingletonResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusSingletonResult performs a merge with any union data inside the StatusRPCResult, using the provided StatusSingletonResult
func (t *StatusRPCResult) MergeStatusSingletonResult(v StatusSingletonResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StatusRPCResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StatusRPCResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
