// Code generated by tools/generate from schema x-known-values; DO NOT EDIT.
package mapmodel

const (
	MapAreaKindCurrent   MapAreaKind = "current"
	MapAreaKindErase     MapAreaKind = "erase"
	MapAreaKindNoCarpet  MapAreaKind = "no-carpet"
	MapAreaKindNoGo      MapAreaKind = "no-go"
	MapAreaKindNoMop     MapAreaKind = "no-mop"
	MapAreaKindUnknown   MapAreaKind = "unknown"
	MapAreaKindWall      MapAreaKind = "wall"
	MapPathKindClean     MapPathKind = "clean"
	MapPathKindGoto      MapPathKind = "goto"
	MapPathKindPredicted MapPathKind = "predicted"
	MapPathKindTrace     MapPathKind = "trace"
)
