// Package mapmodel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package mapmodel

// Defines values for MapFormat.
const (
	MapFormatQ10 MapFormat = "b01-q10"
	MapFormatQ7  MapFormat = "b01-q7"
	MapFormatV1  MapFormat = "v1"
)

// Defines values for MapFrame.
const (
	MapFrameQ10Array MapFrame = "q10-array"
	MapFrameQ10Trace MapFrame = "q10-trace"
	MapFrameQ10World MapFrame = "q10-world"
	MapFrameQ7World  MapFrame = "q7-world"
	MapFrameV1World  MapFrame = "v1-world"
)

// Defines values for MapGridRowYDirection.
const (
	Minus1 MapGridRowYDirection = -1
	N1     MapGridRowYDirection = 1
)

// Defines values for MapPoseHeadingUnit.
const (
	Degrees MapPoseHeadingUnit = "degrees"
	Radians MapPoseHeadingUnit = "radians"
)

// Defines values for MapUnit.
const (
	MapUnitMeters      MapUnit = "meters"
	MapUnitMillimeters MapUnit = "millimeters"
	MapUnitPixels      MapUnit = "pixels"
)

// MapArea defines model for MapArea.
type MapArea struct {
	// Frame Q10 trace is dock-relative; Q10 array is absolute raster coordinates; these frames must not be combined without explicit calibration.
	Frame MapFrame `json:"frame"`

	// Kind Known source restriction name, or unknown when semantics are not verified.
	Kind         string     `json:"kind"`
	Points       []MapPoint `json:"points"`
	SourceIndex  *int64     `json:"sourceIndex,omitempty"`
	SourceStatus *int64     `json:"sourceStatus,omitempty"`

	// SourceType Uninterpreted source area type when present.
	SourceType *int64  `json:"sourceType,omitempty"`
	Unit       MapUnit `json:"unit"`
}

// MapFormat defines model for MapFormat.
type MapFormat string

// MapFrame Q10 trace is dock-relative; Q10 array is absolute raster coordinates; these frames must not be combined without explicit calibration.
type MapFrame string

// MapGrid defines model for MapGrid.
type MapGrid struct {
	// Cells Row-major source occupancy bytes; cell semantics depend on format.
	Cells []byte `json:"cells"`

	// Frame Q10 trace is dock-relative; Q10 array is absolute raster coordinates; these frames must not be combined without explicit calibration.
	Frame MapFrame `json:"frame"`

	// Height Number of rows.
	Height int       `json:"height"`
	Origin *MapPoint `json:"origin,omitempty"`

	// Resolution Source world units per cell; absent when calibration is unavailable.
	Resolution *float64 `json:"resolution,omitempty"`

	// RoomCells Optional source room-assignment raster.
	RoomCells *[]byte `json:"roomCells,omitempty"`

	// RowYDirection Sign of source-world Y change as the stored raster row increases.
	RowYDirection MapGridRowYDirection `json:"rowYDirection"`

	// TopDown True when row zero corresponds to the top of the displayed raster.
	TopDown bool    `json:"topDown"`
	Unit    MapUnit `json:"unit"`

	// Width Number of columns.
	Width int `json:"width"`
}

// MapGridRowYDirection Sign of source-world Y change as the stored raster row increases.
type MapGridRowYDirection int

// MapPath defines model for MapPath.
type MapPath struct {
	// Frame Q10 trace is dock-relative; Q10 array is absolute raster coordinates; these frames must not be combined without explicit calibration.
	Frame MapFrame `json:"frame"`

	// Kind Source path kind; clean, goto, predicted or trace.
	Kind   string     `json:"kind"`
	Points []MapPoint `json:"points"`
	Unit   MapUnit    `json:"unit"`
}

// MapPoint defines model for MapPoint.
type MapPoint struct {
	// X Horizontal coordinate in the containing geometry unit and frame.
	X float64 `json:"x"`

	// Y Vertical coordinate in the containing geometry unit and frame.
	Y float64 `json:"y"`
}

// MapPose defines model for MapPose.
type MapPose struct {
	// Frame Q10 trace is dock-relative; Q10 array is absolute raster coordinates; these frames must not be combined without explicit calibration.
	Frame MapFrame `json:"frame"`

	// Heading Source heading; headingUnit identifies degrees or radians.
	Heading     *float64            `json:"heading,omitempty"`
	HeadingUnit *MapPoseHeadingUnit `json:"headingUnit,omitempty"`
	Point       MapPoint            `json:"point"`
	Unit        MapUnit             `json:"unit"`
}

// MapPoseHeadingUnit defines model for MapPose.HeadingUnit.
type MapPoseHeadingUnit string

// MapRectangle defines model for MapRectangle.
type MapRectangle struct {
	Max MapPoint `json:"max"`
	Min MapPoint `json:"min"`
}

// MapRoom defines model for MapRoom.
type MapRoom struct {
	Bounds     *MapRectangle `json:"bounds,omitempty"`
	CleanState *int64        `json:"cleanState,omitempty"`

	// Frame Q10 trace is dock-relative; Q10 array is absolute raster coordinates; these frames must not be combined without explicit calibration.
	Frame MapFrame `json:"frame"`

	// Id Source room identifier; absent remains absent.
	Id       *int64      `json:"id,omitempty"`
	Label    *MapPoint   `json:"label,omitempty"`
	Material *int64      `json:"material,omitempty"`
	Name     *string     `json:"name,omitempty"`
	Outline  *[]MapPoint `json:"outline,omitempty"`
	RoomType *int64      `json:"roomType,omitempty"`
	Unit     MapUnit     `json:"unit"`
}

// MapSnapshot defines model for MapSnapshot.
type MapSnapshot struct {
	CurrentZones []MapArea `json:"currentZones"`
	Dock         *MapPose  `json:"dock,omitempty"`
	Format       MapFormat `json:"format"`

	// FormatId Source map-type or packet-kind identifier; never inferred when absent.
	FormatId      *int64            `json:"formatId,omitempty"`
	Grid          *MapGrid          `json:"grid,omitempty"`
	MapId         *int64            `json:"mapId,omitempty"`
	Paths         []MapPath         `json:"paths"`
	Restrictions  []MapArea         `json:"restrictions"`
	Robot         *MapPose          `json:"robot,omitempty"`
	Rooms         []MapRoom         `json:"rooms"`
	UnknownBlocks []MapUnknownBlock `json:"unknownBlocks"`
	Walls         []MapArea         `json:"walls"`
}

// MapUnit defines model for MapUnit.
type MapUnit string

// MapUnknownBlock defines model for MapUnknownBlock.
type MapUnknownBlock struct {
	DataLength   int   `json:"dataLength"`
	HeaderLength int   `json:"headerLength"`
	Offset       int   `json:"offset"`
	Type         int64 `json:"type"`
}
