// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/external/b01_scmap.proto

package mapproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevicePointInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePointInfo) Reset() {
	*x = DevicePointInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePointInfo) ProtoMessage() {}

func (x *DevicePointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePointInfo.ProtoReflect.Descriptor instead.
func (*DevicePointInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{0}
}

func (x *DevicePointInfo) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *DevicePointInfo) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type MapBoundaryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapMd5        *string                `protobuf:"bytes,1,opt,name=mapMd5" json:"mapMd5,omitempty"`
	VMinX         *uint32                `protobuf:"varint,2,opt,name=vMinX" json:"vMinX,omitempty"`
	VMaxX         *uint32                `protobuf:"varint,3,opt,name=vMaxX" json:"vMaxX,omitempty"`
	VMinY         *uint32                `protobuf:"varint,4,opt,name=vMinY" json:"vMinY,omitempty"`
	VMaxY         *uint32                `protobuf:"varint,5,opt,name=vMaxY" json:"vMaxY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapBoundaryInfo) Reset() {
	*x = MapBoundaryInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapBoundaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapBoundaryInfo) ProtoMessage() {}

func (x *MapBoundaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapBoundaryInfo.ProtoReflect.Descriptor instead.
func (*MapBoundaryInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{1}
}

func (x *MapBoundaryInfo) GetMapMd5() string {
	if x != nil && x.MapMd5 != nil {
		return *x.MapMd5
	}
	return ""
}

func (x *MapBoundaryInfo) GetVMinX() uint32 {
	if x != nil && x.VMinX != nil {
		return *x.VMinX
	}
	return 0
}

func (x *MapBoundaryInfo) GetVMaxX() uint32 {
	if x != nil && x.VMaxX != nil {
		return *x.VMaxX
	}
	return 0
}

func (x *MapBoundaryInfo) GetVMinY() uint32 {
	if x != nil && x.VMinY != nil {
		return *x.VMinY
	}
	return 0
}

func (x *MapBoundaryInfo) GetVMaxY() uint32 {
	if x != nil && x.VMaxY != nil {
		return *x.VMaxY
	}
	return 0
}

type MapExtInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskBeginDate *uint32                `protobuf:"varint,1,opt,name=taskBeginDate" json:"taskBeginDate,omitempty"`
	MapUploadDate *uint32                `protobuf:"varint,2,opt,name=mapUploadDate" json:"mapUploadDate,omitempty"`
	MapValid      *uint32                `protobuf:"varint,3,opt,name=mapValid" json:"mapValid,omitempty"`
	Radian        *uint32                `protobuf:"varint,4,opt,name=radian" json:"radian,omitempty"`
	Force         *uint32                `protobuf:"varint,5,opt,name=force" json:"force,omitempty"`
	CleanPath     *uint32                `protobuf:"varint,6,opt,name=cleanPath" json:"cleanPath,omitempty"`
	BoudaryInfo   *MapBoundaryInfo       `protobuf:"bytes,7,opt,name=boudaryInfo" json:"boudaryInfo,omitempty"`
	MapVersion    *uint32                `protobuf:"varint,8,opt,name=mapVersion" json:"mapVersion,omitempty"`
	MapValueType  *uint32                `protobuf:"varint,9,opt,name=mapValueType" json:"mapValueType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapExtInfo) Reset() {
	*x = MapExtInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapExtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapExtInfo) ProtoMessage() {}

func (x *MapExtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapExtInfo.ProtoReflect.Descriptor instead.
func (*MapExtInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{2}
}

func (x *MapExtInfo) GetTaskBeginDate() uint32 {
	if x != nil && x.TaskBeginDate != nil {
		return *x.TaskBeginDate
	}
	return 0
}

func (x *MapExtInfo) GetMapUploadDate() uint32 {
	if x != nil && x.MapUploadDate != nil {
		return *x.MapUploadDate
	}
	return 0
}

func (x *MapExtInfo) GetMapValid() uint32 {
	if x != nil && x.MapValid != nil {
		return *x.MapValid
	}
	return 0
}

func (x *MapExtInfo) GetRadian() uint32 {
	if x != nil && x.Radian != nil {
		return *x.Radian
	}
	return 0
}

func (x *MapExtInfo) GetForce() uint32 {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return 0
}

func (x *MapExtInfo) GetCleanPath() uint32 {
	if x != nil && x.CleanPath != nil {
		return *x.CleanPath
	}
	return 0
}

func (x *MapExtInfo) GetBoudaryInfo() *MapBoundaryInfo {
	if x != nil {
		return x.BoudaryInfo
	}
	return nil
}

func (x *MapExtInfo) GetMapVersion() uint32 {
	if x != nil && x.MapVersion != nil {
		return *x.MapVersion
	}
	return 0
}

func (x *MapExtInfo) GetMapValueType() uint32 {
	if x != nil && x.MapValueType != nil {
		return *x.MapValueType
	}
	return 0
}

type MapHeadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapHeadId     *uint32                `protobuf:"varint,1,opt,name=mapHeadId" json:"mapHeadId,omitempty"`
	SizeX         *uint32                `protobuf:"varint,2,opt,name=sizeX" json:"sizeX,omitempty"`
	SizeY         *uint32                `protobuf:"varint,3,opt,name=sizeY" json:"sizeY,omitempty"`
	MinX          *float32               `protobuf:"fixed32,4,opt,name=minX" json:"minX,omitempty"`
	MinY          *float32               `protobuf:"fixed32,5,opt,name=minY" json:"minY,omitempty"`
	MaxX          *float32               `protobuf:"fixed32,6,opt,name=maxX" json:"maxX,omitempty"`
	MaxY          *float32               `protobuf:"fixed32,7,opt,name=maxY" json:"maxY,omitempty"`
	Resolution    *float32               `protobuf:"fixed32,8,opt,name=resolution" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapHeadInfo) Reset() {
	*x = MapHeadInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapHeadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapHeadInfo) ProtoMessage() {}

func (x *MapHeadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapHeadInfo.ProtoReflect.Descriptor instead.
func (*MapHeadInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{3}
}

func (x *MapHeadInfo) GetMapHeadId() uint32 {
	if x != nil && x.MapHeadId != nil {
		return *x.MapHeadId
	}
	return 0
}

func (x *MapHeadInfo) GetSizeX() uint32 {
	if x != nil && x.SizeX != nil {
		return *x.SizeX
	}
	return 0
}

func (x *MapHeadInfo) GetSizeY() uint32 {
	if x != nil && x.SizeY != nil {
		return *x.SizeY
	}
	return 0
}

func (x *MapHeadInfo) GetMinX() float32 {
	if x != nil && x.MinX != nil {
		return *x.MinX
	}
	return 0
}

func (x *MapHeadInfo) GetMinY() float32 {
	if x != nil && x.MinY != nil {
		return *x.MinY
	}
	return 0
}

func (x *MapHeadInfo) GetMaxX() float32 {
	if x != nil && x.MaxX != nil {
		return *x.MaxX
	}
	return 0
}

func (x *MapHeadInfo) GetMaxY() float32 {
	if x != nil && x.MaxY != nil {
		return *x.MaxY
	}
	return 0
}

func (x *MapHeadInfo) GetResolution() float32 {
	if x != nil && x.Resolution != nil {
		return *x.Resolution
	}
	return 0
}

type MapDataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapData       []byte                 `protobuf:"bytes,1,opt,name=mapData" json:"mapData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDataInfo) Reset() {
	*x = MapDataInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDataInfo) ProtoMessage() {}

func (x *MapDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDataInfo.ProtoReflect.Descriptor instead.
func (*MapDataInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{4}
}

func (x *MapDataInfo) GetMapData() []byte {
	if x != nil {
		return x.MapData
	}
	return nil
}

type MapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         *uint32                `protobuf:"varint,1,opt,name=mapId" json:"mapId,omitempty"`
	MapName       *string                `protobuf:"bytes,2,opt,name=mapName" json:"mapName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInfo) Reset() {
	*x = MapInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo) ProtoMessage() {}

func (x *MapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo.ProtoReflect.Descriptor instead.
func (*MapInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{5}
}

func (x *MapInfo) GetMapId() uint32 {
	if x != nil && x.MapId != nil {
		return *x.MapId
	}
	return 0
}

func (x *MapInfo) GetMapName() string {
	if x != nil && x.MapName != nil {
		return *x.MapName
	}
	return ""
}

type DevicePoseDataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *uint32                `protobuf:"varint,1,opt,name=update" json:"update,omitempty"`
	X             *float32               `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePoseDataInfo) Reset() {
	*x = DevicePoseDataInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePoseDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePoseDataInfo) ProtoMessage() {}

func (x *DevicePoseDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePoseDataInfo.ProtoReflect.Descriptor instead.
func (*DevicePoseDataInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{6}
}

func (x *DevicePoseDataInfo) GetUpdate() uint32 {
	if x != nil && x.Update != nil {
		return *x.Update
	}
	return 0
}

func (x *DevicePoseDataInfo) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *DevicePoseDataInfo) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type DeviceHistoryPoseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoseId        *uint32                `protobuf:"varint,1,opt,name=poseId" json:"poseId,omitempty"`
	Points        []*DevicePoseDataInfo  `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHistoryPoseInfo) Reset() {
	*x = DeviceHistoryPoseInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHistoryPoseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHistoryPoseInfo) ProtoMessage() {}

func (x *DeviceHistoryPoseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHistoryPoseInfo.ProtoReflect.Descriptor instead.
func (*DeviceHistoryPoseInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceHistoryPoseInfo) GetPoseId() uint32 {
	if x != nil && x.PoseId != nil {
		return *x.PoseId
	}
	return 0
}

func (x *DeviceHistoryPoseInfo) GetPoints() []*DevicePoseDataInfo {
	if x != nil {
		return x.Points
	}
	return nil
}

type DevicePoseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Phi           *float32               `protobuf:"fixed32,3,opt,name=phi" json:"phi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePoseInfo) Reset() {
	*x = DevicePoseInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePoseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePoseInfo) ProtoMessage() {}

func (x *DevicePoseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePoseInfo.ProtoReflect.Descriptor instead.
func (*DevicePoseInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{8}
}

func (x *DevicePoseInfo) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *DevicePoseInfo) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *DevicePoseInfo) GetPhi() float32 {
	if x != nil && x.Phi != nil {
		return *x.Phi
	}
	return 0
}

type DeviceCurrentPoseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoseId        *uint32                `protobuf:"varint,1,opt,name=poseId" json:"poseId,omitempty"`
	Update        *uint32                `protobuf:"varint,2,opt,name=update" json:"update,omitempty"`
	X             *float32               `protobuf:"fixed32,3,opt,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,4,opt,name=y" json:"y,omitempty"`
	Phi           *float32               `protobuf:"fixed32,5,opt,name=phi" json:"phi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCurrentPoseInfo) Reset() {
	*x = DeviceCurrentPoseInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCurrentPoseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCurrentPoseInfo) ProtoMessage() {}

func (x *DeviceCurrentPoseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCurrentPoseInfo.ProtoReflect.Descriptor instead.
func (*DeviceCurrentPoseInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceCurrentPoseInfo) GetPoseId() uint32 {
	if x != nil && x.PoseId != nil {
		return *x.PoseId
	}
	return 0
}

func (x *DeviceCurrentPoseInfo) GetUpdate() uint32 {
	if x != nil && x.Update != nil {
		return *x.Update
	}
	return 0
}

func (x *DeviceCurrentPoseInfo) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *DeviceCurrentPoseInfo) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *DeviceCurrentPoseInfo) GetPhi() float32 {
	if x != nil && x.Phi != nil {
		return *x.Phi
	}
	return 0
}

type DeviceAreaDataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *uint32                `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Type          *uint32                `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	AreaIndex     *uint32                `protobuf:"varint,3,opt,name=areaIndex" json:"areaIndex,omitempty"`
	Points        []*DevicePointInfo     `protobuf:"bytes,4,rep,name=points" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAreaDataInfo) Reset() {
	*x = DeviceAreaDataInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAreaDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAreaDataInfo) ProtoMessage() {}

func (x *DeviceAreaDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAreaDataInfo.ProtoReflect.Descriptor instead.
func (*DeviceAreaDataInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceAreaDataInfo) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *DeviceAreaDataInfo) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *DeviceAreaDataInfo) GetAreaIndex() uint32 {
	if x != nil && x.AreaIndex != nil {
		return *x.AreaIndex
	}
	return 0
}

func (x *DeviceAreaDataInfo) GetPoints() []*DevicePointInfo {
	if x != nil {
		return x.Points
	}
	return nil
}

type RoomMatrixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matrix        []byte                 `protobuf:"bytes,1,opt,name=matrix" json:"matrix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMatrixInfo) Reset() {
	*x = RoomMatrixInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMatrixInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMatrixInfo) ProtoMessage() {}

func (x *RoomMatrixInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMatrixInfo.ProtoReflect.Descriptor instead.
func (*RoomMatrixInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{11}
}

func (x *RoomMatrixInfo) GetMatrix() []byte {
	if x != nil {
		return x.Matrix
	}
	return nil
}

type RoomOutlinePointInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *uint32                `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *uint32                `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Value         *uint32                `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOutlinePointInfo) Reset() {
	*x = RoomOutlinePointInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOutlinePointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOutlinePointInfo) ProtoMessage() {}

func (x *RoomOutlinePointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOutlinePointInfo.ProtoReflect.Descriptor instead.
func (*RoomOutlinePointInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{12}
}

func (x *RoomOutlinePointInfo) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *RoomOutlinePointInfo) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *RoomOutlinePointInfo) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type RoomBorderPointInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *uint32                `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *uint32                `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBorderPointInfo) Reset() {
	*x = RoomBorderPointInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBorderPointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBorderPointInfo) ProtoMessage() {}

func (x *RoomBorderPointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBorderPointInfo.ProtoReflect.Descriptor instead.
func (*RoomBorderPointInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{13}
}

func (x *RoomBorderPointInfo) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *RoomBorderPointInfo) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type RoomBorderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*RoomBorderPointInfo `protobuf:"bytes,1,rep,name=points" json:"points,omitempty"`
	RoomIds       []uint32               `protobuf:"varint,2,rep,name=roomIds" json:"roomIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBorderInfo) Reset() {
	*x = RoomBorderInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBorderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBorderInfo) ProtoMessage() {}

func (x *RoomBorderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBorderInfo.ProtoReflect.Descriptor instead.
func (*RoomBorderInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{14}
}

func (x *RoomBorderInfo) GetPoints() []*RoomBorderPointInfo {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *RoomBorderInfo) GetRoomIds() []uint32 {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type RoomOutlineInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RoomId        *uint32                 `protobuf:"varint,1,opt,name=roomId" json:"roomId,omitempty"`
	Points        []*RoomOutlinePointInfo `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
	Borders       []*RoomBorderInfo       `protobuf:"bytes,3,rep,name=borders" json:"borders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOutlineInfo) Reset() {
	*x = RoomOutlineInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOutlineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOutlineInfo) ProtoMessage() {}

func (x *RoomOutlineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOutlineInfo.ProtoReflect.Descriptor instead.
func (*RoomOutlineInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{15}
}

func (x *RoomOutlineInfo) GetRoomId() uint32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *RoomOutlineInfo) GetPoints() []*RoomOutlinePointInfo {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *RoomOutlineInfo) GetBorders() []*RoomBorderInfo {
	if x != nil {
		return x.Borders
	}
	return nil
}

type CarpetDataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarpetId      *uint32                `protobuf:"varint,1,opt,name=carpetId" json:"carpetId,omitempty"`
	Type          *uint32                `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Unknown3      *uint32                `protobuf:"varint,3,opt,name=unknown3" json:"unknown3,omitempty"`
	Points        []*DevicePointInfo     `protobuf:"bytes,4,rep,name=points" json:"points,omitempty"`
	Enabled       *uint32                `protobuf:"varint,6,opt,name=enabled" json:"enabled,omitempty"`
	Unknown7      *uint32                `protobuf:"varint,7,opt,name=unknown7" json:"unknown7,omitempty"`
	Unknown8      *uint32                `protobuf:"varint,8,opt,name=unknown8" json:"unknown8,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarpetDataInfo) Reset() {
	*x = CarpetDataInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarpetDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarpetDataInfo) ProtoMessage() {}

func (x *CarpetDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarpetDataInfo.ProtoReflect.Descriptor instead.
func (*CarpetDataInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{16}
}

func (x *CarpetDataInfo) GetCarpetId() uint32 {
	if x != nil && x.CarpetId != nil {
		return *x.CarpetId
	}
	return 0
}

func (x *CarpetDataInfo) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CarpetDataInfo) GetUnknown3() uint32 {
	if x != nil && x.Unknown3 != nil {
		return *x.Unknown3
	}
	return 0
}

func (x *CarpetDataInfo) GetPoints() []*DevicePointInfo {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *CarpetDataInfo) GetEnabled() uint32 {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return 0
}

func (x *CarpetDataInfo) GetUnknown7() uint32 {
	if x != nil && x.Unknown7 != nil {
		return *x.Unknown7
	}
	return 0
}

func (x *CarpetDataInfo) GetUnknown8() uint32 {
	if x != nil && x.Unknown8 != nil {
		return *x.Unknown8
	}
	return 0
}

type RoomDataInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         *uint32                `protobuf:"varint,1,opt,name=roomId" json:"roomId,omitempty"`
	RoomName       *string                `protobuf:"bytes,2,opt,name=roomName" json:"roomName,omitempty"`
	RoomTypeId     *uint32                `protobuf:"varint,3,opt,name=roomTypeId" json:"roomTypeId,omitempty"`
	MeterialId     *uint32                `protobuf:"varint,4,opt,name=meterialId" json:"meterialId,omitempty"`
	CleanState     *uint32                `protobuf:"varint,5,opt,name=cleanState" json:"cleanState,omitempty"`
	RoomClean      *uint32                `protobuf:"varint,6,opt,name=roomClean" json:"roomClean,omitempty"`
	RoomCleanIndex *uint32                `protobuf:"varint,7,opt,name=roomCleanIndex" json:"roomCleanIndex,omitempty"`
	RoomNamePost   *DevicePointInfo       `protobuf:"bytes,8,opt,name=roomNamePost" json:"roomNamePost,omitempty"`
	ColorId        *uint32                `protobuf:"varint,10,opt,name=colorId" json:"colorId,omitempty"`
	FloorDirection *uint32                `protobuf:"varint,11,opt,name=floor_direction,json=floorDirection" json:"floor_direction,omitempty"`
	GlobalSeq      *uint32                `protobuf:"varint,12,opt,name=global_seq,json=globalSeq" json:"global_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomDataInfo) Reset() {
	*x = RoomDataInfo{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDataInfo) ProtoMessage() {}

func (x *RoomDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDataInfo.ProtoReflect.Descriptor instead.
func (*RoomDataInfo) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{17}
}

func (x *RoomDataInfo) GetRoomId() uint32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *RoomDataInfo) GetRoomName() string {
	if x != nil && x.RoomName != nil {
		return *x.RoomName
	}
	return ""
}

func (x *RoomDataInfo) GetRoomTypeId() uint32 {
	if x != nil && x.RoomTypeId != nil {
		return *x.RoomTypeId
	}
	return 0
}

func (x *RoomDataInfo) GetMeterialId() uint32 {
	if x != nil && x.MeterialId != nil {
		return *x.MeterialId
	}
	return 0
}

func (x *RoomDataInfo) GetCleanState() uint32 {
	if x != nil && x.CleanState != nil {
		return *x.CleanState
	}
	return 0
}

func (x *RoomDataInfo) GetRoomClean() uint32 {
	if x != nil && x.RoomClean != nil {
		return *x.RoomClean
	}
	return 0
}

func (x *RoomDataInfo) GetRoomCleanIndex() uint32 {
	if x != nil && x.RoomCleanIndex != nil {
		return *x.RoomCleanIndex
	}
	return 0
}

func (x *RoomDataInfo) GetRoomNamePost() *DevicePointInfo {
	if x != nil {
		return x.RoomNamePost
	}
	return nil
}

func (x *RoomDataInfo) GetColorId() uint32 {
	if x != nil && x.ColorId != nil {
		return *x.ColorId
	}
	return 0
}

func (x *RoomDataInfo) GetFloorDirection() uint32 {
	if x != nil && x.FloorDirection != nil {
		return *x.FloorDirection
	}
	return 0
}

func (x *RoomDataInfo) GetGlobalSeq() uint32 {
	if x != nil && x.GlobalSeq != nil {
		return *x.GlobalSeq
	}
	return 0
}

type RobotMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapType       *uint32                `protobuf:"varint,1,opt,name=mapType" json:"mapType,omitempty"`
	MapExtInfo    *MapExtInfo            `protobuf:"bytes,2,opt,name=mapExtInfo" json:"mapExtInfo,omitempty"`
	MapHead       *MapHeadInfo           `protobuf:"bytes,3,opt,name=mapHead" json:"mapHead,omitempty"`
	MapData       *MapDataInfo           `protobuf:"bytes,4,opt,name=mapData" json:"mapData,omitempty"`
	MapInfo       []*MapInfo             `protobuf:"bytes,5,rep,name=mapInfo" json:"mapInfo,omitempty"`
	HistoryPose   *DeviceHistoryPoseInfo `protobuf:"bytes,6,opt,name=historyPose" json:"historyPose,omitempty"`
	ChargeStation *DevicePoseInfo        `protobuf:"bytes,7,opt,name=chargeStation" json:"chargeStation,omitempty"`
	CurrentPose   *DeviceCurrentPoseInfo `protobuf:"bytes,8,opt,name=currentPose" json:"currentPose,omitempty"`
	AreaInfo      []*DeviceAreaDataInfo  `protobuf:"bytes,9,rep,name=areaInfo" json:"areaInfo,omitempty"`
	RoomDataInfo  []*RoomDataInfo        `protobuf:"bytes,12,rep,name=roomDataInfo" json:"roomDataInfo,omitempty"`
	RoomMatrix    *RoomMatrixInfo        `protobuf:"bytes,13,opt,name=roomMatrix" json:"roomMatrix,omitempty"`
	RoomOutline   []*RoomOutlineInfo     `protobuf:"bytes,14,rep,name=roomOutline" json:"roomOutline,omitempty"`
	CarpetInfo    []*CarpetDataInfo      `protobuf:"bytes,20,rep,name=carpetInfo" json:"carpetInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotMap) Reset() {
	*x = RobotMap{}
	mi := &file_api_external_b01_scmap_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotMap) ProtoMessage() {}

func (x *RobotMap) ProtoReflect() protoreflect.Message {
	mi := &file_api_external_b01_scmap_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotMap.ProtoReflect.Descriptor instead.
func (*RobotMap) Descriptor() ([]byte, []int) {
	return file_api_external_b01_scmap_proto_rawDescGZIP(), []int{18}
}

func (x *RobotMap) GetMapType() uint32 {
	if x != nil && x.MapType != nil {
		return *x.MapType
	}
	return 0
}

func (x *RobotMap) GetMapExtInfo() *MapExtInfo {
	if x != nil {
		return x.MapExtInfo
	}
	return nil
}

func (x *RobotMap) GetMapHead() *MapHeadInfo {
	if x != nil {
		return x.MapHead
	}
	return nil
}

func (x *RobotMap) GetMapData() *MapDataInfo {
	if x != nil {
		return x.MapData
	}
	return nil
}

func (x *RobotMap) GetMapInfo() []*MapInfo {
	if x != nil {
		return x.MapInfo
	}
	return nil
}

func (x *RobotMap) GetHistoryPose() *DeviceHistoryPoseInfo {
	if x != nil {
		return x.HistoryPose
	}
	return nil
}

func (x *RobotMap) GetChargeStation() *DevicePoseInfo {
	if x != nil {
		return x.ChargeStation
	}
	return nil
}

func (x *RobotMap) GetCurrentPose() *DeviceCurrentPoseInfo {
	if x != nil {
		return x.CurrentPose
	}
	return nil
}

func (x *RobotMap) GetAreaInfo() []*DeviceAreaDataInfo {
	if x != nil {
		return x.AreaInfo
	}
	return nil
}

func (x *RobotMap) GetRoomDataInfo() []*RoomDataInfo {
	if x != nil {
		return x.RoomDataInfo
	}
	return nil
}

func (x *RobotMap) GetRoomMatrix() *RoomMatrixInfo {
	if x != nil {
		return x.RoomMatrix
	}
	return nil
}

func (x *RobotMap) GetRoomOutline() []*RoomOutlineInfo {
	if x != nil {
		return x.RoomOutline
	}
	return nil
}

func (x *RobotMap) GetCarpetInfo() []*CarpetDataInfo {
	if x != nil {
		return x.CarpetInfo
	}
	return nil
}

var File_api_external_b01_scmap_proto protoreflect.FileDescriptor

const file_api_external_b01_scmap_proto_rawDesc = "" +
	"\n" +
	"\x1capi/external/b01_scmap.proto\x12\tb01.scmap\"-\n" +
	"\x0fDevicePointInfo\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\x81\x01\n" +
	"\x0fMapBoundaryInfo\x12\x16\n" +
	"\x06mapMd5\x18\x01 \x01(\tR\x06mapMd5\x12\x14\n" +
	"\x05vMinX\x18\x02 \x01(\rR\x05vMinX\x12\x14\n" +
	"\x05vMaxX\x18\x03 \x01(\rR\x05vMaxX\x12\x14\n" +
	"\x05vMinY\x18\x04 \x01(\rR\x05vMinY\x12\x14\n" +
	"\x05vMaxY\x18\x05 \x01(\rR\x05vMaxY\"\xc2\x02\n" +
	"\n" +
	"MapExtInfo\x12$\n" +
	"\rtaskBeginDate\x18\x01 \x01(\rR\rtaskBeginDate\x12$\n" +
	"\rmapUploadDate\x18\x02 \x01(\rR\rmapUploadDate\x12\x1a\n" +
	"\bmapValid\x18\x03 \x01(\rR\bmapValid\x12\x16\n" +
	"\x06radian\x18\x04 \x01(\rR\x06radian\x12\x14\n" +
	"\x05force\x18\x05 \x01(\rR\x05force\x12\x1c\n" +
	"\tcleanPath\x18\x06 \x01(\rR\tcleanPath\x12<\n" +
	"\vboudaryInfo\x18\a \x01(\v2\x1a.b01.scmap.MapBoundaryInfoR\vboudaryInfo\x12\x1e\n" +
	"\n" +
	"mapVersion\x18\b \x01(\rR\n" +
	"mapVersion\x12\"\n" +
	"\fmapValueType\x18\t \x01(\rR\fmapValueType\"\xc7\x01\n" +
	"\vMapHeadInfo\x12\x1c\n" +
	"\tmapHeadId\x18\x01 \x01(\rR\tmapHeadId\x12\x14\n" +
	"\x05sizeX\x18\x02 \x01(\rR\x05sizeX\x12\x14\n" +
	"\x05sizeY\x18\x03 \x01(\rR\x05sizeY\x12\x12\n" +
	"\x04minX\x18\x04 \x01(\x02R\x04minX\x12\x12\n" +
	"\x04minY\x18\x05 \x01(\x02R\x04minY\x12\x12\n" +
	"\x04maxX\x18\x06 \x01(\x02R\x04maxX\x12\x12\n" +
	"\x04maxY\x18\a \x01(\x02R\x04maxY\x12\x1e\n" +
	"\n" +
	"resolution\x18\b \x01(\x02R\n" +
	"resolution\"'\n" +
	"\vMapDataInfo\x12\x18\n" +
	"\amapData\x18\x01 \x01(\fR\amapData\"9\n" +
	"\aMapInfo\x12\x14\n" +
	"\x05mapId\x18\x01 \x01(\rR\x05mapId\x12\x18\n" +
	"\amapName\x18\x02 \x01(\tR\amapName\"H\n" +
	"\x12DevicePoseDataInfo\x12\x16\n" +
	"\x06update\x18\x01 \x01(\rR\x06update\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"f\n" +
	"\x15DeviceHistoryPoseInfo\x12\x16\n" +
	"\x06poseId\x18\x01 \x01(\rR\x06poseId\x125\n" +
	"\x06points\x18\x02 \x03(\v2\x1d.b01.scmap.DevicePoseDataInfoR\x06points\">\n" +
	"\x0eDevicePoseInfo\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x10\n" +
	"\x03phi\x18\x03 \x01(\x02R\x03phi\"u\n" +
	"\x15DeviceCurrentPoseInfo\x12\x16\n" +
	"\x06poseId\x18\x01 \x01(\rR\x06poseId\x12\x16\n" +
	"\x06update\x18\x02 \x01(\rR\x06update\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x10\n" +
	"\x03phi\x18\x05 \x01(\x02R\x03phi\"\x92\x01\n" +
	"\x12DeviceAreaDataInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x1c\n" +
	"\tareaIndex\x18\x03 \x01(\rR\tareaIndex\x122\n" +
	"\x06points\x18\x04 \x03(\v2\x1a.b01.scmap.DevicePointInfoR\x06points\"(\n" +
	"\x0eRoomMatrixInfo\x12\x16\n" +
	"\x06matrix\x18\x01 \x01(\fR\x06matrix\"H\n" +
	"\x14RoomOutlinePointInfo\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\x14\n" +
	"\x05value\x18\x03 \x01(\rR\x05value\"1\n" +
	"\x13RoomBorderPointInfo\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\"b\n" +
	"\x0eRoomBorderInfo\x126\n" +
	"\x06points\x18\x01 \x03(\v2\x1e.b01.scmap.RoomBorderPointInfoR\x06points\x12\x18\n" +
	"\aroomIds\x18\x02 \x03(\rR\aroomIds\"\x97\x01\n" +
	"\x0fRoomOutlineInfo\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\rR\x06roomId\x127\n" +
	"\x06points\x18\x02 \x03(\v2\x1f.b01.scmap.RoomOutlinePointInfoR\x06points\x123\n" +
	"\aborders\x18\x03 \x03(\v2\x19.b01.scmap.RoomBorderInfoR\aborders\"\xe2\x01\n" +
	"\x0eCarpetDataInfo\x12\x1a\n" +
	"\bcarpetId\x18\x01 \x01(\rR\bcarpetId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x1a\n" +
	"\bunknown3\x18\x03 \x01(\rR\bunknown3\x122\n" +
	"\x06points\x18\x04 \x03(\v2\x1a.b01.scmap.DevicePointInfoR\x06points\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\rR\aenabled\x12\x1a\n" +
	"\bunknown7\x18\a \x01(\rR\bunknown7\x12\x1a\n" +
	"\bunknown8\x18\b \x01(\rR\bunknown8\"\x8a\x03\n" +
	"\fRoomDataInfo\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\rR\x06roomId\x12\x1a\n" +
	"\broomName\x18\x02 \x01(\tR\broomName\x12\x1e\n" +
	"\n" +
	"roomTypeId\x18\x03 \x01(\rR\n" +
	"roomTypeId\x12\x1e\n" +
	"\n" +
	"meterialId\x18\x04 \x01(\rR\n" +
	"meterialId\x12\x1e\n" +
	"\n" +
	"cleanState\x18\x05 \x01(\rR\n" +
	"cleanState\x12\x1c\n" +
	"\troomClean\x18\x06 \x01(\rR\troomClean\x12&\n" +
	"\x0eroomCleanIndex\x18\a \x01(\rR\x0eroomCleanIndex\x12>\n" +
	"\froomNamePost\x18\b \x01(\v2\x1a.b01.scmap.DevicePointInfoR\froomNamePost\x12\x18\n" +
	"\acolorId\x18\n" +
	" \x01(\rR\acolorId\x12'\n" +
	"\x0ffloor_direction\x18\v \x01(\rR\x0efloorDirection\x12\x1d\n" +
	"\n" +
	"global_seq\x18\f \x01(\rR\tglobalSeq\"\xe2\x05\n" +
	"\bRobotMap\x12\x18\n" +
	"\amapType\x18\x01 \x01(\rR\amapType\x125\n" +
	"\n" +
	"mapExtInfo\x18\x02 \x01(\v2\x15.b01.scmap.MapExtInfoR\n" +
	"mapExtInfo\x120\n" +
	"\amapHead\x18\x03 \x01(\v2\x16.b01.scmap.MapHeadInfoR\amapHead\x120\n" +
	"\amapData\x18\x04 \x01(\v2\x16.b01.scmap.MapDataInfoR\amapData\x12,\n" +
	"\amapInfo\x18\x05 \x03(\v2\x12.b01.scmap.MapInfoR\amapInfo\x12B\n" +
	"\vhistoryPose\x18\x06 \x01(\v2 .b01.scmap.DeviceHistoryPoseInfoR\vhistoryPose\x12?\n" +
	"\rchargeStation\x18\a \x01(\v2\x19.b01.scmap.DevicePoseInfoR\rchargeStation\x12B\n" +
	"\vcurrentPose\x18\b \x01(\v2 .b01.scmap.DeviceCurrentPoseInfoR\vcurrentPose\x129\n" +
	"\bareaInfo\x18\t \x03(\v2\x1d.b01.scmap.DeviceAreaDataInfoR\bareaInfo\x12;\n" +
	"\froomDataInfo\x18\f \x03(\v2\x17.b01.scmap.RoomDataInfoR\froomDataInfo\x129\n" +
	"\n" +
	"roomMatrix\x18\r \x01(\v2\x19.b01.scmap.RoomMatrixInfoR\n" +
	"roomMatrix\x12<\n" +
	"\vroomOutline\x18\x0e \x03(\v2\x1a.b01.scmap.RoomOutlineInfoR\vroomOutline\x129\n" +
	"\n" +
	"carpetInfo\x18\x14 \x03(\v2\x19.b01.scmap.CarpetDataInfoR\n" +
	"carpetInfoBBZ@github.com/portpowered/go-roborock/pkg/dependencymodels/mapproto"

var (
	file_api_external_b01_scmap_proto_rawDescOnce sync.Once
	file_api_external_b01_scmap_proto_rawDescData []byte
)

func file_api_external_b01_scmap_proto_rawDescGZIP() []byte {
	file_api_external_b01_scmap_proto_rawDescOnce.Do(func() {
		file_api_external_b01_scmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_external_b01_scmap_proto_rawDesc), len(file_api_external_b01_scmap_proto_rawDesc)))
	})
	return file_api_external_b01_scmap_proto_rawDescData
}

var file_api_external_b01_scmap_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_external_b01_scmap_proto_goTypes = []any{
	(*DevicePointInfo)(nil),       // 0: b01.scmap.DevicePointInfo
	(*MapBoundaryInfo)(nil),       // 1: b01.scmap.MapBoundaryInfo
	(*MapExtInfo)(nil),            // 2: b01.scmap.MapExtInfo
	(*MapHeadInfo)(nil),           // 3: b01.scmap.MapHeadInfo
	(*MapDataInfo)(nil),           // 4: b01.scmap.MapDataInfo
	(*MapInfo)(nil),               // 5: b01.scmap.MapInfo
	(*DevicePoseDataInfo)(nil),    // 6: b01.scmap.DevicePoseDataInfo
	(*DeviceHistoryPoseInfo)(nil), // 7: b01.scmap.DeviceHistoryPoseInfo
	(*DevicePoseInfo)(nil),        // 8: b01.scmap.DevicePoseInfo
	(*DeviceCurrentPoseInfo)(nil), // 9: b01.scmap.DeviceCurrentPoseInfo
	(*DeviceAreaDataInfo)(nil),    // 10: b01.scmap.DeviceAreaDataInfo
	(*RoomMatrixInfo)(nil),        // 11: b01.scmap.RoomMatrixInfo
	(*RoomOutlinePointInfo)(nil),  // 12: b01.scmap.RoomOutlinePointInfo
	(*RoomBorderPointInfo)(nil),   // 13: b01.scmap.RoomBorderPointInfo
	(*RoomBorderInfo)(nil),        // 14: b01.scmap.RoomBorderInfo
	(*RoomOutlineInfo)(nil),       // 15: b01.scmap.RoomOutlineInfo
	(*CarpetDataInfo)(nil),        // 16: b01.scmap.CarpetDataInfo
	(*RoomDataInfo)(nil),          // 17: b01.scmap.RoomDataInfo
	(*RobotMap)(nil),              // 18: b01.scmap.RobotMap
}
var file_api_external_b01_scmap_proto_depIdxs = []int32{
	1,  // 0: b01.scmap.MapExtInfo.boudaryInfo:type_name -> b01.scmap.MapBoundaryInfo
	6,  // 1: b01.scmap.DeviceHistoryPoseInfo.points:type_name -> b01.scmap.DevicePoseDataInfo
	0,  // 2: b01.scmap.DeviceAreaDataInfo.points:type_name -> b01.scmap.DevicePointInfo
	13, // 3: b01.scmap.RoomBorderInfo.points:type_name -> b01.scmap.RoomBorderPointInfo
	12, // 4: b01.scmap.RoomOutlineInfo.points:type_name -> b01.scmap.RoomOutlinePointInfo
	14, // 5: b01.scmap.RoomOutlineInfo.borders:type_name -> b01.scmap.RoomBorderInfo
	0,  // 6: b01.scmap.CarpetDataInfo.points:type_name -> b01.scmap.DevicePointInfo
	0,  // 7: b01.scmap.RoomDataInfo.roomNamePost:type_name -> b01.scmap.DevicePointInfo
	2,  // 8: b01.scmap.RobotMap.mapExtInfo:type_name -> b01.scmap.MapExtInfo
	3,  // 9: b01.scmap.RobotMap.mapHead:type_name -> b01.scmap.MapHeadInfo
	4,  // 10: b01.scmap.RobotMap.mapData:type_name -> b01.scmap.MapDataInfo
	5,  // 11: b01.scmap.RobotMap.mapInfo:type_name -> b01.scmap.MapInfo
	7,  // 12: b01.scmap.RobotMap.historyPose:type_name -> b01.scmap.DeviceHistoryPoseInfo
	8,  // 13: b01.scmap.RobotMap.chargeStation:type_name -> b01.scmap.DevicePoseInfo
	9,  // 14: b01.scmap.RobotMap.currentPose:type_name -> b01.scmap.DeviceCurrentPoseInfo
	10, // 15: b01.scmap.RobotMap.areaInfo:type_name -> b01.scmap.DeviceAreaDataInfo
	17, // 16: b01.scmap.RobotMap.roomDataInfo:type_name -> b01.scmap.RoomDataInfo
	11, // 17: b01.scmap.RobotMap.roomMatrix:type_name -> b01.scmap.RoomMatrixInfo
	15, // 18: b01.scmap.RobotMap.roomOutline:type_name -> b01.scmap.RoomOutlineInfo
	16, // 19: b01.scmap.RobotMap.carpetInfo:type_name -> b01.scmap.CarpetDataInfo
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_api_external_b01_scmap_proto_init() }
func file_api_external_b01_scmap_proto_init() {
	if File_api_external_b01_scmap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_external_b01_scmap_proto_rawDesc), len(file_api_external_b01_scmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_external_b01_scmap_proto_goTypes,
		DependencyIndexes: file_api_external_b01_scmap_proto_depIdxs,
		MessageInfos:      file_api_external_b01_scmap_proto_msgTypes,
	}.Build()
	File_api_external_b01_scmap_proto = out.File
	file_api_external_b01_scmap_proto_goTypes = nil
	file_api_external_b01_scmap_proto_depIdxs = nil
}
