// Command publicdocs renders schema-owned public A01 types as customer MDX.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"html"
	"io/fs"
	"os"
	"slices"
	"sort"
	"strconv"
	"strings"
)

const (
	sourceFile    = "api/a01-models.openapi.yaml"
	generatedFile = "pkg/roborock/a01_models.gen.go"
	outputFile    = "docs/guides/a01-models.mdx"
	privateMode   = 0o600
)

var errPublicDocs = errors.New("public documentation does not match its schema")

type document struct {
	Components components `json:"components"`
}
type components struct {
	Schemas map[string]schema `json:"schemas"`
}
type schema struct {
	Description string              `json:"description"`
	Properties  map[string]property `json:"properties"`
	Required    []string            `json:"required"`
	Enum        []json.RawMessage   `json:"enum"`
	EnumNames   []string            `json:"x-enum-varnames"` //nolint:tagliatelle // Fixed OpenAPI extension key.
}
type property struct {
	Description string `json:"description"`
}
type goField struct{ name, jsonName, kind string }

func main() {
	check := flag.Bool("check", false, "verify checked-in public model guide")

	flag.Parse()

	err := run(*check)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(check bool) error {
	tree := os.DirFS(".")

	data, err := fs.ReadFile(tree, sourceFile)
	if err != nil {
		return fmt.Errorf("read public schema: %w", err)
	}

	var spec document

	err = json.Unmarshal(data, &spec)
	if err != nil {
		return fmt.Errorf("decode public schema: %w", err)
	}

	fields, err := readFields()
	if err != nil {
		return err
	}

	rendered, err := render(spec, fields)
	if err != nil {
		return err
	}

	if check {
		previous, readErr := fs.ReadFile(tree, outputFile)
		if readErr != nil {
			return fmt.Errorf("read generated guide: %w", readErr)
		}

		if !bytes.Equal(previous, rendered) {
			return errPublicDocs
		}

		return nil
	}

	err = os.WriteFile(outputFile, rendered, privateMode)
	if err != nil {
		return fmt.Errorf("write public guide: %w", err)
	}

	return nil
}

func readFields() (map[string][]goField, error) {
	fileSet := token.NewFileSet()

	file, err := parser.ParseFile(fileSet, generatedFile, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse generated public models: %w", err)
	}

	fields := map[string][]goField{}

	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, item := range group.Specs {
			definition, isType := item.(*ast.TypeSpec)
			if !isType {
				continue
			}

			structure, isStruct := definition.Type.(*ast.StructType)
			if !isStruct {
				continue
			}

			model, fieldErr := structFields(fileSet, structure)
			if fieldErr != nil {
				return nil, fieldErr
			}

			fields[definition.Name.Name] = model
		}
	}

	return fields, nil
}

func structFields(fileSet *token.FileSet, structure *ast.StructType) ([]goField, error) {
	fields := make([]goField, 0, len(structure.Fields.List))

	for _, field := range structure.Fields.List {
		if len(field.Names) != 1 || field.Tag == nil {
			return nil, errPublicDocs
		}

		tag, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return nil, fmt.Errorf("decode generated field tag: %w", err)
		}

		_, suffix, found := strings.Cut(tag, `json:"`)
		if !found {
			return nil, errPublicDocs
		}

		jsonName, _, _ := strings.Cut(suffix, `"`)
		jsonName, _, _ = strings.Cut(jsonName, ",")

		var kind bytes.Buffer

		err = printer.Fprint(&kind, fileSet, field.Type)
		if err != nil {
			return nil, fmt.Errorf("render Go field type: %w", err)
		}

		fields = append(fields, goField{name: field.Names[0].Name, jsonName: jsonName, kind: kind.String()})
	}

	return fields, nil
}

func render(spec document, fields map[string][]goField) ([]byte, error) {
	var output strings.Builder

	output.WriteString("---\ntitle: A01 public type reference\n" +
		"description: Generated request fields, state fields, and known appliance enum constants.\n---\n\n")
	output.WriteString("{/* Code generated by go run ./tools/publicdocs; DO NOT EDIT. */}\n\n")
	output.WriteString("This reference is generated from the public A01 projection schema and its Go declarations. ")
	output.WriteString("See [A01 workflow](/docs/guides/a01) for appliance-supported property selection and commands. ")
	output.WriteString("Optional pointer fields preserve absence; sparse settings send only non-nil fields. ")
	output.WriteString("Known enum constants are listed below; open numeric types preserve future values.\n\n")

	names := make([]string, 0, len(spec.Components.Schemas))

	for name := range spec.Components.Schemas {
		names = append(names, name)
	}

	sort.Strings(names)

	for _, name := range names {
		component := spec.Components.Schemas[name]
		output.WriteString("## " + name + "\n\n" + plain(component.Description) + "\n\n")
		output.WriteString("[Go declaration](https://pkg.go.dev/github.com/portpowered/go-roborock/pkg/roborock#" +
			name + ").\n\n")

		err := renderComponent(&output, component, fields[name])
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
	}

	return []byte(output.String()), nil
}

func renderComponent(output *strings.Builder, component schema, fields []goField) error {
	if len(component.Enum) != 0 {
		if len(component.EnumNames) != len(component.Enum) {
			return errPublicDocs
		}

		output.WriteString("| Go constant | Value |\n| --- | --- |\n")

		for index, value := range component.Enum {
			output.WriteString("| `" + component.EnumNames[index] + "` | `" + string(value) + "` |\n")
		}

		output.WriteString("\n")
	}

	if len(component.Properties) == 0 {
		return nil
	}

	if len(component.Properties) != len(fields) {
		return errPublicDocs
	}

	output.WriteString("| Go field | JSON field | Go type | Required | Meaning |\n| --- | --- | --- | --- | --- |\n")

	for _, field := range fields {
		definition, exists := component.Properties[field.jsonName]
		if !exists {
			return errPublicDocs
		}

		required := "no"
		if slices.Contains(component.Required, field.jsonName) {
			required = "yes"
		}

		output.WriteString("| `" + field.name + "` | `" + field.jsonName + "` | `" + field.kind + "` | " + required + " | " +
			plain(definition.Description) + " |\n")
	}

	output.WriteString("\n")

	return nil
}

func plain(text string) string {
	escaped := html.EscapeString(strings.ReplaceAll(strings.ReplaceAll(text, "\n", " "), "|", "\\|"))

	return strings.ReplaceAll(strings.ReplaceAll(escaped, "{", "&#123;"), "}", "&#125;")
}
