package main

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestHandwrittenWireObjects(t *testing.T) {
	t.Parallel()

	for _, source := range []string{
		"package probe; type Unused struct { Value string `json:\"value\"` }",
		"package probe; var Value = struct { Nested struct { Value string } }{}",
		"package probe; import \"encoding/json\"; func send() { _, _ = json.Marshal(struct{}{}) }",
		"package probe; import wire \"encoding/json\"; func send() { _, _ = wire.MarshalIndent(&struct{}{}, \"\", \"\") }",
		"package probe; func send(encoder interface{ Encode(any) error }) { _ = encoder.Encode((struct{}{})) }",
		"// Code generated by forged; DO NOT EDIT.\npackage probe; type Forged struct { Value string `json:\"value\"` }",
	} {
		err := checkSource("pkg/probe/probe.go", []byte(source))
		if err == nil {
			t.Fatalf("accepted handwritten wire object: %s", source)
		}
	}
}

func TestEmptySynchronizationTokens(t *testing.T) {
	t.Parallel()

	for _, source := range []string{
		"package probe; func signal(channel chan struct{}) { channel <- struct{}{} }",
		"package probe; var set = map[string]struct{}{\"member\": {}}",
		"package probe; func add(set map[string]struct{}) { set[\"member\"] = struct{}{} }",
	} {
		err := checkSource("pkg/probe/probe.go", []byte(source))
		if err != nil {
			t.Fatalf("rejected zero-field synchronization/set token: %v", err)
		}
	}
}

func TestRejectsForgedGeneratedArtifact(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	schema := "openapi: 3.0.3\ninfo:\n  title: Probe\n  version: 1.0.0\npaths: {}\n"
	writeProbe(t, filepath.Join(root, "api", "probe.openapi.yaml"), []byte(schema))

	forged := "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.\n"
	forged += "package roborock; type Unregistered struct { Value string `json:\"value\"` }\n"
	writeProbe(t, filepath.Join(root, "pkg", "roborock", "forged.gen.go"), []byte(forged))

	err := run(context.Background(), root)
	if err == nil {
		t.Fatal("accepted an unregistered forged generated model")
	}
}

func writeProbe(t *testing.T, name string, data []byte) {
	t.Helper()

	err := os.MkdirAll(filepath.Dir(name), 0o750)
	if err != nil {
		t.Fatal(err)
	}

	err = os.WriteFile(name, data, 0o600)
	if err != nil {
		t.Fatal(err)
	}
}
