// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.

package roborock

// Defines values for DyadBrushSpeed.
const (
	DyadBrushSpeedL1 DyadBrushSpeed = 1
	DyadBrushSpeedL2 DyadBrushSpeed = 2
)

// Defines values for DyadCleanMode.
const (
	DyadCleanModeAuto        DyadCleanMode = 1
	DyadCleanModeDehydration DyadCleanMode = 3
	DyadCleanModeMax         DyadCleanMode = 2
	DyadCleanModePowerSaving DyadCleanMode = 4
)

// Defines values for DyadCleanser.
const (
	DyadCleanserDeep   DyadCleanser = 2
	DyadCleanserMax    DyadCleanser = 3
	DyadCleanserNone   DyadCleanser = 0
	DyadCleanserNormal DyadCleanser = 1
)

// Defines values for DyadError.
const (
	DyadErrorBatteryTemperatureProtection   DyadError = 20007
	DyadErrorBatteryTemperatureProtection2  DyadError = 20008
	DyadErrorBatteryTemperatureProtectionE0 DyadError = 10000
	DyadErrorBatteryUnder10                 DyadError = 20018
	DyadErrorCleanHeadEntangled             DyadError = 20003
	DyadErrorCleanHeadTooHot                DyadError = 20004
	DyadErrorCleanTankEmpty                 DyadError = 20002
	DyadErrorCleaningHeadBlocked            DyadError = 20005
	DyadErrorDirtyChargingContacts          DyadError = 10007
	DyadErrorDirtyTankFull                  DyadError = 20000
	DyadErrorFanProtectionE4                DyadError = 10004
	DyadErrorFanProtectionE5                DyadError = 10005
	DyadErrorFanProtectionE9                DyadError = 10009
	DyadErrorLowBattery                     DyadError = 20017
	DyadErrorNone                           DyadError = 0
	DyadErrorPowerAdapterError              DyadError = 20009
	DyadErrorTemperatureProtection          DyadError = 20006
	DyadErrorWaterLevelSensorStuck          DyadError = 20001
)

// Defines values for DyadMode.
const (
	DyadModeDry        DyadMode = 3
	DyadModeWash       DyadMode = 1
	DyadModeWashAndDry DyadMode = 2
)

// Defines values for DyadProperty.
const (
	DyadPropertyAutoDry              DyadProperty = 213
	DyadPropertyAutoDryMode          DyadProperty = 224
	DyadPropertyAutoSelfCleanSet     DyadProperty = 212
	DyadPropertyAutoSelfCleanSetMode DyadProperty = 223
	DyadPropertyBrushLeft            DyadProperty = 215
	DyadPropertyBrushReset           DyadProperty = 219
	DyadPropertyBrushSpeed           DyadProperty = 208
	DyadPropertyCleanMode            DyadProperty = 205
	DyadPropertyCountdownTime        DyadProperty = 210
	DyadPropertyDryCountdown         DyadProperty = 237
	DyadPropertyDryingStatus         DyadProperty = 134
	DyadPropertyError                DyadProperty = 216
	DyadPropertyFeatureInfo          DyadProperty = 235
	DyadPropertyMeshLeft             DyadProperty = 214
	DyadPropertyMeshReset            DyadProperty = 218
	DyadPropertyPower                DyadProperty = 209
	DyadPropertyRecentRunTime        DyadProperty = 229
	DyadPropertyRecoverSettings      DyadProperty = 236
	DyadPropertySelfCleanLevel       DyadProperty = 203
	DyadPropertySelfCleanMode        DyadProperty = 202
	DyadPropertySilentDryDuration    DyadProperty = 225
	DyadPropertySilentMode           DyadProperty = 226
	DyadPropertySilentModeEndTime    DyadProperty = 228
	DyadPropertySilentModeStartTime  DyadProperty = 227
	DyadPropertyStandLockAutoRun     DyadProperty = 222
	DyadPropertyStart                DyadProperty = 200
	DyadPropertyStatus               DyadProperty = 201
	DyadPropertySuction              DyadProperty = 206
	DyadPropertyTotalRunTime         DyadProperty = 230
	DyadPropertyVolume               DyadProperty = 221
	DyadPropertyWarmLevel            DyadProperty = 204
	DyadPropertyWaterLevel           DyadProperty = 207
)

// Defines values for DyadSelfCleanLevel.
const (
	DyadSelfCleanLevelDeep   DyadSelfCleanLevel = 2
	DyadSelfCleanLevelNormal DyadSelfCleanLevel = 1
)

// Defines values for DyadSelfCleanMode.
const (
	DyadSelfCleanModeDry             DyadSelfCleanMode = 3
	DyadSelfCleanModeSelfClean       DyadSelfCleanMode = 1
	DyadSelfCleanModeSelfCleanAndDry DyadSelfCleanMode = 2
	DyadSelfCleanModeVentilation     DyadSelfCleanMode = 4
)

// Defines values for DyadStatus.
const (
	DyadStatusCharging              DyadStatus = 3
	DyadStatusDrying                DyadStatus = 9
	DyadStatusDustingMode           DyadStatus = 14
	DyadStatusFetchFailed           DyadStatus = -997
	DyadStatusFetching              DyadStatus = -998
	DyadStatusMopWashing            DyadStatus = 4
	DyadStatusMopWashingPaused      DyadStatus = 13
	DyadStatusReady                 DyadStatus = 2
	DyadStatusReserving             DyadStatus = 12
	DyadStatusSelfCleanCleaning     DyadStatus = 5
	DyadStatusSelfCleanDeepCleaning DyadStatus = 6
	DyadStatusSelfCleanDehydrating  DyadStatus = 8
	DyadStatusSelfCleanRinsing      DyadStatus = 7
	DyadStatusUnknown               DyadStatus = -999
	DyadStatusUpdating              DyadStatus = -996
	DyadStatusVentilating           DyadStatus = 10
	DyadStatusWashing               DyadStatus = 1
)

// Defines values for DyadSuction.
const (
	DyadSuctionL1 DyadSuction = 1
	DyadSuctionL2 DyadSuction = 2
	DyadSuctionL3 DyadSuction = 3
	DyadSuctionL4 DyadSuction = 4
	DyadSuctionL5 DyadSuction = 5
	DyadSuctionL6 DyadSuction = 6
)

// Defines values for DyadSwitch.
const (
	DyadSwitchOff DyadSwitch = 0
	DyadSwitchOn  DyadSwitch = 1
)

// Defines values for DyadWarmLevel.
const (
	DyadWarmLevelDeep   DyadWarmLevel = 2
	DyadWarmLevelNormal DyadWarmLevel = 1
)

// Defines values for DyadWaterLevel.
const (
	DyadWaterLevelL1 DyadWaterLevel = 1
	DyadWaterLevelL2 DyadWaterLevel = 2
	DyadWaterLevelL3 DyadWaterLevel = 3
	DyadWaterLevelL4 DyadWaterLevel = 4
)

// Defines values for ZeoDetergentExpansionType.
const (
	ZeoDetergentExpansionTypeConcentratedDetergent ZeoDetergentExpansionType = 1
	ZeoDetergentExpansionTypeDetergent             ZeoDetergentExpansionType = 2
	ZeoDetergentExpansionTypeNull                  ZeoDetergentExpansionType = 0
)

// Defines values for ZeoDetergentType.
const (
	ZeoDetergentTypeEmpty  ZeoDetergentType = 0
	ZeoDetergentTypeHigh   ZeoDetergentType = 3
	ZeoDetergentTypeLow    ZeoDetergentType = 1
	ZeoDetergentTypeMedium ZeoDetergentType = 2
)

// Defines values for ZeoDirtDetectionStatus.
const (
	ZeoDirtDetectionStatusDetecting          ZeoDirtDetectionStatus = 1
	ZeoDirtDetectionStatusDetectionCompleted ZeoDirtDetectionStatus = 2
	ZeoDirtDetectionStatusIdle               ZeoDirtDetectionStatus = 0
)

// Defines values for ZeoDryAndCare.
const (
	ZeoDryAndCareNormal ZeoDryAndCare = 2
	ZeoDryAndCareNull   ZeoDryAndCare = 0
	ZeoDryAndCareSoft   ZeoDryAndCare = 1
)

// Defines values for ZeoDryerStartError.
const (
	ZeoDryerStartErrorDryerCountdown      ZeoDryerStartError = 6
	ZeoDryerStartErrorDryerDone           ZeoDryerStartError = 3
	ZeoDryerStartErrorDryerError          ZeoDryerStartError = 2
	ZeoDryerStartErrorDryerNetworkFail    ZeoDryerStartError = 7
	ZeoDryerStartErrorDryerRunning        ZeoDryerStartError = 1
	ZeoDryerStartErrorDryerSmartHosting   ZeoDryerStartError = 5
	ZeoDryerStartErrorDryerWaitingHosting ZeoDryerStartError = 4
	ZeoDryerStartErrorNull                ZeoDryerStartError = 0
)

// Defines values for ZeoDryingMethod.
const (
	ZeoDryingMethodL1   ZeoDryingMethod = 1
	ZeoDryingMethodL2   ZeoDryingMethod = 2
	ZeoDryingMethodL3   ZeoDryingMethod = 3
	ZeoDryingMethodNull ZeoDryingMethod = 0
)

// Defines values for ZeoDryingMode.
const (
	ZeoDryingModeIron  ZeoDryingMode = 2
	ZeoDryingModeNone  ZeoDryingMode = 0
	ZeoDryingModeQuick ZeoDryingMode = 1
	ZeoDryingModeStore ZeoDryingMode = 3
)

// Defines values for ZeoError.
const (
	ZeoErrorCommunicationError   ZeoError = 10
	ZeoErrorDoorLockError        ZeoError = 3
	ZeoErrorDrainError           ZeoError = 2
	ZeoErrorDryingError          ZeoError = 11
	ZeoErrorDryingErrorE12       ZeoError = 12
	ZeoErrorDryingErrorE13       ZeoError = 13
	ZeoErrorDryingErrorE14       ZeoError = 14
	ZeoErrorDryingErrorE15       ZeoError = 15
	ZeoErrorDryingErrorE16       ZeoError = 16
	ZeoErrorDryingErrorRestart   ZeoError = 18
	ZeoErrorDryingErrorWaterFlow ZeoError = 17
	ZeoErrorHeatingError         ZeoError = 6
	ZeoErrorInverterError        ZeoError = 5
	ZeoErrorNone                 ZeoError = 0
	ZeoErrorRefillError          ZeoError = 1
	ZeoErrorSpinError            ZeoError = 19
	ZeoErrorTemperatureError     ZeoError = 7
	ZeoErrorWaterLevelError      ZeoError = 4
)

// Defines values for ZeoFeatureBits.
const (
	ZeoFeatureBitsAdaptedCustomProgram      ZeoFeatureBits = 14
	ZeoFeatureBitsConcentratedDetergent     ZeoFeatureBits = 11
	ZeoFeatureBitsDeepSelfClean             ZeoFeatureBits = 19
	ZeoFeatureBitsDetectDoorStatus          ZeoFeatureBits = 5
	ZeoFeatureBitsDirtDetection             ZeoFeatureBits = 18
	ZeoFeatureBitsDryCare                   ZeoFeatureBits = 3
	ZeoFeatureBitsExpandSoftener            ZeoFeatureBits = 6
	ZeoFeatureBitsFluffCleanNotification    ZeoFeatureBits = 16
	ZeoFeatureBitsIonDeodorization          ZeoFeatureBits = 23
	ZeoFeatureBitsNewCustomProgram          ZeoFeatureBits = 2
	ZeoFeatureBitsPowerButtonIndicatorLight ZeoFeatureBits = 17
	ZeoFeatureBitsSavePanelProgramParams    ZeoFeatureBits = 20
	ZeoFeatureBitsSetParamsInWorking        ZeoFeatureBits = 7
	ZeoFeatureBitsSetUvcInAppointment       ZeoFeatureBits = 4
	ZeoFeatureBitsSetUvcInPause             ZeoFeatureBits = 10
	ZeoFeatureBitsSilentMode                ZeoFeatureBits = 1
	ZeoFeatureBitsSmartHosting              ZeoFeatureBits = 0
	ZeoFeatureBitsSmileLight                ZeoFeatureBits = 9
	ZeoFeatureBitsSteamCare                 ZeoFeatureBits = 21
	ZeoFeatureBitsThirtyMinSoak             ZeoFeatureBits = 8
	ZeoFeatureBitsVoiceAssistant            ZeoFeatureBits = 13
	ZeoFeatureBitsVoiceAssistantRecord      ZeoFeatureBits = 15
	ZeoFeatureBitsWashDryLinkage            ZeoFeatureBits = 22
	ZeoFeatureBitsWoolDetergent             ZeoFeatureBits = 12
)

// Defines values for ZeoMode.
const (
	ZeoModeDry        ZeoMode = 3
	ZeoModeNull       ZeoMode = 0
	ZeoModeTreatment  ZeoMode = 4
	ZeoModeWash       ZeoMode = 1
	ZeoModeWashAndDry ZeoMode = 2
)

// Defines values for ZeoProgram.
const (
	ZeoProgramAirRefresh        ZeoProgram = 5
	ZeoProgramAntiAllergen      ZeoProgram = 14
	ZeoProgramAntiMite          ZeoProgram = 32
	ZeoProgramBabyCare          ZeoProgram = 13
	ZeoProgramBathTowel         ZeoProgram = 40
	ZeoProgramBedding           ZeoProgram = 7
	ZeoProgramBoilingWash       ZeoProgram = 28
	ZeoProgramBra               ZeoProgram = 26
	ZeoProgramCottonLinen       ZeoProgram = 23
	ZeoProgramCustom            ZeoProgram = 6
	ZeoProgramDeepSelfClean     ZeoProgram = 55
	ZeoProgramDescaling         ZeoProgram = 54
	ZeoProgramDown              ZeoProgram = 8
	ZeoProgramDownClean         ZeoProgram = 12
	ZeoProgramExo4060           ZeoProgram = 33
	ZeoProgramFlax              ZeoProgram = 47
	ZeoProgramGentle            ZeoProgram = 21
	ZeoProgramIntensive         ZeoProgram = 22
	ZeoProgramJeans             ZeoProgram = 41
	ZeoProgramMixing            ZeoProgram = 39
	ZeoProgramNewClothes        ZeoProgram = 17
	ZeoProgramNight             ZeoProgram = 16
	ZeoProgramNull              ZeoProgram = 0
	ZeoProgramOutdoorJackets    ZeoProgram = 44
	ZeoProgramOutdoors          ZeoProgram = 42
	ZeoProgramPanties           ZeoProgram = 27
	ZeoProgramPetCare           ZeoProgram = 56
	ZeoProgramQuick             ZeoProgram = 2
	ZeoProgramQuiltDrying       ZeoProgram = 46
	ZeoProgramRackDrying        ZeoProgram = 50
	ZeoProgramRinseAndSpin      ZeoProgram = 10
	ZeoProgramSanitize          ZeoProgram = 3
	ZeoProgramSeason            ZeoProgram = 24
	ZeoProgramShirts            ZeoProgram = 18
	ZeoProgramSilk              ZeoProgram = 9
	ZeoProgramSmallThings       ZeoProgram = 37
	ZeoProgramSmallThingsDrying ZeoProgram = 57
	ZeoProgramSoaking           ZeoProgram = 29
	ZeoProgramSocks             ZeoProgram = 30
	ZeoProgramSpin              ZeoProgram = 11
	ZeoProgramSportShoes        ZeoProgram = 49
	ZeoProgramSportswear        ZeoProgram = 15
	ZeoProgramStainRemoval      ZeoProgram = 36
	ZeoProgramStandard          ZeoProgram = 1
	ZeoProgramSteamCare         ZeoProgram = 53
	ZeoProgramSuit              ZeoProgram = 48
	ZeoProgramSummerQuilt       ZeoProgram = 51
	ZeoProgramSynthetics        ZeoProgram = 19
	ZeoProgramTShirts           ZeoProgram = 35
	ZeoProgramTimedDrying       ZeoProgram = 43
	ZeoProgramTowels            ZeoProgram = 31
	ZeoProgramTwentyC           ZeoProgram = 34
	ZeoProgramUnderwear         ZeoProgram = 20
	ZeoProgramWarming           ZeoProgram = 25
	ZeoProgramWindBreaker       ZeoProgram = 52
	ZeoProgramWool              ZeoProgram = 4
	ZeoProgramYoga              ZeoProgram = 45
)

// Defines values for ZeoProperty.
const (
	ZeoPropertyAppAuthorization            ZeoProperty = 232
	ZeoPropertyChildLock                   ZeoProperty = 206
	ZeoPropertyClothPutIn                  ZeoProperty = 263
	ZeoPropertyClothReadyToDryCountdown    ZeoProperty = 264
	ZeoPropertyCountdown                   ZeoProperty = 217
	ZeoPropertyCustomParamGet              ZeoProperty = 222
	ZeoPropertyCustomParamSave             ZeoProperty = 221
	ZeoPropertyCustomProgramCleaningTime   ZeoProperty = 239
	ZeoPropertyDefaultSetting              ZeoProperty = 225
	ZeoPropertyDetergentEmpty              ZeoProperty = 226
	ZeoPropertyDetergentExpansionType      ZeoProperty = 248
	ZeoPropertyDetergentSet                ZeoProperty = 211
	ZeoPropertyDetergentType               ZeoProperty = 213
	ZeoPropertyDetergentVolume             ZeoProperty = 230
	ZeoPropertyDeviceBound                 ZeoProperty = 262
	ZeoPropertyDirtDetectionStatus         ZeoProperty = 216
	ZeoPropertyDirtDetectionSwitch         ZeoProperty = 215
	ZeoPropertyDoorLockState               ZeoProperty = 219
	ZeoPropertyDryCareMode                 ZeoProperty = 244
	ZeoPropertyDryingMethod                ZeoProperty = 256
	ZeoPropertyDryingMode                  ZeoProperty = 210
	ZeoPropertyError                       ZeoProperty = 220
	ZeoPropertyFeatureBits                 ZeoProperty = 237
	ZeoPropertyFluffCleaned                ZeoProperty = 249
	ZeoPropertyIonDeodorization            ZeoProperty = 258
	ZeoPropertyLightSetting                ZeoProperty = 229
	ZeoPropertyMode                        ZeoProperty = 204
	ZeoPropertyNeedFluffClean              ZeoProperty = 250
	ZeoPropertyPanelProgramParamsSet       ZeoProperty = 252
	ZeoPropertyPanelProgramParamsSetResult ZeoProperty = 253
	ZeoPropertyPanelTimingProgramParams    ZeoProperty = 260
	ZeoPropertyPause                       ZeoProperty = 201
	ZeoPropertyPowerLight                  ZeoProperty = 251
	ZeoPropertyProgram                     ZeoProperty = 205
	ZeoPropertyRinse                       ZeoProperty = 208
	ZeoPropertySaveAdaptedCloudProgram     ZeoProperty = 254
	ZeoPropertyShutdown                    ZeoProperty = 202
	ZeoPropertySilentMode                  ZeoProperty = 240
	ZeoPropertySilentModeEndTime           ZeoProperty = 242
	ZeoPropertySilentModeStartTime         ZeoProperty = 241
	ZeoPropertySmartHosting                ZeoProperty = 235
	ZeoPropertySmartHostingTime            ZeoProperty = 236
	ZeoPropertySmartHostingWaitedTime      ZeoProperty = 238
	ZeoPropertySmileLightStatus            ZeoProperty = 247
	ZeoPropertySoak                        ZeoProperty = 233
	ZeoPropertySoftenerEmpty               ZeoProperty = 227
	ZeoPropertySoftenerExpansionType       ZeoProperty = 245
	ZeoPropertySoftenerSet                 ZeoProperty = 212
	ZeoPropertySoftenerType                ZeoProperty = 214
	ZeoPropertySoftenerVolume              ZeoProperty = 231
	ZeoPropertySound                       ZeoProperty = 223
	ZeoPropertySpin                        ZeoProperty = 209
	ZeoPropertyStart                       ZeoProperty = 200
	ZeoPropertyStartDryerError             ZeoProperty = 265
	ZeoPropertyStatus                      ZeoProperty = 203
	ZeoPropertySteamCareTime               ZeoProperty = 261
	ZeoPropertySteamVolume                 ZeoProperty = 257
	ZeoPropertyTemperature                 ZeoProperty = 207
	ZeoPropertyTimesAfterClean             ZeoProperty = 224
	ZeoPropertyTotalTime                   ZeoProperty = 234
	ZeoPropertyUVLight                     ZeoProperty = 228
	ZeoPropertyWashDryLinked               ZeoProperty = 255
	ZeoPropertyWashingLeft                 ZeoProperty = 218
	ZeoPropertyWiFiLinkageReset            ZeoProperty = 266
)

// Defines values for ZeoRinse.
const (
	ZeoRinseHigh ZeoRinse = 4
	ZeoRinseLow  ZeoRinse = 2
	ZeoRinseMax  ZeoRinse = 5
	ZeoRinseMid  ZeoRinse = 3
	ZeoRinseMin  ZeoRinse = 1
	ZeoRinseNone ZeoRinse = 0
)

// Defines values for ZeoSoak.
const (
	ZeoSoakHigh    ZeoSoak = 3
	ZeoSoakLow     ZeoSoak = 1
	ZeoSoakMax     ZeoSoak = 4
	ZeoSoakMedium  ZeoSoak = 2
	ZeoSoakNormal  ZeoSoak = 0
	ZeoSoakVeryMax ZeoSoak = 5
)

// Defines values for ZeoSoftenerExpansionType.
const (
	ZeoSoftenerExpansionTypeNull              ZeoSoftenerExpansionType = 0
	ZeoSoftenerExpansionTypeSoftener          ZeoSoftenerExpansionType = 1
	ZeoSoftenerExpansionTypeSoftenerExpansion ZeoSoftenerExpansionType = 2
	ZeoSoftenerExpansionTypeWoolDetergent     ZeoSoftenerExpansionType = 3
)

// Defines values for ZeoSoftenerType.
const (
	ZeoSoftenerTypeEmpty  ZeoSoftenerType = 0
	ZeoSoftenerTypeHigh   ZeoSoftenerType = 3
	ZeoSoftenerTypeLow    ZeoSoftenerType = 1
	ZeoSoftenerTypeMedium ZeoSoftenerType = 2
)

// Defines values for ZeoSpin.
const (
	ZeoSpinHigh     ZeoSpin = 5
	ZeoSpinLow      ZeoSpin = 3
	ZeoSpinMax      ZeoSpin = 7
	ZeoSpinMid      ZeoSpin = 4
	ZeoSpinNone     ZeoSpin = 1
	ZeoSpinNull     ZeoSpin = 0
	ZeoSpinVeryHigh ZeoSpin = 6
	ZeoSpinVeryLow  ZeoSpin = 2
)

// Defines values for ZeoStatus.
const (
	ZeoStatusAftercare           ZeoStatus = 12
	ZeoStatusClothReady          ZeoStatus = 16
	ZeoStatusCooling             ZeoStatus = 8
	ZeoStatusDescaling           ZeoStatus = 15
	ZeoStatusDone                ZeoStatus = 10
	ZeoStatusDrying              ZeoStatus = 7
	ZeoStatusInCare              ZeoStatus = 20
	ZeoStatusNull                ZeoStatus = 0
	ZeoStatusPreHeatComplete     ZeoStatus = 19
	ZeoStatusPreHeating          ZeoStatus = 18
	ZeoStatusRinsing             ZeoStatus = 5
	ZeoStatusSoaking             ZeoStatus = 3
	ZeoStatusSpinning            ZeoStatus = 6
	ZeoStatusStandby             ZeoStatus = 1
	ZeoStatusSteamCaring         ZeoStatus = 14
	ZeoStatusUnderDelayStart     ZeoStatus = 9
	ZeoStatusUpdating            ZeoStatus = 11
	ZeoStatusWaitingForAftercare ZeoStatus = 13
	ZeoStatusWaitingForDrying    ZeoStatus = 17
	ZeoStatusWashing             ZeoStatus = 4
	ZeoStatusWeighing            ZeoStatus = 2
)

// Defines values for ZeoSteamVolume.
const (
	ZeoSteamVolumeHigh   ZeoSteamVolume = 3
	ZeoSteamVolumeLow    ZeoSteamVolume = 1
	ZeoSteamVolumeMax    ZeoSteamVolume = 4
	ZeoSteamVolumeMedium ZeoSteamVolume = 2
	ZeoSteamVolumeNone   ZeoSteamVolume = 0
)

// Defines values for ZeoTemperature.
const (
	ZeoTemperatureHigh    ZeoTemperature = 4
	ZeoTemperatureLow     ZeoTemperature = 2
	ZeoTemperatureMax     ZeoTemperature = 5
	ZeoTemperatureMedium  ZeoTemperature = 3
	ZeoTemperatureNinetyC ZeoTemperature = 7
	ZeoTemperatureNormal  ZeoTemperature = 1
	ZeoTemperatureNull    ZeoTemperature = 0
	ZeoTemperatureTwentyC ZeoTemperature = 6
)

// DyadBrushSpeed Known protocol values; unlisted future numeric values remain valid.
type DyadBrushSpeed int

// DyadCleanMode Known protocol values; unlisted future numeric values remain valid.
type DyadCleanMode int

// DyadCleanser Known protocol values; unlisted future numeric values remain valid.
type DyadCleanser int

// DyadError Known protocol values; unlisted future numeric values remain valid.
type DyadError int

// DyadMode Known protocol values; unlisted future numeric values remain valid.
type DyadMode int

// DyadProperty A01 appliance datapoint identifier.
type DyadProperty int

// DyadSelfCleanLevel Known protocol values; unlisted future numeric values remain valid.
type DyadSelfCleanLevel int

// DyadSelfCleanMode Known protocol values; unlisted future numeric values remain valid.
type DyadSelfCleanMode int

// DyadState Presence-aware device state; nil fields were not returned by the appliance. Numeric enums retain future values. Only scalar datapoints with a documented type are projected; other known IDs are inventory entries and cannot be selected by this operation.
type DyadState struct {
	// AutoDry Known DyadSwitch values and future numeric values are accepted.
	AutoDry *DyadSwitch `json:"autoDry,omitempty"`

	// AutoDryMode Known DyadSwitch values and future numeric values are accepted.
	AutoDryMode *DyadSwitch `json:"autoDryMode,omitempty"`

	// AutoSelfCleanSet Known DyadSwitch values and future numeric values are accepted.
	AutoSelfCleanSet *DyadSwitch `json:"autoSelfCleanSet,omitempty"`

	// AutoSelfCleanSetMode Known DyadSelfCleanMode values and future numeric values are accepted.
	AutoSelfCleanSetMode *DyadSelfCleanMode `json:"autoSelfCleanSetMode,omitempty"`

	// BrushLeft Device-reported integer value.
	BrushLeft *int `json:"brushLeft,omitempty"`

	// BrushSpeed Known DyadBrushSpeed values and future numeric values are accepted.
	BrushSpeed *DyadBrushSpeed `json:"brushSpeed,omitempty"`

	// CleanMode Known DyadCleanMode values and future numeric values are accepted.
	CleanMode *DyadCleanMode `json:"cleanMode,omitempty"`

	// CountdownTime Device-reported integer value.
	CountdownTime *int `json:"countdownTime,omitempty"`

	// DryCountdown Device-reported integer value.
	DryCountdown *int `json:"dryCountdown,omitempty"`

	// Error Known DyadError values and future numeric values are accepted.
	Error *DyadError `json:"error,omitempty"`

	// MeshLeft Device-reported integer value.
	MeshLeft *int `json:"meshLeft,omitempty"`

	// Power Device-reported integer value.
	Power *int `json:"power,omitempty"`

	// RecentRunTime Daily cleaning durations, in minutes, decoded from the comma-delimited appliance value.
	RecentRunTime *[]int `json:"recentRunTime,omitempty"`

	// SelfCleanLevel Known DyadSelfCleanLevel values and future numeric values are accepted.
	SelfCleanLevel *DyadSelfCleanLevel `json:"selfCleanLevel,omitempty"`

	// SelfCleanMode Known DyadSelfCleanMode values and future numeric values are accepted.
	SelfCleanMode *DyadSelfCleanMode `json:"selfCleanMode,omitempty"`

	// SilentDryDuration Device-reported integer value.
	SilentDryDuration *int `json:"silentDryDuration,omitempty"`

	// SilentMode Known DyadSwitch values and future numeric values are accepted.
	SilentMode *DyadSwitch `json:"silentMode,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeEndTime *int `json:"silentModeEndTime,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeStartTime *int `json:"silentModeStartTime,omitempty"`

	// StandLockAutoRun Known DyadSwitch values and future numeric values are accepted.
	StandLockAutoRun *DyadSwitch `json:"standLockAutoRun,omitempty"`

	// Status Known DyadStatus values and future numeric values are accepted.
	Status *DyadStatus `json:"status,omitempty"`

	// Suction Known DyadSuction values and future numeric values are accepted.
	Suction *DyadSuction `json:"suction,omitempty"`

	// TotalRunTime Device-reported integer value.
	TotalRunTime *int `json:"totalRunTime,omitempty"`

	// Volume Speaker volume percent, from 0 through 100.
	Volume *int `json:"volume,omitempty"`

	// WarmLevel Known DyadWarmLevel values and future numeric values are accepted.
	WarmLevel *DyadWarmLevel `json:"warmLevel,omitempty"`

	// WaterLevel Known DyadWaterLevel values and future numeric values are accepted.
	WaterLevel *DyadWaterLevel `json:"waterLevel,omitempty"`
}

// DyadStatus Known protocol values; unlisted future numeric values remain valid.
type DyadStatus int

// DyadSuction Known protocol values; unlisted future numeric values remain valid.
type DyadSuction int

// DyadSwitch Dyad switch encoded as integer 0 (off) or 1 (on). Unlisted values remain representable.
type DyadSwitch int

// DyadWarmLevel Known protocol values; unlisted future numeric values remain valid.
type DyadWarmLevel int

// DyadWaterLevel Known protocol values; unlisted future numeric values remain valid.
type DyadWaterLevel int

// GetDyadStateRequest Select the appliance-supported properties to query. Every selected property must be returned before the transport completes; unselected state fields remain nil. Select only properties represented by the typed state model; metadata and unknown-shape datapoints are unsupported by this method.
type GetDyadStateRequest struct {
	Properties []DyadProperty `json:"properties"`
}

// GetZeoStateRequest Select the appliance-supported properties to query. Every selected property must be returned before the transport completes; unselected state fields remain nil. Select only properties represented by the typed state model; metadata and unknown-shape datapoints are unsupported by this method.
type GetZeoStateRequest struct {
	Properties []ZeoProperty `json:"properties"`
}

// SetDyadSettingsRequest Sparse settings update. Absent fields are never sent. Integer switches use the appliance protocol value (typically 0 or 1).
type SetDyadSettingsRequest struct {
	// AutoDry Known DyadSwitch values and future numeric values are accepted.
	AutoDry *DyadSwitch `json:"autoDry,omitempty"`

	// AutoDryMode Known DyadSwitch values and future numeric values are accepted.
	AutoDryMode *DyadSwitch `json:"autoDryMode,omitempty"`

	// AutoSelfCleanSet Known DyadSwitch values and future numeric values are accepted.
	AutoSelfCleanSet *DyadSwitch `json:"autoSelfCleanSet,omitempty"`

	// AutoSelfCleanSetMode Known DyadSelfCleanMode values and future numeric values are accepted.
	AutoSelfCleanSetMode *DyadSelfCleanMode `json:"autoSelfCleanSetMode,omitempty"`

	// BrushSpeed Known DyadBrushSpeed values and future numeric values are accepted.
	BrushSpeed *DyadBrushSpeed `json:"brushSpeed,omitempty"`

	// CleanMode Known DyadCleanMode values and future numeric values are accepted.
	CleanMode *DyadCleanMode `json:"cleanMode,omitempty"`

	// SelfCleanLevel Known DyadSelfCleanLevel values and future numeric values are accepted.
	SelfCleanLevel *DyadSelfCleanLevel `json:"selfCleanLevel,omitempty"`

	// SelfCleanMode Known DyadSelfCleanMode values and future numeric values are accepted.
	SelfCleanMode *DyadSelfCleanMode `json:"selfCleanMode,omitempty"`

	// SilentDryDuration Device-reported integer value.
	SilentDryDuration *int `json:"silentDryDuration,omitempty"`

	// SilentMode Known DyadSwitch values and future numeric values are accepted.
	SilentMode *DyadSwitch `json:"silentMode,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeEndTime *int `json:"silentModeEndTime,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeStartTime *int `json:"silentModeStartTime,omitempty"`

	// StandLockAutoRun Known DyadSwitch values and future numeric values are accepted.
	StandLockAutoRun *DyadSwitch `json:"standLockAutoRun,omitempty"`

	// Suction Known DyadSuction values and future numeric values are accepted.
	Suction *DyadSuction `json:"suction,omitempty"`

	// Volume Speaker volume percent, from 0 through 100.
	Volume *int `json:"volume,omitempty"`

	// WarmLevel Known DyadWarmLevel values and future numeric values are accepted.
	WarmLevel *DyadWarmLevel `json:"warmLevel,omitempty"`

	// WaterLevel Known DyadWaterLevel values and future numeric values are accepted.
	WaterLevel *DyadWaterLevel `json:"waterLevel,omitempty"`
}

// SetZeoSettingsRequest Sparse settings update. Absent fields are never sent. Switches use boolean values on the appliance protocol.
type SetZeoSettingsRequest struct {
	// ChildLock Appliance boolean value.
	ChildLock *bool `json:"childLock,omitempty"`

	// Countdown Device-reported integer value.
	Countdown *int `json:"countdown,omitempty"`

	// DetergentExpansionType Known ZeoDetergentExpansionType values and future numeric values are accepted.
	DetergentExpansionType *ZeoDetergentExpansionType `json:"detergentExpansionType,omitempty"`

	// DetergentSet Appliance boolean value.
	DetergentSet *bool `json:"detergentSet,omitempty"`

	// DetergentType Known ZeoDetergentType values and future numeric values are accepted.
	DetergentType *ZeoDetergentType `json:"detergentType,omitempty"`

	// DetergentVolume Device-reported integer value.
	DetergentVolume *int `json:"detergentVolume,omitempty"`

	// LightSetting Appliance boolean value.
	LightSetting *bool `json:"lightSetting,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeEndTime *int `json:"silentModeEndTime,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeStartTime *int `json:"silentModeStartTime,omitempty"`

	// SoftenerExpansionType Known ZeoSoftenerExpansionType values and future numeric values are accepted.
	SoftenerExpansionType *ZeoSoftenerExpansionType `json:"softenerExpansionType,omitempty"`

	// SoftenerSet Appliance boolean value.
	SoftenerSet *bool `json:"softenerSet,omitempty"`

	// SoftenerType Known ZeoSoftenerType values and future numeric values are accepted.
	SoftenerType *ZeoSoftenerType `json:"softenerType,omitempty"`

	// SoftenerVolume Device-reported integer value.
	SoftenerVolume *int `json:"softenerVolume,omitempty"`

	// Sound Appliance boolean value.
	Sound *bool `json:"sound,omitempty"`
}

// StartZeoRequest Start command. Mode and program must be supplied together; optional settings are sent only when provided. Acknowledgement is not completion of the physical cycle.
type StartZeoRequest struct {
	// DryCareMode Known ZeoDryAndCare values and future numeric values are accepted.
	DryCareMode *ZeoDryAndCare `json:"dryCareMode,omitempty"`

	// DryingMethod Known ZeoDryingMethod values and future numeric values are accepted.
	DryingMethod *ZeoDryingMethod `json:"dryingMethod,omitempty"`

	// DryingMode Known ZeoDryingMode values and future numeric values are accepted.
	DryingMode *ZeoDryingMode `json:"dryingMode,omitempty"`

	// Mode Known ZeoMode values and future numeric values are accepted.
	Mode ZeoMode `json:"mode"`

	// Program Known ZeoProgram values and future numeric values are accepted.
	Program ZeoProgram `json:"program"`

	// Rinse Known ZeoRinse values and future numeric values are accepted.
	Rinse *ZeoRinse `json:"rinse,omitempty"`

	// Soak Known ZeoSoak values and future numeric values are accepted.
	Soak *ZeoSoak `json:"soak,omitempty"`

	// Spin Known ZeoSpin values and future numeric values are accepted.
	Spin *ZeoSpin `json:"spin,omitempty"`

	// SteamVolume Known ZeoSteamVolume values and future numeric values are accepted.
	SteamVolume *ZeoSteamVolume `json:"steamVolume,omitempty"`

	// Temperature Known ZeoTemperature values and future numeric values are accepted.
	Temperature *ZeoTemperature `json:"temperature,omitempty"`
}

// ZeoDetergentExpansionType Known protocol values; unlisted future numeric values remain valid.
type ZeoDetergentExpansionType int

// ZeoDetergentType Known protocol values; unlisted future numeric values remain valid.
type ZeoDetergentType int

// ZeoDirtDetectionStatus Known protocol values; unlisted future numeric values remain valid.
type ZeoDirtDetectionStatus int

// ZeoDryAndCare Known protocol values; unlisted future numeric values remain valid.
type ZeoDryAndCare int

// ZeoDryerStartError Known protocol values; unlisted future numeric values remain valid.
type ZeoDryerStartError int

// ZeoDryingMethod Known protocol values; unlisted future numeric values remain valid.
type ZeoDryingMethod int

// ZeoDryingMode Known protocol values; unlisted future numeric values remain valid.
type ZeoDryingMode int

// ZeoError Known protocol values; unlisted future numeric values remain valid.
type ZeoError int

// ZeoFeatureBits Known protocol values; unlisted future numeric values remain valid.
type ZeoFeatureBits int

// ZeoMode Known protocol values; unlisted future numeric values remain valid.
type ZeoMode int

// ZeoProgram Known protocol values; unlisted future numeric values remain valid.
type ZeoProgram int

// ZeoProperty A01 appliance datapoint identifier.
type ZeoProperty int

// ZeoRinse Known rinse intensity protocol positions, not a literal count of rinses. Public fields also accept future numeric positions.
type ZeoRinse int

// ZeoSoak Known protocol values; unlisted future numeric values remain valid.
type ZeoSoak int

// ZeoSoftenerExpansionType Known protocol values; unlisted future numeric values remain valid.
type ZeoSoftenerExpansionType int

// ZeoSoftenerType Known protocol values; unlisted future numeric values remain valid.
type ZeoSoftenerType int

// ZeoSpin Known spin protocol positions, not RPM: 1 = no spin, 2 = 400 RPM, 3 = 600 RPM, 4 = 800 RPM, 5 = 1000 RPM, 6 = 1200 RPM, 7 = 1400 RPM. Public fields also accept future numeric positions.
type ZeoSpin int

// ZeoState Presence-aware device state; nil fields were not returned by the appliance. Numeric enums retain future values. Only scalar datapoints with a documented type are projected; other known IDs are inventory entries and cannot be selected by this operation.
type ZeoState struct {
	// AppAuthorization Device-reported integer value.
	AppAuthorization *int `json:"appAuthorization,omitempty"`

	// ChildLock Appliance boolean value.
	ChildLock *bool `json:"childLock,omitempty"`

	// Countdown Device-reported integer value.
	Countdown *int `json:"countdown,omitempty"`

	// CustomParamGet Device-reported integer value.
	CustomParamGet *int `json:"customParamGet,omitempty"`

	// CustomParamSave Device-reported integer value.
	CustomParamSave *int `json:"customParamSave,omitempty"`

	// CustomProgramCleaningTime Device-reported integer value.
	CustomProgramCleaningTime *int `json:"customProgramCleaningTime,omitempty"`

	// DefaultSetting Appliance boolean value.
	DefaultSetting *bool `json:"defaultSetting,omitempty"`

	// DetergentEmpty Appliance boolean value.
	DetergentEmpty *bool `json:"detergentEmpty,omitempty"`

	// DetergentExpansionType Known ZeoDetergentExpansionType values and future numeric values are accepted.
	DetergentExpansionType *ZeoDetergentExpansionType `json:"detergentExpansionType,omitempty"`

	// DetergentSet Appliance boolean value.
	DetergentSet *bool `json:"detergentSet,omitempty"`

	// DetergentType Known ZeoDetergentType values and future numeric values are accepted.
	DetergentType *ZeoDetergentType `json:"detergentType,omitempty"`

	// DetergentVolume Device-reported integer value.
	DetergentVolume *int `json:"detergentVolume,omitempty"`

	// DirtDetectionStatus Known ZeoDirtDetectionStatus values and future numeric values are accepted.
	DirtDetectionStatus *ZeoDirtDetectionStatus `json:"dirtDetectionStatus,omitempty"`

	// DoorLockState Appliance boolean value.
	DoorLockState *bool `json:"doorLockState,omitempty"`

	// DryCareMode Known ZeoDryAndCare values and future numeric values are accepted.
	DryCareMode *ZeoDryAndCare `json:"dryCareMode,omitempty"`

	// DryingMethod Known ZeoDryingMethod values and future numeric values are accepted.
	DryingMethod *ZeoDryingMethod `json:"dryingMethod,omitempty"`

	// DryingMode Known ZeoDryingMode values and future numeric values are accepted.
	DryingMode *ZeoDryingMode `json:"dryingMode,omitempty"`

	// Error Known ZeoError values and future numeric values are accepted.
	Error *ZeoError `json:"error,omitempty"`

	// FeatureBits Device-reported integer value.
	FeatureBits *int `json:"featureBits,omitempty"`

	// LightSetting Appliance boolean value.
	LightSetting *bool `json:"lightSetting,omitempty"`

	// Mode Known ZeoMode values and future numeric values are accepted.
	Mode *ZeoMode `json:"mode,omitempty"`

	// Pause Appliance boolean value.
	Pause *bool `json:"pause,omitempty"`

	// Program Known ZeoProgram values and future numeric values are accepted.
	Program *ZeoProgram `json:"program,omitempty"`

	// Rinse Known ZeoRinse values and future numeric values are accepted.
	Rinse *ZeoRinse `json:"rinse,omitempty"`

	// Shutdown Appliance boolean value.
	Shutdown *bool `json:"shutdown,omitempty"`

	// SilentModeEndTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeEndTime *int `json:"silentModeEndTime,omitempty"`

	// SilentModeStartTime Minute of day, from 0 through 1439, in the appliance local timezone.
	SilentModeStartTime *int `json:"silentModeStartTime,omitempty"`

	// Soak Known ZeoSoak values and future numeric values are accepted.
	Soak *ZeoSoak `json:"soak,omitempty"`

	// SoftenerEmpty Appliance boolean value.
	SoftenerEmpty *bool `json:"softenerEmpty,omitempty"`

	// SoftenerExpansionType Known ZeoSoftenerExpansionType values and future numeric values are accepted.
	SoftenerExpansionType *ZeoSoftenerExpansionType `json:"softenerExpansionType,omitempty"`

	// SoftenerSet Appliance boolean value.
	SoftenerSet *bool `json:"softenerSet,omitempty"`

	// SoftenerType Known ZeoSoftenerType values and future numeric values are accepted.
	SoftenerType *ZeoSoftenerType `json:"softenerType,omitempty"`

	// SoftenerVolume Device-reported integer value.
	SoftenerVolume *int `json:"softenerVolume,omitempty"`

	// Sound Appliance boolean value.
	Sound *bool `json:"sound,omitempty"`

	// Spin Known ZeoSpin values and future numeric values are accepted.
	Spin *ZeoSpin `json:"spin,omitempty"`

	// Start Appliance boolean value.
	Start *bool `json:"start,omitempty"`

	// StartDryerError Known ZeoDryerStartError values and future numeric values are accepted.
	StartDryerError *ZeoDryerStartError `json:"startDryerError,omitempty"`

	// Status Known ZeoStatus values and future numeric values are accepted.
	Status *ZeoStatus `json:"status,omitempty"`

	// SteamCareTime Device-reported integer value.
	SteamCareTime *int `json:"steamCareTime,omitempty"`

	// SteamVolume Known ZeoSteamVolume values and future numeric values are accepted.
	SteamVolume *ZeoSteamVolume `json:"steamVolume,omitempty"`

	// Temperature Known ZeoTemperature values and future numeric values are accepted.
	Temperature *ZeoTemperature `json:"temperature,omitempty"`

	// TimesAfterClean Device-reported integer value.
	TimesAfterClean *int `json:"timesAfterClean,omitempty"`

	// TotalTime Device-reported integer value.
	TotalTime *int `json:"totalTime,omitempty"`

	// WashingLeft Device-reported integer value.
	WashingLeft *int `json:"washingLeft,omitempty"`
}

// ZeoStatus Known protocol values; unlisted future numeric values remain valid.
type ZeoStatus int

// ZeoSteamVolume Known protocol values; unlisted future numeric values remain valid.
type ZeoSteamVolume int

// ZeoTemperature Known temperature protocol positions, not degrees Celsius: 1 = unheated, 2 = 30 C, 3 = 40 C, 4 = 60 C, 5 = 90 C, 6 = 20 C, 7 = 95 C. Public fields also accept future numeric positions.
type ZeoTemperature int
