// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.

package roborock

// Defines values for DeviceFamily.
const (
	FamilyB01Q10   DeviceFamily = "b01_q10"
	FamilyB01Q7    DeviceFamily = "b01_q7"
	FamilyDyad     DeviceFamily = "dyad"
	FamilyUnknown  DeviceFamily = "unknown"
	FamilyV1Vacuum DeviceFamily = "v1_vacuum"
	FamilyZeo      DeviceFamily = "zeo"
)

// Defines values for HomeDataVersion.
const (
	HomeDataV1 HomeDataVersion = 1
	HomeDataV2 HomeDataVersion = 2
	HomeDataV3 HomeDataVersion = 3
)

// Defines values for ProtocolVersion.
const (
	ProtocolA01 ProtocolVersion = "A01"
	ProtocolB01 ProtocolVersion = "B01"
	ProtocolL01 ProtocolVersion = "L01"
	ProtocolV1  ProtocolVersion = "1.0"
)

// Defines values for Region.
const (
	RegionCN Region = "cn"
	RegionEU Region = "eu"
	RegionRU Region = "ru"
	RegionUS Region = "us"
)

// AuthContext defines model for AuthContext.
type AuthContext struct {
	// BaseURL Regional IoT HTTPS origin.
	BaseURL string `json:"baseUrl"`

	// ClientID Login identity that produced these credentials.
	ClientID string   `json:"clientId"`
	Mqtt     MQTTAuth `json:"mqtt"`

	// Token Current account token; caller owns storage and replacement.
	Token string `json:"token"`
}

// Device defines model for Device.
type Device struct {
	// Capability Vendor capability flags when present.
	Capability *int64 `json:"capability,omitempty"`

	// Category Open product category independent of capabilities.
	Category *string `json:"category,omitempty"`

	// Family Open implementation family derived from protocol, model and category. Unknown devices remain discoverable.
	Family   *DeviceFamily `json:"family,omitempty"`
	Firmware *string       `json:"firmware,omitempty"`
	ID       string        `json:"id"`

	// LocalKey Device encryption secret; do not log it.
	LocalKey  string `json:"localKey"`
	Model     string `json:"model"`
	Name      string `json:"name"`
	Online    *bool  `json:"online,omitempty"`
	ProductID string `json:"productId"`

	// Protocol Open device protocol value. Unsupported future versions remain visible to callers.
	Protocol ProtocolVersion `json:"protocol"`
	RoomID   *int64          `json:"roomId,omitempty"`

	// Shared True when discovered through the vendor shared-device list.
	Shared bool `json:"shared"`

	// SupportedProperties Advertised numeric datapoint IDs; select typed A01 query properties from this inventory.
	SupportedProperties []int `json:"supportedProperties"`
}

// DeviceFamily Open implementation family derived from protocol, model and category. Unknown devices remain discoverable.
type DeviceFamily string

// Home defines model for Home.
type Home struct {
	// ID Roborock home identifier for home-data requests.
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// HomeData defines model for HomeData.
type HomeData struct {
	Devices []Device `json:"devices"`
	Home    Home     `json:"home"`
	Rooms   []Room   `json:"rooms"`
}

// HomeDataVersion Supported home-data route revision. Zero in a request selects HomeDataV1.
type HomeDataVersion int

// LoginContext defines model for LoginContext.
type LoginContext struct {
	// BaseURL Optional explicit regional HTTPS origin.
	BaseURL *string `json:"baseUrl,omitempty"`

	// ClientID Stable caller-owned login identity; reuse it across code request and exchange.
	ClientID string `json:"clientId"`

	// Country Country code returned by region resolution or selected by the caller.
	Country string `json:"country"`

	// CountryCode Calling code required by the login endpoint.
	CountryCode string `json:"countryCode"`

	// Email Account email address.
	Email string `json:"email"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Auth     AuthContext `json:"auth"`
	Nickname string      `json:"nickname"`
	UserID   int64       `json:"userId"`
}

// MQTTAuth defines model for MQTTAuth.
type MQTTAuth struct {
	// APIURL Hawk-authenticated API origin returned by the vendor.
	APIURL string `json:"apiUrl"`

	// BrokerURL Broker endpoint returned by the vendor.
	BrokerURL string `json:"brokerUrl"`

	// Key Account MQTT derivation key.
	Key string `json:"key"`

	// Secret Account secret used to derive MQTT password.
	Secret string `json:"secret"`

	// SigningKey Hawk HMAC signing key.
	SigningKey string `json:"signingKey"`

	// User Account identifier used to derive MQTT identity.
	User string `json:"user"`
}

// ProtocolVersion Open device protocol value. Unsupported future versions remain visible to callers.
type ProtocolVersion string

// Region Open region value. Known regions are us, eu, cn and ru.
type Region string

// Room defines model for Room.
type Room struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
