// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.

package roborock

// CloudRoom defines model for CloudRoom.
type CloudRoom struct {
	ID int64 `json:"id"`

	// Name Absent when the cloud does not report a room name.
	Name *string `json:"name,omitempty"`
}

// DeviceCapabilities defines model for DeviceCapabilities.
type DeviceCapabilities struct {
	MapContent   bool `json:"mapContent"`
	MapList      bool `json:"mapList"`
	MapRooms     bool `json:"mapRooms"`
	MapSelection bool `json:"mapSelection"`

	// MapTrace Separate trace stream requests; map and trace need not form one coherent snapshot.
	MapTrace     bool `json:"mapTrace"`
	RoomCleaning bool `json:"roomCleaning"`
	ZoneCleaning bool `json:"zoneCleaning"`
}

// GetMapRequest defines model for GetMapRequest.
type GetMapRequest struct {
	// MapID Opaque map identifier. Empty requests the current map. Q10 only supports current-map reads.
	MapID string `json:"mapId,omitempty"`
}

// HomeRoomsRequest defines model for HomeRoomsRequest.
type HomeRoomsRequest struct {
	// Auth Caller-owned account credentials.
	Auth   AuthContext `json:"auth"`
	HomeID int64       `json:"homeId"`
}

// ListMapsResult defines model for ListMapsResult.
type ListMapsResult struct {
	Maps []MapInfo `json:"maps"`
}

// MapInfo defines model for MapInfo.
type MapInfo struct {
	// Current Present only when the family reports active-map identity.
	Current *bool `json:"current,omitempty"`

	// ID Opaque identifier returned unchanged to map operations.
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

// MapRoomMapping defines model for MapRoomMapping.
type MapRoomMapping struct {
	// IoTID Optional V1 cloud room identity; unrelated to a map ID.
	IoTID *string `json:"iotId,omitempty"`
	Name  *string `json:"name,omitempty"`

	// SegmentID Device room or segment identifier accepted by CleanSegments.
	SegmentID int64 `json:"segmentId"`
}

// MapRoomsResult defines model for MapRoomsResult.
type MapRoomsResult struct {
	Rooms []MapRoomMapping `json:"rooms"`
}

// RoomsResult defines model for RoomsResult.
type RoomsResult struct {
	Rooms []CloudRoom `json:"rooms"`
}

// SelectMapRequest defines model for SelectMapRequest.
type SelectMapRequest struct {
	// MapID Opaque V1 map identifier from ListMaps. Selecting changes the device active map.
	MapID string `json:"mapId"`
}

// SharedDeviceRoomsRequest defines model for SharedDeviceRoomsRequest.
type SharedDeviceRoomsRequest struct {
	// Auth Caller-owned account credentials.
	Auth     AuthContext `json:"auth"`
	DeviceID string      `json:"deviceId"`
}
