// Code generated by tools/generate from api/maps-models.openapi.yaml; DO NOT EDIT.

package roborock

import "github.com/portpowered/go-roborock/internal/mapmodel"

// MapFormatQ10 is a map protocol value.
const MapFormatQ10 = mapmodel.MapFormatQ10

// MapFormatQ7 is a map protocol value.
const MapFormatQ7 = mapmodel.MapFormatQ7

// MapFormatV1 is a map protocol value.
const MapFormatV1 = mapmodel.MapFormatV1

// MapFrameQ10Array is a map protocol value.
const MapFrameQ10Array = mapmodel.MapFrameQ10Array

// MapFrameQ10Trace is a map protocol value.
const MapFrameQ10Trace = mapmodel.MapFrameQ10Trace

// MapFrameQ10World is a map protocol value.
const MapFrameQ10World = mapmodel.MapFrameQ10World

// MapFrameQ7World is a map protocol value.
const MapFrameQ7World = mapmodel.MapFrameQ7World

// MapFrameV1World is a map protocol value.
const MapFrameV1World = mapmodel.MapFrameV1World

// Minus1 is a map protocol value.
const Minus1 = mapmodel.Minus1

// N1 is a map protocol value.
const N1 = mapmodel.N1

// Degrees is a map protocol value.
const Degrees = mapmodel.Degrees

// Radians is a map protocol value.
const Radians = mapmodel.Radians

// MapUnitMeters is a map protocol value.
const MapUnitMeters = mapmodel.MapUnitMeters

// MapUnitMillimeters is a map protocol value.
const MapUnitMillimeters = mapmodel.MapUnitMillimeters

// MapUnitPixels is a map protocol value.
const MapUnitPixels = mapmodel.MapUnitPixels

// MapArea describes a decoded Roborock map value.
type MapArea = mapmodel.MapArea

// MapFormat describes a decoded Roborock map value.
type MapFormat = mapmodel.MapFormat

// MapFrame describes a decoded Roborock map value.
type MapFrame = mapmodel.MapFrame

// MapGrid describes a decoded Roborock map value.
type MapGrid = mapmodel.MapGrid

// MapGridRowYDirection describes a decoded Roborock map value.
type MapGridRowYDirection = mapmodel.MapGridRowYDirection

// MapPath describes a decoded Roborock map value.
type MapPath = mapmodel.MapPath

// MapPoint describes a decoded Roborock map value.
type MapPoint = mapmodel.MapPoint

// MapPose describes a decoded Roborock map value.
type MapPose = mapmodel.MapPose

// MapPoseHeadingUnit describes a decoded Roborock map value.
type MapPoseHeadingUnit = mapmodel.MapPoseHeadingUnit

// MapRectangle describes a decoded Roborock map value.
type MapRectangle = mapmodel.MapRectangle

// MapRoom describes a decoded Roborock map value.
type MapRoom = mapmodel.MapRoom

// MapSnapshot describes a decoded Roborock map value.
type MapSnapshot = mapmodel.MapSnapshot

// MapUnit describes a decoded Roborock map value.
type MapUnit = mapmodel.MapUnit

// MapUnknownBlock describes a decoded Roborock map value.
type MapUnknownBlock = mapmodel.MapUnknownBlock
