// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	externalRef0 "github.com/portpowered/go-roborock/pkg/roborock"
	roborock "github.com/portpowered/go-roborock/pkg/roborock"
)

// CameraIdentity defines model for CameraIdentity.
type CameraIdentity struct {
	Negotiated bool `json:"negotiated"`
}

// CommandInput defines model for CommandInput.
type CommandInput struct {
	Auth           externalRef0.AuthContext       `json:"auth,omitempty"`
	Camera         externalRef0.OpenCameraRequest `json:"camera,omitempty"`
	ClientID       string                         `json:"clientId,omitempty"`
	Code           string                         `json:"code,omitempty"`
	DeviceID       string                         `json:"deviceId,omitempty"`
	DyadProperties []roborock.DyadProperty        `json:"dyadProperties,omitempty"`
	Email          string                         `json:"email,omitempty"`
	LocalKey       string                         `json:"localKey,omitempty"`
	Login          externalRef0.LoginContext      `json:"login,omitempty"`
	Password       string                         `json:"password,omitempty"`
	Protocol       externalRef0.ProtocolVersion   `json:"protocol,omitempty"`
	ZeoProperties  []roborock.ZeoProperty         `json:"zeoProperties,omitempty"`
}

// CredentialExport defines model for CredentialExport.
type CredentialExport struct {
	Auth  *externalRef0.AuthContext  `json:"auth,omitempty"`
	Login *externalRef0.LoginContext `json:"login,omitempty"`
}

// LoginIdentity defines model for LoginIdentity.
type LoginIdentity struct {
	Nickname string `json:"nickname"`
	UserID   int64  `json:"userId"`
}
