// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	RESTHawkEntropyBytes   = 6
	RESTHawkHeaderFormat   = "Hawk id=\"%s\",s=\"%s\",ts=\"%s\",nonce=\"%s\",mac=\"%s\""
	RESTHawkMACInputFormat = "%s:%s:%s:%s:%s::"
	RESTHeaderAccept       = "Accept"
	RESTHeaderContentType  = "Content-Type"
	RESTMediaForm          = "application/x-www-form-urlencoded"
	RESTMediaJSON          = "application/json"
	RESTMercyCharacters    = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	RESTMercyNonceLength   = 16
)
