// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	RESTHeaderAccept      = "Accept"
	RESTHeaderContentType = "Content-Type"
	RESTMediaForm         = "application/x-www-form-urlencoded"
	RESTMediaJSON         = "application/json"
)
