// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	B01EmptyObjectJSON        = "{}"
	B01Hash                   = "5wwh9ikChRjASpMU8cxg7o1d2E"
	B01IVHexEnd               = 25
	B01IVHexStart             = 9
	B01Q10CommonDatapoint     = "101"
	B01Q10CurrentMapDatapoint = "102"
	B01Q10MapListDatapoint    = "61"
	B01Q10MapListOperation    = "list"
	B01Q10MapListRequestJSON  = "{\"61\":{\"op\":\"list\"}}"
	B01Q10MapListSuccess      = 1
	B01Q10RoomCleanCommand    = 2
	B01Q10StartCleanDatapoint = "201"
	B01Q10ZoneCleanCommand    = 3
	B01Q7CleanStart           = 1
	B01Q7Datapoint            = "10000"
	B01Q7MapKeyHexEnd         = 24
	B01Q7MapKeyHexStart       = 8
	B01Q7MapKeyInputFormat    = "%s+%s+%s"
	B01Q7MessageIDBase        = 100000000000
	B01Q7MessageIDRange       = 900000000000
	B01Q7MethodPattern        = "^[a-zA-Z0-9_.]+$"
	B01Q7ModelKeyBytes        = 16
	B01Q7ModelKeyPadding      = "0"
	B01Q7RoomCleanType        = 1
	B01Version                = "B01"
	DeviceCategoryVacuum      = "robot.vacuum.cleaner"
	DeviceCategoryWasher      = "roborock.wm"
	DeviceCategoryWetDry      = "roborock.wetdryvac"
	DeviceQ10ModelPrefix      = "ss"
	DeviceQ7ModelPrefix       = "sc"
	Q10ZoneCoordinateBytes    = 2
	Q10ZoneCoordinateOffsetMM = 25500
	Q10ZoneCount              = 1
	Q10ZoneHeaderSize         = 4
	Q10ZoneMaxRepeat          = 3
	Q10ZoneMinRepeat          = 1
	Q10ZoneNameBytes          = 19
	Q10ZoneNameLengthBytes    = 1
	Q10ZoneVectorUnitMM       = 5
	Q10ZoneVersion            = 1
	Q10ZoneVertexBytes        = 4
	Q10ZoneVertices           = 4
)
