// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	MapBlockCharger              = 1
	MapBlockCurrentZones         = 6
	MapBlockGotoPath             = 4
	MapBlockGotoTarget           = 7
	MapBlockHeaderMinimum        = 8
	MapBlockImage                = 2
	MapBlockNoCarpet             = 19
	MapBlockNoGo                 = 9
	MapBlockNoMop                = 12
	MapBlockPath                 = 3
	MapBlockPredictedPath        = 5
	MapBlockRobot                = 8
	MapBlockRooms                = 11
	MapBlockWalls                = 10
	MapQ10CompressedLengthOffset = 27
	MapQ10DockHeadingOffset      = 21
	MapQ10DockXOffset            = 17
	MapQ10DockYOffset            = 19
	MapQ10HeaderLength           = 29
	MapQ10HeightOffset           = 9
	MapQ10IDOffset               = 2
	MapQ10OriginXOffset          = 11
	MapQ10OriginYOffset          = 13
	MapQ10ResolutionOffset       = 15
	MapQ10RoomNameLengthOffset   = 26
	MapQ10RoomNameOffset         = 27
	MapQ10RoomRecordLength       = 47
	MapQ10TraceHeaderLength      = 14
	MapQ10TraceHeadingOffset     = 10
	MapQ10TracePointCountOffset  = 8
	MapQ10WidthOffset            = 7
	MapV1HeaderMinimum           = 20
	MapV1Magic                   = "rr"
)
