// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	MapsProtocolResponse  = 301
	MapsQ10CurrentPrefix  = 1
	MapsQ10PrefixSize     = 2
	MapsQ10PrefixVersion  = 1
	MapsQ10TracePrefix    = 2
	MapsQ7ListMethod      = "service.get_map_list"
	MapsQ7RoomCleanMethod = "service.set_room_clean"
	MapsQ7UploadMethod    = "service.upload_by_mapid"
	MapsV1EndpointEnd     = 8
	MapsV1EndpointOffset  = 0
	MapsV1GetMethod       = "get_map_v1"
	MapsV1HeaderSize      = 24
	MapsV1ListMethod      = "get_multi_maps_list"
	MapsV1LoadMethod      = "load_multi_map"
	MapsV1RequestIDEnd    = 18
	MapsV1RequestIDOffset = 16
	MapsV1RequestIDRange  = 65535
	MapsV1RoomsMethod     = "get_room_mapping"
	RPCGetMultiMapsList   = "get_multi_maps_list"
	RPCGetRoomMapping     = "get_room_mapping"
	RPCLoadMultiMap       = "load_multi_map"
)
