// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	MQTTA01Hash              = "726f626f726f636b2d67a6d6da"
	MQTTConnAck              = 32
	MQTTConnect              = 16
	MQTTConnectFlags         = 194
	MQTTFrameChecksumSize    = 4
	MQTTFrameHeaderSize      = 19
	MQTTKeepaliveSeconds     = 45
	MQTTPingReq              = 192
	MQTTPingResp             = 208
	MQTTProtocolLevel        = 4
	MQTTProtocolName         = "MQTT"
	MQTTProtocolRequest      = 101
	MQTTProtocolResponse     = 102
	MQTTPubAck               = 64
	MQTTPublish              = 48
	MQTTPublishTopicPrefix   = "rr/m/i/"
	MQTTQoSAtLeastOnce       = 1
	MQTTQoSAtMostOnce        = 0
	MQTTQueryDatapoint       = "10000"
	MQTTRPCRequestDatapoint  = "101"
	MQTTRPCResponseDatapoint = "102"
	MQTTSubAck               = 144
	MQTTSubscribe            = 130
	MQTTSubscribeTopicPrefix = "rr/m/o/"
	MQTTVersionA01           = "A01"
	MQTTVersionV1            = "1.0"
	MQTTWireSalt             = "TXdfu$jyZ#TZHsg4"
)
