// Code generated by tools/generate from schema x-wire-constants; DO NOT EDIT.
package protocol

const (
	MQTTA01Hash                  = "726f626f726f636b2d67a6d6da"
	MQTTBadUsernamePassword      = 4
	MQTTConnAck                  = 32
	MQTTConnAckLength            = 2
	MQTTConnect                  = 16
	MQTTConnectFlags             = 194
	MQTTFrameChecksumSize        = 4
	MQTTFrameHeaderSize          = 19
	MQTTFramePayloadLengthOffset = 17
	MQTTFramePayloadOffset       = 19
	MQTTFrameProtocolOffset      = 15
	MQTTFrameRandomOffset        = 7
	MQTTFrameSequenceOffset      = 3
	MQTTFrameTimestampOffset     = 11
	MQTTKeepaliveSeconds         = 45
	MQTTKindPublish              = 3
	MQTTKindShift                = 4
	MQTTMaxRemainingLengthOctets = 4
	MQTTMaxStringLength          = 65535
	MQTTNotAuthorized            = 5
	MQTTPingReq                  = 192
	MQTTPingResp                 = 208
	MQTTProtocolLevel            = 4
	MQTTProtocolName             = "MQTT"
	MQTTProtocolRequest          = 101
	MQTTProtocolResponse         = 102
	MQTTPubAck                   = 64
	MQTTPublish                  = 48
	MQTTPublishTopicPrefix       = "rr/m/i/"
	MQTTQoSAtLeastOnce           = 1
	MQTTQoSAtMostOnce            = 0
	MQTTQoSMask                  = 3
	MQTTQueryDatapoint           = "10000"
	MQTTRPCRequestDatapoint      = "101"
	MQTTRPCResponseDatapoint     = "102"
	MQTTSubAck                   = 144
	MQTTSubAckLength             = 3
	MQTTSubscribe                = 130
	MQTTSubscribeIdentifier      = 1
	MQTTSubscribeTopicPrefix     = "rr/m/o/"
	MQTTTopicSeparators          = 2
	MQTTUint16Size               = 2
	MQTTUsernameLength           = 8
	MQTTVarintBase               = 128
	MQTTVarintContinuation       = 128
	MQTTVarintMask               = 127
	MQTTVersionA01               = "A01"
	MQTTVersionV1                = "1.0"
	MQTTWireSalt                 = "TXdfu$jyZ#TZHsg4"
)
